// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/tasks (interfaces: TaskRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/repository_mock.go -package=mocks . TaskRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	sqlx "github.com/jmoiron/sqlx"
	tasks "github.com/yuudev14/ytsoar/internal/application/tasks"
	domain "github.com/yuudev14/ytsoar/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskRepository is a mock of TaskRepository interface.
type MockTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepositoryMockRecorder
	isgomock struct{}
}

// MockTaskRepositoryMockRecorder is the mock recorder for MockTaskRepository.
type MockTaskRepositoryMockRecorder struct {
	mock *MockTaskRepository
}

// NewMockTaskRepository creates a new mock instance.
func NewMockTaskRepository(ctrl *gomock.Controller) *MockTaskRepository {
	mock := &MockTaskRepository{ctrl: ctrl}
	mock.recorder = &MockTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepository) EXPECT() *MockTaskRepositoryMockRecorder {
	return m.recorder
}

// CreateTaskHistory mocks base method.
func (m *MockTaskRepository) CreateTaskHistory(tx *sqlx.Tx, playbookHistoryId string, arg2 []domain.Tasks, graph map[uuid.UUID][]uuid.UUID) ([]domain.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTaskHistory", tx, playbookHistoryId, arg2, graph)
	ret0, _ := ret[0].([]domain.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTaskHistory indicates an expected call of CreateTaskHistory.
func (mr *MockTaskRepositoryMockRecorder) CreateTaskHistory(tx, playbookHistoryId, arg2, graph any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTaskHistory", reflect.TypeOf((*MockTaskRepository)(nil).CreateTaskHistory), tx, playbookHistoryId, arg2, graph)
}

// DeleteTasks mocks base method.
func (m *MockTaskRepository) DeleteTasks(tx *sqlx.Tx, taskIds []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTasks", tx, taskIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTasks indicates an expected call of DeleteTasks.
func (mr *MockTaskRepositoryMockRecorder) DeleteTasks(tx, taskIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTasks", reflect.TypeOf((*MockTaskRepository)(nil).DeleteTasks), tx, taskIds)
}

// GetTaskHistoryByPlaybookHistoryId mocks base method.
func (m *MockTaskRepository) GetTaskHistoryByPlaybookHistoryId(id string, filter tasks.TaskHistoryFilter) ([]domain.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskHistoryByPlaybookHistoryId", id, filter)
	ret0, _ := ret[0].([]domain.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskHistoryByPlaybookHistoryId indicates an expected call of GetTaskHistoryByPlaybookHistoryId.
func (mr *MockTaskRepositoryMockRecorder) GetTaskHistoryByPlaybookHistoryId(id, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskHistoryByPlaybookHistoryId", reflect.TypeOf((*MockTaskRepository)(nil).GetTaskHistoryByPlaybookHistoryId), id, filter)
}

// GetTaskHistoryCount mocks base method.
func (m *MockTaskRepository) GetTaskHistoryCount(filter tasks.TaskHistoryFilter) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskHistoryCount", filter)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskHistoryCount indicates an expected call of GetTaskHistoryCount.
func (mr *MockTaskRepositoryMockRecorder) GetTaskHistoryCount(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskHistoryCount", reflect.TypeOf((*MockTaskRepository)(nil).GetTaskHistoryCount), filter)
}

// GetTasksByPlaybookId mocks base method.
func (m *MockTaskRepository) GetTasksByPlaybookId(playbookId string) []domain.Tasks {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByPlaybookId", playbookId)
	ret0, _ := ret[0].([]domain.Tasks)
	return ret0
}

// GetTasksByPlaybookId indicates an expected call of GetTasksByPlaybookId.
func (mr *MockTaskRepositoryMockRecorder) GetTasksByPlaybookId(playbookId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByPlaybookId", reflect.TypeOf((*MockTaskRepository)(nil).GetTasksByPlaybookId), playbookId)
}

// UpdateTaskHistory mocks base method.
func (m *MockTaskRepository) UpdateTaskHistory(playbookHistoryId, taskId string, taskHistory tasks.UpdateTaskHistoryData) (*domain.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskHistory", playbookHistoryId, taskId, taskHistory)
	ret0, _ := ret[0].(*domain.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskHistory indicates an expected call of UpdateTaskHistory.
func (mr *MockTaskRepositoryMockRecorder) UpdateTaskHistory(playbookHistoryId, taskId, taskHistory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskHistory", reflect.TypeOf((*MockTaskRepository)(nil).UpdateTaskHistory), playbookHistoryId, taskId, taskHistory)
}

// UpdateTaskStatus mocks base method.
func (m *MockTaskRepository) UpdateTaskStatus(playbookHistoryId, taskId, status string) (*domain.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatus", playbookHistoryId, taskId, status)
	ret0, _ := ret[0].(*domain.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskStatus indicates an expected call of UpdateTaskStatus.
func (mr *MockTaskRepositoryMockRecorder) UpdateTaskStatus(playbookHistoryId, taskId, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatus", reflect.TypeOf((*MockTaskRepository)(nil).UpdateTaskStatus), playbookHistoryId, taskId, status)
}

// UpsertTasks mocks base method.
func (m *MockTaskRepository) UpsertTasks(tx *sqlx.Tx, playbookId uuid.UUID, arg2 []domain.Tasks) ([]domain.Tasks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTasks", tx, playbookId, arg2)
	ret0, _ := ret[0].([]domain.Tasks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertTasks indicates an expected call of UpsertTasks.
func (mr *MockTaskRepositoryMockRecorder) UpsertTasks(tx, playbookId, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTasks", reflect.TypeOf((*MockTaskRepository)(nil).UpsertTasks), tx, playbookId, arg2)
}
