// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/workflow_service/internal/workflows/repository.go
//
// Generated by this command:
//
//	mockgen -source=./app/workflow_service/internal/workflows/repository.go -destination=./app/workflow_service/internal/workflows/mocks/repository_mock.go
//

// Package mock_workflows is a generated GoMock package.
package mock_workflows

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	sqlx "github.com/jmoiron/sqlx"
	edges "github.com/yuudev14-workflow/workflow-service/internal/edges"
	workflows "github.com/yuudev14-workflow/workflow-service/internal/workflows"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkflowRepository is a mock of WorkflowRepository interface.
type MockWorkflowRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowRepositoryMockRecorder
	isgomock struct{}
}

// MockWorkflowRepositoryMockRecorder is the mock recorder for MockWorkflowRepository.
type MockWorkflowRepositoryMockRecorder struct {
	mock *MockWorkflowRepository
}

// NewMockWorkflowRepository creates a new mock instance.
func NewMockWorkflowRepository(ctrl *gomock.Controller) *MockWorkflowRepository {
	mock := &MockWorkflowRepository{ctrl: ctrl}
	mock.recorder = &MockWorkflowRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowRepository) EXPECT() *MockWorkflowRepositoryMockRecorder {
	return m.recorder
}

// CreateWorkflow mocks base method.
func (m *MockWorkflowRepository) CreateWorkflow(workflow workflows.WorkflowPayload) (*workflows.Workflows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkflow", workflow)
	ret0, _ := ret[0].(*workflows.Workflows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkflow indicates an expected call of CreateWorkflow.
func (mr *MockWorkflowRepositoryMockRecorder) CreateWorkflow(workflow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkflow", reflect.TypeOf((*MockWorkflowRepository)(nil).CreateWorkflow), workflow)
}

// CreateWorkflowHistory mocks base method.
func (m *MockWorkflowRepository) CreateWorkflowHistory(tx *sqlx.Tx, id string, arg2 []edges.ResponseEdges) (*workflows.WorkflowHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkflowHistory", tx, id, arg2)
	ret0, _ := ret[0].(*workflows.WorkflowHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkflowHistory indicates an expected call of CreateWorkflowHistory.
func (mr *MockWorkflowRepositoryMockRecorder) CreateWorkflowHistory(tx, id, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkflowHistory", reflect.TypeOf((*MockWorkflowRepository)(nil).CreateWorkflowHistory), tx, id, arg2)
}

// GetWorkflowById mocks base method.
func (m *MockWorkflowRepository) GetWorkflowById(id string) (*workflows.Workflows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowById", id)
	ret0, _ := ret[0].(*workflows.Workflows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowById indicates an expected call of GetWorkflowById.
func (mr *MockWorkflowRepositoryMockRecorder) GetWorkflowById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowById", reflect.TypeOf((*MockWorkflowRepository)(nil).GetWorkflowById), id)
}

// GetWorkflowGraphById mocks base method.
func (m *MockWorkflowRepository) GetWorkflowGraphById(id string) (*workflows.WorkflowsGraph, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowGraphById", id)
	ret0, _ := ret[0].(*workflows.WorkflowsGraph)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowGraphById indicates an expected call of GetWorkflowGraphById.
func (mr *MockWorkflowRepositoryMockRecorder) GetWorkflowGraphById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowGraphById", reflect.TypeOf((*MockWorkflowRepository)(nil).GetWorkflowGraphById), id)
}

// GetWorkflowHistory mocks base method.
func (m *MockWorkflowRepository) GetWorkflowHistory(offset, limit int, filter workflows.WorkflowHistoryFilter) ([]workflows.WorkflowHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowHistory", offset, limit, filter)
	ret0, _ := ret[0].([]workflows.WorkflowHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowHistory indicates an expected call of GetWorkflowHistory.
func (mr *MockWorkflowRepositoryMockRecorder) GetWorkflowHistory(offset, limit, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowHistory", reflect.TypeOf((*MockWorkflowRepository)(nil).GetWorkflowHistory), offset, limit, filter)
}

// GetWorkflowHistoryById mocks base method.
func (m *MockWorkflowRepository) GetWorkflowHistoryById(workflowHistoryId uuid.UUID) (*workflows.WorkflowHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowHistoryById", workflowHistoryId)
	ret0, _ := ret[0].(*workflows.WorkflowHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowHistoryById indicates an expected call of GetWorkflowHistoryById.
func (mr *MockWorkflowRepositoryMockRecorder) GetWorkflowHistoryById(workflowHistoryId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowHistoryById", reflect.TypeOf((*MockWorkflowRepository)(nil).GetWorkflowHistoryById), workflowHistoryId)
}

// GetWorkflowHistoryCount mocks base method.
func (m *MockWorkflowRepository) GetWorkflowHistoryCount(filter workflows.WorkflowHistoryFilter) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowHistoryCount", filter)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowHistoryCount indicates an expected call of GetWorkflowHistoryCount.
func (mr *MockWorkflowRepositoryMockRecorder) GetWorkflowHistoryCount(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowHistoryCount", reflect.TypeOf((*MockWorkflowRepository)(nil).GetWorkflowHistoryCount), filter)
}

// GetWorkflowTriggers mocks base method.
func (m *MockWorkflowRepository) GetWorkflowTriggers() ([]workflows.WorkflowTriggers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowTriggers")
	ret0, _ := ret[0].([]workflows.WorkflowTriggers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowTriggers indicates an expected call of GetWorkflowTriggers.
func (mr *MockWorkflowRepositoryMockRecorder) GetWorkflowTriggers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowTriggers", reflect.TypeOf((*MockWorkflowRepository)(nil).GetWorkflowTriggers))
}

// GetWorkflows mocks base method.
func (m *MockWorkflowRepository) GetWorkflows(offset, limit int, filter workflows.WorkflowFilter) ([]workflows.Workflows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflows", offset, limit, filter)
	ret0, _ := ret[0].([]workflows.Workflows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflows indicates an expected call of GetWorkflows.
func (mr *MockWorkflowRepositoryMockRecorder) GetWorkflows(offset, limit, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflows", reflect.TypeOf((*MockWorkflowRepository)(nil).GetWorkflows), offset, limit, filter)
}

// GetWorkflowsCount mocks base method.
func (m *MockWorkflowRepository) GetWorkflowsCount(filter workflows.WorkflowFilter) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowsCount", filter)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowsCount indicates an expected call of GetWorkflowsCount.
func (mr *MockWorkflowRepositoryMockRecorder) GetWorkflowsCount(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowsCount", reflect.TypeOf((*MockWorkflowRepository)(nil).GetWorkflowsCount), filter)
}

// UpdateWorkflow mocks base method.
func (m *MockWorkflowRepository) UpdateWorkflow(id string, workflow workflows.UpdateWorkflowData) (*workflows.Workflows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkflow", id, workflow)
	ret0, _ := ret[0].(*workflows.Workflows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWorkflow indicates an expected call of UpdateWorkflow.
func (mr *MockWorkflowRepositoryMockRecorder) UpdateWorkflow(id, workflow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkflow", reflect.TypeOf((*MockWorkflowRepository)(nil).UpdateWorkflow), id, workflow)
}

// UpdateWorkflowHistory mocks base method.
func (m *MockWorkflowRepository) UpdateWorkflowHistory(workflowHistoryId string, workflowHistory workflows.UpdateWorkflowHistoryData) (*workflows.WorkflowHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkflowHistory", workflowHistoryId, workflowHistory)
	ret0, _ := ret[0].(*workflows.WorkflowHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWorkflowHistory indicates an expected call of UpdateWorkflowHistory.
func (mr *MockWorkflowRepositoryMockRecorder) UpdateWorkflowHistory(workflowHistoryId, workflowHistory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkflowHistory", reflect.TypeOf((*MockWorkflowRepository)(nil).UpdateWorkflowHistory), workflowHistoryId, workflowHistory)
}

// UpdateWorkflowHistoryStatus mocks base method.
func (m *MockWorkflowRepository) UpdateWorkflowHistoryStatus(workflow_history_id, status string) (*workflows.WorkflowHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkflowHistoryStatus", workflow_history_id, status)
	ret0, _ := ret[0].(*workflows.WorkflowHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWorkflowHistoryStatus indicates an expected call of UpdateWorkflowHistoryStatus.
func (mr *MockWorkflowRepositoryMockRecorder) UpdateWorkflowHistoryStatus(workflow_history_id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkflowHistoryStatus", reflect.TypeOf((*MockWorkflowRepository)(nil).UpdateWorkflowHistoryStatus), workflow_history_id, status)
}

// UpdateWorkflowTx mocks base method.
func (m *MockWorkflowRepository) UpdateWorkflowTx(tx *sqlx.Tx, id string, workflow workflows.UpdateWorkflowData) (*workflows.Workflows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkflowTx", tx, id, workflow)
	ret0, _ := ret[0].(*workflows.Workflows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWorkflowTx indicates an expected call of UpdateWorkflowTx.
func (mr *MockWorkflowRepositoryMockRecorder) UpdateWorkflowTx(tx, id, workflow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkflowTx", reflect.TypeOf((*MockWorkflowRepository)(nil).UpdateWorkflowTx), tx, id, workflow)
}
