// Code generated by MockGen. DO NOT EDIT.
// Source: /home/yuudev14/Desktop/projects/workflow/app/workflow_service/internal/workflows/service.go
//
// Generated by this command:
//
//	mockgen -source=/home/yuudev14/Desktop/projects/workflow/app/workflow_service/internal/workflows/service.go -destination=/home/yuudev14/Desktop/projects/workflow/app/workflow_service/internal/workflows/mocks/service_mock.go
//

// Package mock_workflows is a generated GoMock package.
package mock_workflows

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	sqlx "github.com/jmoiron/sqlx"
	edges "github.com/yuudev14-workflow/workflow-service/internal/edges"
	workflows "github.com/yuudev14-workflow/workflow-service/internal/workflows"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkflowService is a mock of WorkflowService interface.
type MockWorkflowService struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowServiceMockRecorder
	isgomock struct{}
}

// MockWorkflowServiceMockRecorder is the mock recorder for MockWorkflowService.
type MockWorkflowServiceMockRecorder struct {
	mock *MockWorkflowService
}

// NewMockWorkflowService creates a new mock instance.
func NewMockWorkflowService(ctrl *gomock.Controller) *MockWorkflowService {
	mock := &MockWorkflowService{ctrl: ctrl}
	mock.recorder = &MockWorkflowServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowService) EXPECT() *MockWorkflowServiceMockRecorder {
	return m.recorder
}

// CreateWorkflow mocks base method.
func (m *MockWorkflowService) CreateWorkflow(workflow workflows.WorkflowPayload) (*workflows.Workflows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkflow", workflow)
	ret0, _ := ret[0].(*workflows.Workflows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkflow indicates an expected call of CreateWorkflow.
func (mr *MockWorkflowServiceMockRecorder) CreateWorkflow(workflow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkflow", reflect.TypeOf((*MockWorkflowService)(nil).CreateWorkflow), workflow)
}

// CreateWorkflowHistory mocks base method.
func (m *MockWorkflowService) CreateWorkflowHistory(tx *sqlx.Tx, id string, arg2 []edges.ResponseEdges) (*workflows.WorkflowHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkflowHistory", tx, id, arg2)
	ret0, _ := ret[0].(*workflows.WorkflowHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkflowHistory indicates an expected call of CreateWorkflowHistory.
func (mr *MockWorkflowServiceMockRecorder) CreateWorkflowHistory(tx, id, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkflowHistory", reflect.TypeOf((*MockWorkflowService)(nil).CreateWorkflowHistory), tx, id, arg2)
}

// GetWorkflowById mocks base method.
func (m *MockWorkflowService) GetWorkflowById(id string) (*workflows.Workflows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowById", id)
	ret0, _ := ret[0].(*workflows.Workflows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowById indicates an expected call of GetWorkflowById.
func (mr *MockWorkflowServiceMockRecorder) GetWorkflowById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowById", reflect.TypeOf((*MockWorkflowService)(nil).GetWorkflowById), id)
}

// GetWorkflowGraphById mocks base method.
func (m *MockWorkflowService) GetWorkflowGraphById(id string) (*workflows.WorkflowsGraph, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowGraphById", id)
	ret0, _ := ret[0].(*workflows.WorkflowsGraph)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowGraphById indicates an expected call of GetWorkflowGraphById.
func (mr *MockWorkflowServiceMockRecorder) GetWorkflowGraphById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowGraphById", reflect.TypeOf((*MockWorkflowService)(nil).GetWorkflowGraphById), id)
}

// GetWorkflowHistory mocks base method.
func (m *MockWorkflowService) GetWorkflowHistory(offset, limit int, filter workflows.WorkflowHistoryFilter) ([]workflows.WorkflowHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowHistory", offset, limit, filter)
	ret0, _ := ret[0].([]workflows.WorkflowHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowHistory indicates an expected call of GetWorkflowHistory.
func (mr *MockWorkflowServiceMockRecorder) GetWorkflowHistory(offset, limit, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowHistory", reflect.TypeOf((*MockWorkflowService)(nil).GetWorkflowHistory), offset, limit, filter)
}

// GetWorkflowHistoryById mocks base method.
func (m *MockWorkflowService) GetWorkflowHistoryById(workflowHistoryId uuid.UUID) (*workflows.WorkflowHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowHistoryById", workflowHistoryId)
	ret0, _ := ret[0].(*workflows.WorkflowHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowHistoryById indicates an expected call of GetWorkflowHistoryById.
func (mr *MockWorkflowServiceMockRecorder) GetWorkflowHistoryById(workflowHistoryId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowHistoryById", reflect.TypeOf((*MockWorkflowService)(nil).GetWorkflowHistoryById), workflowHistoryId)
}

// GetWorkflowHistoryCount mocks base method.
func (m *MockWorkflowService) GetWorkflowHistoryCount(filter workflows.WorkflowHistoryFilter) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowHistoryCount", filter)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowHistoryCount indicates an expected call of GetWorkflowHistoryCount.
func (mr *MockWorkflowServiceMockRecorder) GetWorkflowHistoryCount(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowHistoryCount", reflect.TypeOf((*MockWorkflowService)(nil).GetWorkflowHistoryCount), filter)
}

// GetWorkflowTriggers mocks base method.
func (m *MockWorkflowService) GetWorkflowTriggers() ([]workflows.WorkflowTriggers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowTriggers")
	ret0, _ := ret[0].([]workflows.WorkflowTriggers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowTriggers indicates an expected call of GetWorkflowTriggers.
func (mr *MockWorkflowServiceMockRecorder) GetWorkflowTriggers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowTriggers", reflect.TypeOf((*MockWorkflowService)(nil).GetWorkflowTriggers))
}

// GetWorkflows mocks base method.
func (m *MockWorkflowService) GetWorkflows(offset, limit int, filter workflows.WorkflowFilter) ([]workflows.Workflows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflows", offset, limit, filter)
	ret0, _ := ret[0].([]workflows.Workflows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflows indicates an expected call of GetWorkflows.
func (mr *MockWorkflowServiceMockRecorder) GetWorkflows(offset, limit, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflows", reflect.TypeOf((*MockWorkflowService)(nil).GetWorkflows), offset, limit, filter)
}

// GetWorkflowsCount mocks base method.
func (m *MockWorkflowService) GetWorkflowsCount(filter workflows.WorkflowFilter) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowsCount", filter)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowsCount indicates an expected call of GetWorkflowsCount.
func (mr *MockWorkflowServiceMockRecorder) GetWorkflowsCount(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowsCount", reflect.TypeOf((*MockWorkflowService)(nil).GetWorkflowsCount), filter)
}

// UpdateWorkflow mocks base method.
func (m *MockWorkflowService) UpdateWorkflow(id string, workflow workflows.UpdateWorkflowData) (*workflows.Workflows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkflow", id, workflow)
	ret0, _ := ret[0].(*workflows.Workflows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWorkflow indicates an expected call of UpdateWorkflow.
func (mr *MockWorkflowServiceMockRecorder) UpdateWorkflow(id, workflow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkflow", reflect.TypeOf((*MockWorkflowService)(nil).UpdateWorkflow), id, workflow)
}

// UpdateWorkflowHistory mocks base method.
func (m *MockWorkflowService) UpdateWorkflowHistory(workflowHistoryId string, workflowHistory workflows.UpdateWorkflowHistoryData) (*workflows.WorkflowHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkflowHistory", workflowHistoryId, workflowHistory)
	ret0, _ := ret[0].(*workflows.WorkflowHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWorkflowHistory indicates an expected call of UpdateWorkflowHistory.
func (mr *MockWorkflowServiceMockRecorder) UpdateWorkflowHistory(workflowHistoryId, workflowHistory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkflowHistory", reflect.TypeOf((*MockWorkflowService)(nil).UpdateWorkflowHistory), workflowHistoryId, workflowHistory)
}

// UpdateWorkflowHistoryStatus mocks base method.
func (m *MockWorkflowService) UpdateWorkflowHistoryStatus(workflowHistoryId, status string) (*workflows.WorkflowHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkflowHistoryStatus", workflowHistoryId, status)
	ret0, _ := ret[0].(*workflows.WorkflowHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWorkflowHistoryStatus indicates an expected call of UpdateWorkflowHistoryStatus.
func (mr *MockWorkflowServiceMockRecorder) UpdateWorkflowHistoryStatus(workflowHistoryId, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkflowHistoryStatus", reflect.TypeOf((*MockWorkflowService)(nil).UpdateWorkflowHistoryStatus), workflowHistoryId, status)
}

// UpdateWorkflowTx mocks base method.
func (m *MockWorkflowService) UpdateWorkflowTx(tx *sqlx.Tx, id string, workflow workflows.UpdateWorkflowData) (*workflows.Workflows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkflowTx", tx, id, workflow)
	ret0, _ := ret[0].(*workflows.Workflows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWorkflowTx indicates an expected call of UpdateWorkflowTx.
func (mr *MockWorkflowServiceMockRecorder) UpdateWorkflowTx(tx, id, workflow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkflowTx", reflect.TypeOf((*MockWorkflowService)(nil).UpdateWorkflowTx), tx, id, workflow)
}
