// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/auth (interfaces: AuditLogRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/audit_log_repository_mock.go -package=mocks . AuditLogRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/yuudev14/ytsoar/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditLogRepository is a mock of AuditLogRepository interface.
type MockAuditLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuditLogRepositoryMockRecorder
	isgomock struct{}
}

// MockAuditLogRepositoryMockRecorder is the mock recorder for MockAuditLogRepository.
type MockAuditLogRepositoryMockRecorder struct {
	mock *MockAuditLogRepository
}

// NewMockAuditLogRepository creates a new mock instance.
func NewMockAuditLogRepository(ctrl *gomock.Controller) *MockAuditLogRepository {
	mock := &MockAuditLogRepository{ctrl: ctrl}
	mock.recorder = &MockAuditLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditLogRepository) EXPECT() *MockAuditLogRepositoryMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockAuditLogRepository) Insert(ctx context.Context, entry domain.AuditEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockAuditLogRepositoryMockRecorder) Insert(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockAuditLogRepository)(nil).Insert), ctx, entry)
}
