// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/auth (interfaces: AuthProviderRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/auth_provider_repository_mock.go -package=mocks . AuthProviderRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	uuid "github.com/google/uuid"
	auth "github.com/yuudev14/ytsoar/internal/application/auth"
	domain "github.com/yuudev14/ytsoar/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthProviderRepository is a mock of AuthProviderRepository interface.
type MockAuthProviderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthProviderRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthProviderRepositoryMockRecorder is the mock recorder for MockAuthProviderRepository.
type MockAuthProviderRepositoryMockRecorder struct {
	mock *MockAuthProviderRepository
}

// NewMockAuthProviderRepository creates a new mock instance.
func NewMockAuthProviderRepository(ctrl *gomock.Controller) *MockAuthProviderRepository {
	mock := &MockAuthProviderRepository{ctrl: ctrl}
	mock.recorder = &MockAuthProviderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthProviderRepository) EXPECT() *MockAuthProviderRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuthProviderRepository) Create(ctx context.Context, typ domain.AuthProvider, name string, config json.RawMessage, enabled bool) (auth.AuthProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, typ, name, config, enabled)
	ret0, _ := ret[0].(auth.AuthProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAuthProviderRepositoryMockRecorder) Create(ctx, typ, name, config, enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthProviderRepository)(nil).Create), ctx, typ, name, config, enabled)
}

// GetByID mocks base method.
func (m *MockAuthProviderRepository) GetByID(ctx context.Context, id uuid.UUID) (auth.AuthProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(auth.AuthProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAuthProviderRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAuthProviderRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockAuthProviderRepository) List(ctx context.Context) ([]auth.AuthProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]auth.AuthProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAuthProviderRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAuthProviderRepository)(nil).List), ctx)
}

// ListEnabled mocks base method.
func (m *MockAuthProviderRepository) ListEnabled(ctx context.Context) ([]auth.AuthProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnabled", ctx)
	ret0, _ := ret[0].([]auth.AuthProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnabled indicates an expected call of ListEnabled.
func (mr *MockAuthProviderRepositoryMockRecorder) ListEnabled(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnabled", reflect.TypeOf((*MockAuthProviderRepository)(nil).ListEnabled), ctx)
}

// Update mocks base method.
func (m *MockAuthProviderRepository) Update(ctx context.Context, id uuid.UUID, params auth.UpdateProviderParams) (auth.AuthProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, params)
	ret0, _ := ret[0].(auth.AuthProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAuthProviderRepositoryMockRecorder) Update(ctx, id, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAuthProviderRepository)(nil).Update), ctx, id, params)
}
