// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/auth (interfaces: OIDCClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/oidc_client_mock.go -package=mocks . OIDCClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	auth "github.com/yuudev14/ytsoar/internal/application/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockOIDCClient is a mock of OIDCClient interface.
type MockOIDCClient struct {
	ctrl     *gomock.Controller
	recorder *MockOIDCClientMockRecorder
	isgomock struct{}
}

// MockOIDCClientMockRecorder is the mock recorder for MockOIDCClient.
type MockOIDCClientMockRecorder struct {
	mock *MockOIDCClient
}

// NewMockOIDCClient creates a new mock instance.
func NewMockOIDCClient(ctrl *gomock.Controller) *MockOIDCClient {
	mock := &MockOIDCClient{ctrl: ctrl}
	mock.recorder = &MockOIDCClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOIDCClient) EXPECT() *MockOIDCClientMockRecorder {
	return m.recorder
}

// AuthCodeURL mocks base method.
func (m *MockOIDCClient) AuthCodeURL(ctx context.Context, cfg auth.OIDCConfig, redirectURL, state, codeChallenge string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthCodeURL", ctx, cfg, redirectURL, state, codeChallenge)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthCodeURL indicates an expected call of AuthCodeURL.
func (mr *MockOIDCClientMockRecorder) AuthCodeURL(ctx, cfg, redirectURL, state, codeChallenge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthCodeURL", reflect.TypeOf((*MockOIDCClient)(nil).AuthCodeURL), ctx, cfg, redirectURL, state, codeChallenge)
}

// Exchange mocks base method.
func (m *MockOIDCClient) Exchange(ctx context.Context, cfg auth.OIDCConfig, redirectURL, code, codeVerifier string) (auth.OIDCIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exchange", ctx, cfg, redirectURL, code, codeVerifier)
	ret0, _ := ret[0].(auth.OIDCIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exchange indicates an expected call of Exchange.
func (mr *MockOIDCClientMockRecorder) Exchange(ctx, cfg, redirectURL, code, codeVerifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exchange", reflect.TypeOf((*MockOIDCClient)(nil).Exchange), ctx, cfg, redirectURL, code, codeVerifier)
}
