// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/auth (interfaces: RoleRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/role_repository_mock.go -package=mocks . RoleRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/yuudev14/ytsoar/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleRepository is a mock of RoleRepository interface.
type MockRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRepositoryMockRecorder
	isgomock struct{}
}

// MockRoleRepositoryMockRecorder is the mock recorder for MockRoleRepository.
type MockRoleRepositoryMockRecorder struct {
	mock *MockRoleRepository
}

// NewMockRoleRepository creates a new mock instance.
func NewMockRoleRepository(ctrl *gomock.Controller) *MockRoleRepository {
	mock := &MockRoleRepository{ctrl: ctrl}
	mock.recorder = &MockRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRepository) EXPECT() *MockRoleRepositoryMockRecorder {
	return m.recorder
}

// AssignToUser mocks base method.
func (m *MockRoleRepository) AssignToUser(ctx context.Context, userID, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignToUser", ctx, userID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignToUser indicates an expected call of AssignToUser.
func (mr *MockRoleRepositoryMockRecorder) AssignToUser(ctx, userID, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignToUser", reflect.TypeOf((*MockRoleRepository)(nil).AssignToUser), ctx, userID, roleID)
}

// GetByName mocks base method.
func (m *MockRoleRepository) GetByName(ctx context.Context, name string) (domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockRoleRepositoryMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockRoleRepository)(nil).GetByName), ctx, name)
}

// ListForUser mocks base method.
func (m *MockRoleRepository) ListForUser(ctx context.Context, userID uuid.UUID) ([]domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForUser", ctx, userID)
	ret0, _ := ret[0].([]domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForUser indicates an expected call of ListForUser.
func (mr *MockRoleRepositoryMockRecorder) ListForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForUser", reflect.TypeOf((*MockRoleRepository)(nil).ListForUser), ctx, userID)
}

// ListPermissionsForUser mocks base method.
func (m *MockRoleRepository) ListPermissionsForUser(ctx context.Context, userID uuid.UUID) (domain.PermissionSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPermissionsForUser", ctx, userID)
	ret0, _ := ret[0].(domain.PermissionSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPermissionsForUser indicates an expected call of ListPermissionsForUser.
func (mr *MockRoleRepositoryMockRecorder) ListPermissionsForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPermissionsForUser", reflect.TypeOf((*MockRoleRepository)(nil).ListPermissionsForUser), ctx, userID)
}
