// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/auth (interfaces: TeamRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/team_repository_mock.go -package=mocks . TeamRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	auth "github.com/yuudev14/ytsoar/internal/application/auth"
	domain "github.com/yuudev14/ytsoar/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTeamRepository is a mock of TeamRepository interface.
type MockTeamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepositoryMockRecorder
	isgomock struct{}
}

// MockTeamRepositoryMockRecorder is the mock recorder for MockTeamRepository.
type MockTeamRepositoryMockRecorder struct {
	mock *MockTeamRepository
}

// NewMockTeamRepository creates a new mock instance.
func NewMockTeamRepository(ctrl *gomock.Controller) *MockTeamRepository {
	mock := &MockTeamRepository{ctrl: ctrl}
	mock.recorder = &MockTeamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepository) EXPECT() *MockTeamRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockTeamRepository) Count(ctx context.Context, filter auth.TeamFilter) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filter)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockTeamRepositoryMockRecorder) Count(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockTeamRepository)(nil).Count), ctx, filter)
}

// Create mocks base method.
func (m *MockTeamRepository) Create(ctx context.Context, name string, description *string) (domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name, description)
	ret0, _ := ret[0].(domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTeamRepositoryMockRecorder) Create(ctx, name, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTeamRepository)(nil).Create), ctx, name, description)
}

// Delete mocks base method.
func (m *MockTeamRepository) Delete(ctx context.Context, id uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockTeamRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTeamRepository)(nil).Delete), ctx, id)
}

// GetWithMembers mocks base method.
func (m *MockTeamRepository) GetWithMembers(ctx context.Context, id uuid.UUID) (domain.TeamWithMembers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithMembers", ctx, id)
	ret0, _ := ret[0].(domain.TeamWithMembers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithMembers indicates an expected call of GetWithMembers.
func (mr *MockTeamRepositoryMockRecorder) GetWithMembers(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithMembers", reflect.TypeOf((*MockTeamRepository)(nil).GetWithMembers), ctx, id)
}

// List mocks base method.
func (m *MockTeamRepository) List(ctx context.Context, offset, limit int, filter auth.TeamFilter) ([]domain.TeamWithMembers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit, filter)
	ret0, _ := ret[0].([]domain.TeamWithMembers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTeamRepositoryMockRecorder) List(ctx, offset, limit, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTeamRepository)(nil).List), ctx, offset, limit, filter)
}

// ReplaceMembers mocks base method.
func (m *MockTeamRepository) ReplaceMembers(ctx context.Context, teamID uuid.UUID, userIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceMembers", ctx, teamID, userIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceMembers indicates an expected call of ReplaceMembers.
func (mr *MockTeamRepositoryMockRecorder) ReplaceMembers(ctx, teamID, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceMembers", reflect.TypeOf((*MockTeamRepository)(nil).ReplaceMembers), ctx, teamID, userIDs)
}

// Update mocks base method.
func (m *MockTeamRepository) Update(ctx context.Context, id uuid.UUID, params auth.UpdateTeamParams) (domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, params)
	ret0, _ := ret[0].(domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTeamRepositoryMockRecorder) Update(ctx, id, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTeamRepository)(nil).Update), ctx, id, params)
}
