// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/execution (interfaces: NodeRuntime,RuntimeResolver,StatusPublisher)
//
// Generated by this command:
//
//	mockgen -destination=mocks/execution_mock.go -package=mocks . NodeRuntime,RuntimeResolver,StatusPublisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	execution "github.com/yuudev14/ytsoar/internal/application/execution"
	domain "github.com/yuudev14/ytsoar/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockNodeRuntime is a mock of NodeRuntime interface.
type MockNodeRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockNodeRuntimeMockRecorder
	isgomock struct{}
}

// MockNodeRuntimeMockRecorder is the mock recorder for MockNodeRuntime.
type MockNodeRuntimeMockRecorder struct {
	mock *MockNodeRuntime
}

// NewMockNodeRuntime creates a new mock instance.
func NewMockNodeRuntime(ctrl *gomock.Controller) *MockNodeRuntime {
	mock := &MockNodeRuntime{ctrl: ctrl}
	mock.recorder = &MockNodeRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeRuntime) EXPECT() *MockNodeRuntimeMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockNodeRuntime) Execute(ctx context.Context, req execution.ExecutionRequest) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, req)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockNodeRuntimeMockRecorder) Execute(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockNodeRuntime)(nil).Execute), ctx, req)
}

// MockRuntimeResolver is a mock of RuntimeResolver interface.
type MockRuntimeResolver struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeResolverMockRecorder
	isgomock struct{}
}

// MockRuntimeResolverMockRecorder is the mock recorder for MockRuntimeResolver.
type MockRuntimeResolverMockRecorder struct {
	mock *MockRuntimeResolver
}

// NewMockRuntimeResolver creates a new mock instance.
func NewMockRuntimeResolver(ctrl *gomock.Controller) *MockRuntimeResolver {
	mock := &MockRuntimeResolver{ctrl: ctrl}
	mock.recorder = &MockRuntimeResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntimeResolver) EXPECT() *MockRuntimeResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockRuntimeResolver) Resolve(task domain.Tasks) (execution.NodeRuntime, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", task)
	ret0, _ := ret[0].(execution.NodeRuntime)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockRuntimeResolverMockRecorder) Resolve(task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockRuntimeResolver)(nil).Resolve), task)
}

// MockStatusPublisher is a mock of StatusPublisher interface.
type MockStatusPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockStatusPublisherMockRecorder
	isgomock struct{}
}

// MockStatusPublisherMockRecorder is the mock recorder for MockStatusPublisher.
type MockStatusPublisherMockRecorder struct {
	mock *MockStatusPublisher
}

// NewMockStatusPublisher creates a new mock instance.
func NewMockStatusPublisher(ctrl *gomock.Controller) *MockStatusPublisher {
	mock := &MockStatusPublisher{ctrl: ctrl}
	mock.recorder = &MockStatusPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusPublisher) EXPECT() *MockStatusPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockStatusPublisher) Publish(event string, data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", event, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockStatusPublisherMockRecorder) Publish(event, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockStatusPublisher)(nil).Publish), event, data)
}
