// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/connectors (interfaces: ConnectorService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/service_mock.go -package=mocks . ConnectorService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/yuudev14/ytsoar/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockConnectorService is a mock of ConnectorService interface.
type MockConnectorService struct {
	ctrl     *gomock.Controller
	recorder *MockConnectorServiceMockRecorder
	isgomock struct{}
}

// MockConnectorServiceMockRecorder is the mock recorder for MockConnectorService.
type MockConnectorServiceMockRecorder struct {
	mock *MockConnectorService
}

// NewMockConnectorService creates a new mock instance.
func NewMockConnectorService(ctrl *gomock.Controller) *MockConnectorService {
	mock := &MockConnectorService{ctrl: ctrl}
	mock.recorder = &MockConnectorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectorService) EXPECT() *MockConnectorServiceMockRecorder {
	return m.recorder
}

// DeleteConnector mocks base method.
func (m *MockConnectorService) DeleteConnector(ctx context.Context, connectorID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConnector", ctx, connectorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConnector indicates an expected call of DeleteConnector.
func (mr *MockConnectorServiceMockRecorder) DeleteConnector(ctx, connectorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConnector", reflect.TypeOf((*MockConnectorService)(nil).DeleteConnector), ctx, connectorID)
}

// GetConnector mocks base method.
func (m *MockConnectorService) GetConnector(ctx context.Context, connectorID string) (domain.ConnectorInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnector", ctx, connectorID)
	ret0, _ := ret[0].(domain.ConnectorInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnector indicates an expected call of GetConnector.
func (mr *MockConnectorServiceMockRecorder) GetConnector(ctx, connectorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnector", reflect.TypeOf((*MockConnectorService)(nil).GetConnector), ctx, connectorID)
}

// GetConnectors mocks base method.
func (m *MockConnectorService) GetConnectors(ctx context.Context) ([]domain.ConnectorInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectors", ctx)
	ret0, _ := ret[0].([]domain.ConnectorInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectors indicates an expected call of GetConnectors.
func (mr *MockConnectorServiceMockRecorder) GetConnectors(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectors", reflect.TypeOf((*MockConnectorService)(nil).GetConnectors), ctx)
}

// UploadConnector mocks base method.
func (m *MockConnectorService) UploadConnector(ctx context.Context, zipBytes []byte, uploadedBy string) (domain.ConnectorInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadConnector", ctx, zipBytes, uploadedBy)
	ret0, _ := ret[0].(domain.ConnectorInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadConnector indicates an expected call of UploadConnector.
func (mr *MockConnectorServiceMockRecorder) UploadConnector(ctx, zipBytes, uploadedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadConnector", reflect.TypeOf((*MockConnectorService)(nil).UploadConnector), ctx, zipBytes, uploadedBy)
}
