// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/connectors (interfaces: ConnectorStore,ConnectorWriter,ConnectorRepository,DepsInstaller)
//
// Generated by this command:
//
//	mockgen -destination=mocks/store_mock.go -package=mocks . ConnectorStore,ConnectorWriter,ConnectorRepository,DepsInstaller
//

// Package mocks is a generated GoMock package.
package mocks

import (
	zip "archive/zip"
	context "context"
	reflect "reflect"

	domain "github.com/yuudev14/ytsoar/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockConnectorStore is a mock of ConnectorStore interface.
type MockConnectorStore struct {
	ctrl     *gomock.Controller
	recorder *MockConnectorStoreMockRecorder
	isgomock struct{}
}

// MockConnectorStoreMockRecorder is the mock recorder for MockConnectorStore.
type MockConnectorStoreMockRecorder struct {
	mock *MockConnectorStore
}

// NewMockConnectorStore creates a new mock instance.
func NewMockConnectorStore(ctrl *gomock.Controller) *MockConnectorStore {
	mock := &MockConnectorStore{ctrl: ctrl}
	mock.recorder = &MockConnectorStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectorStore) EXPECT() *MockConnectorStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockConnectorStore) Get(ctx context.Context, connectorID string) (domain.ConnectorInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, connectorID)
	ret0, _ := ret[0].(domain.ConnectorInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockConnectorStoreMockRecorder) Get(ctx, connectorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConnectorStore)(nil).Get), ctx, connectorID)
}

// List mocks base method.
func (m *MockConnectorStore) List(ctx context.Context) ([]domain.ConnectorInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]domain.ConnectorInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockConnectorStoreMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockConnectorStore)(nil).List), ctx)
}

// MockConnectorWriter is a mock of ConnectorWriter interface.
type MockConnectorWriter struct {
	ctrl     *gomock.Controller
	recorder *MockConnectorWriterMockRecorder
	isgomock struct{}
}

// MockConnectorWriterMockRecorder is the mock recorder for MockConnectorWriter.
type MockConnectorWriterMockRecorder struct {
	mock *MockConnectorWriter
}

// NewMockConnectorWriter creates a new mock instance.
func NewMockConnectorWriter(ctrl *gomock.Controller) *MockConnectorWriter {
	mock := &MockConnectorWriter{ctrl: ctrl}
	mock.recorder = &MockConnectorWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectorWriter) EXPECT() *MockConnectorWriterMockRecorder {
	return m.recorder
}

// Extract mocks base method.
func (m *MockConnectorWriter) Extract(ctx context.Context, connectorID string, archive *zip.Reader, prefix string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Extract", ctx, connectorID, archive, prefix)
	ret0, _ := ret[0].(error)
	return ret0
}

// Extract indicates an expected call of Extract.
func (mr *MockConnectorWriterMockRecorder) Extract(ctx, connectorID, archive, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Extract", reflect.TypeOf((*MockConnectorWriter)(nil).Extract), ctx, connectorID, archive, prefix)
}

// Remove mocks base method.
func (m *MockConnectorWriter) Remove(ctx context.Context, connectorID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, connectorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockConnectorWriterMockRecorder) Remove(ctx, connectorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockConnectorWriter)(nil).Remove), ctx, connectorID)
}

// MockConnectorRepository is a mock of ConnectorRepository interface.
type MockConnectorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConnectorRepositoryMockRecorder
	isgomock struct{}
}

// MockConnectorRepositoryMockRecorder is the mock recorder for MockConnectorRepository.
type MockConnectorRepositoryMockRecorder struct {
	mock *MockConnectorRepository
}

// NewMockConnectorRepository creates a new mock instance.
func NewMockConnectorRepository(ctrl *gomock.Controller) *MockConnectorRepository {
	mock := &MockConnectorRepository{ctrl: ctrl}
	mock.recorder = &MockConnectorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectorRepository) EXPECT() *MockConnectorRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockConnectorRepository) Delete(ctx context.Context, connectorID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, connectorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockConnectorRepositoryMockRecorder) Delete(ctx, connectorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockConnectorRepository)(nil).Delete), ctx, connectorID)
}

// Upsert mocks base method.
func (m *MockConnectorRepository) Upsert(ctx context.Context, record domain.ConnectorRecord) (domain.ConnectorRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, record)
	ret0, _ := ret[0].(domain.ConnectorRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockConnectorRepositoryMockRecorder) Upsert(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockConnectorRepository)(nil).Upsert), ctx, record)
}

// MockDepsInstaller is a mock of DepsInstaller interface.
type MockDepsInstaller struct {
	ctrl     *gomock.Controller
	recorder *MockDepsInstallerMockRecorder
	isgomock struct{}
}

// MockDepsInstallerMockRecorder is the mock recorder for MockDepsInstaller.
type MockDepsInstallerMockRecorder struct {
	mock *MockDepsInstaller
}

// NewMockDepsInstaller creates a new mock instance.
func NewMockDepsInstaller(ctrl *gomock.Controller) *MockDepsInstaller {
	mock := &MockDepsInstaller{ctrl: ctrl}
	mock.recorder = &MockDepsInstallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepsInstaller) EXPECT() *MockDepsInstallerMockRecorder {
	return m.recorder
}

// Install mocks base method.
func (m *MockDepsInstaller) Install(ctx context.Context, connectorID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Install", ctx, connectorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Install indicates an expected call of Install.
func (mr *MockDepsInstallerMockRecorder) Install(ctx, connectorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockDepsInstaller)(nil).Install), ctx, connectorID)
}
