// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/connectors (interfaces: ConnectorStore)
//
// Generated by this command:
//
//	mockgen -destination=mocks/store_mock.go -package=mocks . ConnectorStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/yuudev14/ytsoar/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockConnectorStore is a mock of ConnectorStore interface.
type MockConnectorStore struct {
	ctrl     *gomock.Controller
	recorder *MockConnectorStoreMockRecorder
	isgomock struct{}
}

// MockConnectorStoreMockRecorder is the mock recorder for MockConnectorStore.
type MockConnectorStoreMockRecorder struct {
	mock *MockConnectorStore
}

// NewMockConnectorStore creates a new mock instance.
func NewMockConnectorStore(ctrl *gomock.Controller) *MockConnectorStore {
	mock := &MockConnectorStore{ctrl: ctrl}
	mock.recorder = &MockConnectorStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectorStore) EXPECT() *MockConnectorStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockConnectorStore) Get(ctx context.Context, connectorID string) (domain.ConnectorInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, connectorID)
	ret0, _ := ret[0].(domain.ConnectorInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockConnectorStoreMockRecorder) Get(ctx, connectorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConnectorStore)(nil).Get), ctx, connectorID)
}

// List mocks base method.
func (m *MockConnectorStore) List(ctx context.Context) ([]domain.ConnectorInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]domain.ConnectorInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockConnectorStoreMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockConnectorStore)(nil).List), ctx)
}
