// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/adapters/repository (interfaces: QuerierTx)
//
// Generated by this command:
//
//	mockgen -destination=mocks/querier_mock.go -package=mocks . QuerierTx
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	db "github.com/yuudev14/ytsoar/db"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerierTx is a mock of QuerierTx interface.
type MockQuerierTx struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierTxMockRecorder
	isgomock struct{}
}

// MockQuerierTxMockRecorder is the mock recorder for MockQuerierTx.
type MockQuerierTxMockRecorder struct {
	mock *MockQuerierTx
}

// NewMockQuerierTx creates a new mock instance.
func NewMockQuerierTx(ctrl *gomock.Controller) *MockQuerierTx {
	mock := &MockQuerierTx{ctrl: ctrl}
	mock.recorder = &MockQuerierTxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerierTx) EXPECT() *MockQuerierTxMockRecorder {
	return m.recorder
}

// CreatePlaybook mocks base method.
func (m *MockQuerierTx) CreatePlaybook(ctx context.Context, arg db.CreatePlaybookParams) (db.Playbook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlaybook", ctx, arg)
	ret0, _ := ret[0].(db.Playbook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePlaybook indicates an expected call of CreatePlaybook.
func (mr *MockQuerierTxMockRecorder) CreatePlaybook(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlaybook", reflect.TypeOf((*MockQuerierTx)(nil).CreatePlaybook), ctx, arg)
}

// CreatePlaybookHistory mocks base method.
func (m *MockQuerierTx) CreatePlaybookHistory(ctx context.Context, arg db.CreatePlaybookHistoryParams) (db.PlaybookHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlaybookHistory", ctx, arg)
	ret0, _ := ret[0].(db.PlaybookHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePlaybookHistory indicates an expected call of CreatePlaybookHistory.
func (mr *MockQuerierTxMockRecorder) CreatePlaybookHistory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlaybookHistory", reflect.TypeOf((*MockQuerierTx)(nil).CreatePlaybookHistory), ctx, arg)
}

// CreateTaskHistory mocks base method.
func (m *MockQuerierTx) CreateTaskHistory(ctx context.Context, arg db.CreateTaskHistoryParams) (db.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTaskHistory", ctx, arg)
	ret0, _ := ret[0].(db.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTaskHistory indicates an expected call of CreateTaskHistory.
func (mr *MockQuerierTxMockRecorder) CreateTaskHistory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTaskHistory", reflect.TypeOf((*MockQuerierTx)(nil).CreateTaskHistory), ctx, arg)
}

// DeleteAllPlaybookEdges mocks base method.
func (m *MockQuerierTx) DeleteAllPlaybookEdges(ctx context.Context, playbookID pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllPlaybookEdges", ctx, playbookID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllPlaybookEdges indicates an expected call of DeleteAllPlaybookEdges.
func (mr *MockQuerierTxMockRecorder) DeleteAllPlaybookEdges(ctx, playbookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllPlaybookEdges", reflect.TypeOf((*MockQuerierTx)(nil).DeleteAllPlaybookEdges), ctx, playbookID)
}

// DeleteEdges mocks base method.
func (m *MockQuerierTx) DeleteEdges(ctx context.Context, ids []pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEdges", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEdges indicates an expected call of DeleteEdges.
func (mr *MockQuerierTxMockRecorder) DeleteEdges(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEdges", reflect.TypeOf((*MockQuerierTx)(nil).DeleteEdges), ctx, ids)
}

// DeleteTasks mocks base method.
func (m *MockQuerierTx) DeleteTasks(ctx context.Context, ids []pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTasks", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTasks indicates an expected call of DeleteTasks.
func (mr *MockQuerierTxMockRecorder) DeleteTasks(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTasks", reflect.TypeOf((*MockQuerierTx)(nil).DeleteTasks), ctx, ids)
}

// GetEdgesByPlaybookId mocks base method.
func (m *MockQuerierTx) GetEdgesByPlaybookId(ctx context.Context, playbookID pgtype.UUID) ([]db.GetEdgesByPlaybookIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEdgesByPlaybookId", ctx, playbookID)
	ret0, _ := ret[0].([]db.GetEdgesByPlaybookIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEdgesByPlaybookId indicates an expected call of GetEdgesByPlaybookId.
func (mr *MockQuerierTxMockRecorder) GetEdgesByPlaybookId(ctx, playbookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEdgesByPlaybookId", reflect.TypeOf((*MockQuerierTx)(nil).GetEdgesByPlaybookId), ctx, playbookID)
}

// GetPlaybookById mocks base method.
func (m *MockQuerierTx) GetPlaybookById(ctx context.Context, id pgtype.UUID) (db.Playbook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookById", ctx, id)
	ret0, _ := ret[0].(db.Playbook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookById indicates an expected call of GetPlaybookById.
func (mr *MockQuerierTxMockRecorder) GetPlaybookById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookById", reflect.TypeOf((*MockQuerierTx)(nil).GetPlaybookById), ctx, id)
}

// GetPlaybookGraphById mocks base method.
func (m *MockQuerierTx) GetPlaybookGraphById(ctx context.Context, id pgtype.UUID) (db.GetPlaybookGraphByIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookGraphById", ctx, id)
	ret0, _ := ret[0].(db.GetPlaybookGraphByIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookGraphById indicates an expected call of GetPlaybookGraphById.
func (mr *MockQuerierTxMockRecorder) GetPlaybookGraphById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookGraphById", reflect.TypeOf((*MockQuerierTx)(nil).GetPlaybookGraphById), ctx, id)
}

// GetPlaybookHistoryById mocks base method.
func (m *MockQuerierTx) GetPlaybookHistoryById(ctx context.Context, id pgtype.UUID) (db.GetPlaybookHistoryByIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookHistoryById", ctx, id)
	ret0, _ := ret[0].(db.GetPlaybookHistoryByIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookHistoryById indicates an expected call of GetPlaybookHistoryById.
func (mr *MockQuerierTxMockRecorder) GetPlaybookHistoryById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookHistoryById", reflect.TypeOf((*MockQuerierTx)(nil).GetPlaybookHistoryById), ctx, id)
}

// GetPlaybookTriggers mocks base method.
func (m *MockQuerierTx) GetPlaybookTriggers(ctx context.Context) ([]db.PlaybookTrigger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookTriggers", ctx)
	ret0, _ := ret[0].([]db.PlaybookTrigger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookTriggers indicates an expected call of GetPlaybookTriggers.
func (mr *MockQuerierTxMockRecorder) GetPlaybookTriggers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookTriggers", reflect.TypeOf((*MockQuerierTx)(nil).GetPlaybookTriggers), ctx)
}

// GetTaskHistoryByPlaybookHistoryId mocks base method.
func (m *MockQuerierTx) GetTaskHistoryByPlaybookHistoryId(ctx context.Context, playbookHistoryID pgtype.UUID) ([]db.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskHistoryByPlaybookHistoryId", ctx, playbookHistoryID)
	ret0, _ := ret[0].([]db.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskHistoryByPlaybookHistoryId indicates an expected call of GetTaskHistoryByPlaybookHistoryId.
func (mr *MockQuerierTxMockRecorder) GetTaskHistoryByPlaybookHistoryId(ctx, playbookHistoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskHistoryByPlaybookHistoryId", reflect.TypeOf((*MockQuerierTx)(nil).GetTaskHistoryByPlaybookHistoryId), ctx, playbookHistoryID)
}

// GetTasksByPlaybookId mocks base method.
func (m *MockQuerierTx) GetTasksByPlaybookId(ctx context.Context, playbookID pgtype.UUID) ([]db.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByPlaybookId", ctx, playbookID)
	ret0, _ := ret[0].([]db.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByPlaybookId indicates an expected call of GetTasksByPlaybookId.
func (mr *MockQuerierTxMockRecorder) GetTasksByPlaybookId(ctx, playbookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByPlaybookId", reflect.TypeOf((*MockQuerierTx)(nil).GetTasksByPlaybookId), ctx, playbookID)
}

// UpdatePlaybook mocks base method.
func (m *MockQuerierTx) UpdatePlaybook(ctx context.Context, arg db.UpdatePlaybookParams) (db.Playbook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaybook", ctx, arg)
	ret0, _ := ret[0].(db.Playbook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlaybook indicates an expected call of UpdatePlaybook.
func (mr *MockQuerierTxMockRecorder) UpdatePlaybook(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaybook", reflect.TypeOf((*MockQuerierTx)(nil).UpdatePlaybook), ctx, arg)
}

// UpdatePlaybookHistory mocks base method.
func (m *MockQuerierTx) UpdatePlaybookHistory(ctx context.Context, arg db.UpdatePlaybookHistoryParams) (db.PlaybookHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaybookHistory", ctx, arg)
	ret0, _ := ret[0].(db.PlaybookHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlaybookHistory indicates an expected call of UpdatePlaybookHistory.
func (mr *MockQuerierTxMockRecorder) UpdatePlaybookHistory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaybookHistory", reflect.TypeOf((*MockQuerierTx)(nil).UpdatePlaybookHistory), ctx, arg)
}

// UpdatePlaybookHistoryStatus mocks base method.
func (m *MockQuerierTx) UpdatePlaybookHistoryStatus(ctx context.Context, arg db.UpdatePlaybookHistoryStatusParams) (db.PlaybookHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaybookHistoryStatus", ctx, arg)
	ret0, _ := ret[0].(db.PlaybookHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlaybookHistoryStatus indicates an expected call of UpdatePlaybookHistoryStatus.
func (mr *MockQuerierTxMockRecorder) UpdatePlaybookHistoryStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaybookHistoryStatus", reflect.TypeOf((*MockQuerierTx)(nil).UpdatePlaybookHistoryStatus), ctx, arg)
}

// UpdateTaskHistory mocks base method.
func (m *MockQuerierTx) UpdateTaskHistory(ctx context.Context, arg db.UpdateTaskHistoryParams) (db.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskHistory", ctx, arg)
	ret0, _ := ret[0].(db.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskHistory indicates an expected call of UpdateTaskHistory.
func (mr *MockQuerierTxMockRecorder) UpdateTaskHistory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskHistory", reflect.TypeOf((*MockQuerierTx)(nil).UpdateTaskHistory), ctx, arg)
}

// UpdateTaskStatus mocks base method.
func (m *MockQuerierTx) UpdateTaskStatus(ctx context.Context, arg db.UpdateTaskStatusParams) (db.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatus", ctx, arg)
	ret0, _ := ret[0].(db.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskStatus indicates an expected call of UpdateTaskStatus.
func (mr *MockQuerierTxMockRecorder) UpdateTaskStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatus", reflect.TypeOf((*MockQuerierTx)(nil).UpdateTaskStatus), ctx, arg)
}

// UpsertEdge mocks base method.
func (m *MockQuerierTx) UpsertEdge(ctx context.Context, arg db.UpsertEdgeParams) (db.Edge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertEdge", ctx, arg)
	ret0, _ := ret[0].(db.Edge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertEdge indicates an expected call of UpsertEdge.
func (mr *MockQuerierTxMockRecorder) UpsertEdge(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertEdge", reflect.TypeOf((*MockQuerierTx)(nil).UpsertEdge), ctx, arg)
}

// UpsertTask mocks base method.
func (m *MockQuerierTx) UpsertTask(ctx context.Context, arg db.UpsertTaskParams) (db.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTask", ctx, arg)
	ret0, _ := ret[0].(db.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertTask indicates an expected call of UpsertTask.
func (mr *MockQuerierTxMockRecorder) UpsertTask(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTask", reflect.TypeOf((*MockQuerierTx)(nil).UpsertTask), ctx, arg)
}

// WithTx mocks base method.
func (m *MockQuerierTx) WithTx(tx pgx.Tx) *db.Queries {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(*db.Queries)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockQuerierTxMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockQuerierTx)(nil).WithTx), tx)
}
