// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAlertNote = `-- name: DeleteAlertNote :execrows
DELETE FROM alert_notes WHERE id = $1
`

func (q *Queries) DeleteAlertNote(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAlertNote, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAlertById = `-- name: GetAlertById :one
SELECT id, title, severity, status, source_kind, reporter, assignee_id, team_id, payload, tags, triage, closure_note, fingerprint, dedup_count, last_seen, triaged_at, sla_deadline, sla_breached_at, sla_state, created_at, updated_at FROM alerts WHERE id = $1
`

func (q *Queries) GetAlertById(ctx context.Context, id pgtype.UUID) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlertById, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Severity,
		&i.Status,
		&i.SourceKind,
		&i.Reporter,
		&i.AssigneeID,
		&i.TeamID,
		&i.Payload,
		&i.Tags,
		&i.Triage,
		&i.ClosureNote,
		&i.Fingerprint,
		&i.DedupCount,
		&i.LastSeen,
		&i.TriagedAt,
		&i.SlaDeadline,
		&i.SlaBreachedAt,
		&i.SlaState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlertNoteById = `-- name: GetAlertNoteById :one
SELECT id, alert_id, author_id, body, created_at, updated_at FROM alert_notes WHERE id = $1
`

func (q *Queries) GetAlertNoteById(ctx context.Context, id pgtype.UUID) (AlertNote, error) {
	row := q.db.QueryRow(ctx, getAlertNoteById, id)
	var i AlertNote
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAlertEvent = `-- name: InsertAlertEvent :one
INSERT INTO alert_events (alert_id, type, actor_id, body)
VALUES ($1, $2, $3, $4)
RETURNING id, alert_id, type, actor_id, body, created_at
`

type InsertAlertEventParams struct {
	AlertID pgtype.UUID     `json:"alert_id"`
	Type    EventType       `json:"type"`
	ActorID pgtype.UUID     `json:"actor_id"`
	Body    json.RawMessage `json:"body"`
}

func (q *Queries) InsertAlertEvent(ctx context.Context, arg InsertAlertEventParams) (AlertEvent, error) {
	row := q.db.QueryRow(ctx, insertAlertEvent,
		arg.AlertID,
		arg.Type,
		arg.ActorID,
		arg.Body,
	)
	var i AlertEvent
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.Type,
		&i.ActorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const insertAlertNote = `-- name: InsertAlertNote :one
INSERT INTO alert_notes (alert_id, author_id, body)
VALUES ($1, $2, $3)
RETURNING id, alert_id, author_id, body, created_at, updated_at
`

type InsertAlertNoteParams struct {
	AlertID  pgtype.UUID `json:"alert_id"`
	AuthorID pgtype.UUID `json:"author_id"`
	Body     string      `json:"body"`
}

func (q *Queries) InsertAlertNote(ctx context.Context, arg InsertAlertNoteParams) (AlertNote, error) {
	row := q.db.QueryRow(ctx, insertAlertNote, arg.AlertID, arg.AuthorID, arg.Body)
	var i AlertNote
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlertEvents = `-- name: ListAlertEvents :many
SELECT e.id, e.alert_id, e.type, e.actor_id, e.body, e.created_at, u.username AS actor_username
FROM alert_events e
LEFT JOIN users u ON u.id = e.actor_id
WHERE e.alert_id = $1
ORDER BY e.created_at, e.id
`

type ListAlertEventsRow struct {
	ID            pgtype.UUID      `json:"id"`
	AlertID       pgtype.UUID      `json:"alert_id"`
	Type          EventType        `json:"type"`
	ActorID       pgtype.UUID      `json:"actor_id"`
	Body          json.RawMessage  `json:"body"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	ActorUsername pgtype.Text      `json:"actor_username"`
}

func (q *Queries) ListAlertEvents(ctx context.Context, alertID pgtype.UUID) ([]ListAlertEventsRow, error) {
	rows, err := q.db.Query(ctx, listAlertEvents, alertID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertEventsRow
	for rows.Next() {
		var i ListAlertEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.AlertID,
			&i.Type,
			&i.ActorID,
			&i.Body,
			&i.CreatedAt,
			&i.ActorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertNotes = `-- name: ListAlertNotes :many
SELECT n.id, n.alert_id, n.author_id, n.body, n.created_at, n.updated_at, u.username AS author_username
FROM alert_notes n
LEFT JOIN users u ON u.id = n.author_id
WHERE n.alert_id = $1
ORDER BY n.created_at, n.id
`

type ListAlertNotesRow struct {
	ID             pgtype.UUID      `json:"id"`
	AlertID        pgtype.UUID      `json:"alert_id"`
	AuthorID       pgtype.UUID      `json:"author_id"`
	Body           string           `json:"body"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	AuthorUsername pgtype.Text      `json:"author_username"`
}

func (q *Queries) ListAlertNotes(ctx context.Context, alertID pgtype.UUID) ([]ListAlertNotesRow, error) {
	rows, err := q.db.Query(ctx, listAlertNotes, alertID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertNotesRow
	for rows.Next() {
		var i ListAlertNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.AlertID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlert = `-- name: UpdateAlert :one
UPDATE alerts
SET
    severity = CASE
        WHEN $1::boolean THEN $2::alert_severity
        ELSE severity
    END,
    assignee_id = CASE
        WHEN $3::boolean THEN $4::uuid
        ELSE assignee_id
    END,
    team_id = CASE
        WHEN $5::boolean THEN $6::uuid
        ELSE team_id
    END,
    tags = CASE
        WHEN $7::boolean THEN COALESCE($8::text[], '{}')
        ELSE tags
    END,
    updated_at = NOW()
WHERE id = $9
RETURNING id, title, severity, status, source_kind, reporter, assignee_id, team_id, payload, tags, triage, closure_note, fingerprint, dedup_count, last_seen, triaged_at, sla_deadline, sla_breached_at, sla_state, created_at, updated_at
`

type UpdateAlertParams struct {
	SeveritySet   bool              `json:"severity_set"`
	Severity      NullAlertSeverity `json:"severity"`
	AssigneeIDSet bool              `json:"assignee_id_set"`
	AssigneeID    pgtype.UUID       `json:"assignee_id"`
	TeamIDSet     bool              `json:"team_id_set"`
	TeamID        pgtype.UUID       `json:"team_id"`
	TagsSet       bool              `json:"tags_set"`
	Tags          []string          `json:"tags"`
	ID            pgtype.UUID       `json:"id"`
}

func (q *Queries) UpdateAlert(ctx context.Context, arg UpdateAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, updateAlert,
		arg.SeveritySet,
		arg.Severity,
		arg.AssigneeIDSet,
		arg.AssigneeID,
		arg.TeamIDSet,
		arg.TeamID,
		arg.TagsSet,
		arg.Tags,
		arg.ID,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Severity,
		&i.Status,
		&i.SourceKind,
		&i.Reporter,
		&i.AssigneeID,
		&i.TeamID,
		&i.Payload,
		&i.Tags,
		&i.Triage,
		&i.ClosureNote,
		&i.Fingerprint,
		&i.DedupCount,
		&i.LastSeen,
		&i.TriagedAt,
		&i.SlaDeadline,
		&i.SlaBreachedAt,
		&i.SlaState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAlertNote = `-- name: UpdateAlertNote :one
UPDATE alert_notes
SET body = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, alert_id, author_id, body, created_at, updated_at
`

type UpdateAlertNoteParams struct {
	Body string      `json:"body"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAlertNote(ctx context.Context, arg UpdateAlertNoteParams) (AlertNote, error) {
	row := q.db.QueryRow(ctx, updateAlertNote, arg.Body, arg.ID)
	var i AlertNote
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAlertStatus = `-- name: UpdateAlertStatus :one
UPDATE alerts
SET
    status = $1,
    triaged_at = CASE
        WHEN triaged_at IS NULL AND status = 'new' AND $1::alert_status <> 'new'
        THEN NOW()
        ELSE triaged_at
    END,
    closure_note = CASE
        WHEN $1::alert_status IN ('new', 'investigating') THEN NULL
        ELSE COALESCE($2::text, closure_note)
    END,
    updated_at = NOW()
WHERE id = $3
RETURNING id, title, severity, status, source_kind, reporter, assignee_id, team_id, payload, tags, triage, closure_note, fingerprint, dedup_count, last_seen, triaged_at, sla_deadline, sla_breached_at, sla_state, created_at, updated_at
`

type UpdateAlertStatusParams struct {
	Status      AlertStatus `json:"status"`
	ClosureNote pgtype.Text `json:"closure_note"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAlertStatus(ctx context.Context, arg UpdateAlertStatusParams) (Alert, error) {
	row := q.db.QueryRow(ctx, updateAlertStatus, arg.Status, arg.ClosureNote, arg.ID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Severity,
		&i.Status,
		&i.SourceKind,
		&i.Reporter,
		&i.AssigneeID,
		&i.TeamID,
		&i.Payload,
		&i.Tags,
		&i.Triage,
		&i.ClosureNote,
		&i.Fingerprint,
		&i.DedupCount,
		&i.LastSeen,
		&i.TriagedAt,
		&i.SlaDeadline,
		&i.SlaBreachedAt,
		&i.SlaState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAlert = `-- name: UpsertAlert :one
INSERT INTO alerts (
    title, severity, source_kind, reporter, assignee_id, team_id,
    payload, tags, fingerprint, created_at, last_seen
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    COALESCE($10::timestamp, NOW()),
    COALESCE($10::timestamp, NOW())
)
ON CONFLICT (fingerprint) WHERE status IN ('new', 'investigating')
DO UPDATE SET
    dedup_count = alerts.dedup_count + 1,
    last_seen = NOW(),
    updated_at = NOW()
RETURNING id, title, severity, status, source_kind, reporter, assignee_id, team_id, payload, tags, triage, closure_note, fingerprint, dedup_count, last_seen, triaged_at, sla_deadline, sla_breached_at, sla_state, created_at, updated_at, (xmax = 0) AS inserted
`

type UpsertAlertParams struct {
	Title       string           `json:"title"`
	Severity    AlertSeverity    `json:"severity"`
	SourceKind  SourceKind       `json:"source_kind"`
	Reporter    pgtype.Text      `json:"reporter"`
	AssigneeID  pgtype.UUID      `json:"assignee_id"`
	TeamID      pgtype.UUID      `json:"team_id"`
	Payload     json.RawMessage  `json:"payload"`
	Tags        []string         `json:"tags"`
	Fingerprint string           `json:"fingerprint"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type UpsertAlertRow struct {
	ID            pgtype.UUID      `json:"id"`
	Title         string           `json:"title"`
	Severity      AlertSeverity    `json:"severity"`
	Status        AlertStatus      `json:"status"`
	SourceKind    SourceKind       `json:"source_kind"`
	Reporter      pgtype.Text      `json:"reporter"`
	AssigneeID    pgtype.UUID      `json:"assignee_id"`
	TeamID        pgtype.UUID      `json:"team_id"`
	Payload       json.RawMessage  `json:"payload"`
	Tags          []string         `json:"tags"`
	Triage        []byte           `json:"triage"`
	ClosureNote   pgtype.Text      `json:"closure_note"`
	Fingerprint   string           `json:"fingerprint"`
	DedupCount    int32            `json:"dedup_count"`
	LastSeen      pgtype.Timestamp `json:"last_seen"`
	TriagedAt     pgtype.Timestamp `json:"triaged_at"`
	SlaDeadline   pgtype.Timestamp `json:"sla_deadline"`
	SlaBreachedAt pgtype.Timestamp `json:"sla_breached_at"`
	SlaState      SlaState         `json:"sla_state"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	Inserted      bool             `json:"inserted"`
}

// Dedup lives in the unique partial index alerts_open_fingerprint_idx, so the
// ON CONFLICT predicate must repeat that index's WHERE verbatim to target it.
// xmax is 0 only on a freshly inserted row, which is how the caller tells a new
// alert from a deduped one without a second query.
func (q *Queries) UpsertAlert(ctx context.Context, arg UpsertAlertParams) (UpsertAlertRow, error) {
	row := q.db.QueryRow(ctx, upsertAlert,
		arg.Title,
		arg.Severity,
		arg.SourceKind,
		arg.Reporter,
		arg.AssigneeID,
		arg.TeamID,
		arg.Payload,
		arg.Tags,
		arg.Fingerprint,
		arg.CreatedAt,
	)
	var i UpsertAlertRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Severity,
		&i.Status,
		&i.SourceKind,
		&i.Reporter,
		&i.AssigneeID,
		&i.TeamID,
		&i.Payload,
		&i.Tags,
		&i.Triage,
		&i.ClosureNote,
		&i.Fingerprint,
		&i.DedupCount,
		&i.LastSeen,
		&i.TriagedAt,
		&i.SlaDeadline,
		&i.SlaBreachedAt,
		&i.SlaState,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Inserted,
	)
	return i, err
}
