// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_logs (actor_id, module, action, entity_id, detail)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, actor_id, module, action, entity_id, detail, created_at
`

type InsertAuditLogParams struct {
	ActorID  pgtype.UUID `json:"actor_id"`
	Module   string      `json:"module"`
	Action   string      `json:"action"`
	EntityID pgtype.Text `json:"entity_id"`
	Detail   []byte      `json:"detail"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.ActorID,
		arg.Module,
		arg.Action,
		arg.EntityID,
		arg.Detail,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Module,
		&i.Action,
		&i.EntityID,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}
