// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_providers.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthProvider = `-- name: CreateAuthProvider :one
INSERT INTO auth_providers (type, name, config, enabled)
VALUES ($1, $2, $3, $4)
RETURNING id, type, name, config, enabled, created_at, updated_at
`

type CreateAuthProviderParams struct {
	Type    AuthProviderType `json:"type"`
	Name    string           `json:"name"`
	Config  json.RawMessage  `json:"config"`
	Enabled bool             `json:"enabled"`
}

func (q *Queries) CreateAuthProvider(ctx context.Context, arg CreateAuthProviderParams) (AuthProvider, error) {
	row := q.db.QueryRow(ctx, createAuthProvider,
		arg.Type,
		arg.Name,
		arg.Config,
		arg.Enabled,
	)
	var i AuthProvider
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthProviderByID = `-- name: GetAuthProviderByID :one
SELECT id, type, name, config, enabled, created_at, updated_at FROM auth_providers WHERE id = $1
`

func (q *Queries) GetAuthProviderByID(ctx context.Context, id pgtype.UUID) (AuthProvider, error) {
	row := q.db.QueryRow(ctx, getAuthProviderByID, id)
	var i AuthProvider
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthProviders = `-- name: ListAuthProviders :many
SELECT id, type, name, config, enabled, created_at, updated_at FROM auth_providers ORDER BY name
`

func (q *Queries) ListAuthProviders(ctx context.Context) ([]AuthProvider, error) {
	rows, err := q.db.Query(ctx, listAuthProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthProvider
	for rows.Next() {
		var i AuthProvider
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAuthProviders = `-- name: ListEnabledAuthProviders :many
SELECT id, type, name, config, enabled, created_at, updated_at FROM auth_providers WHERE enabled = TRUE ORDER BY name
`

func (q *Queries) ListEnabledAuthProviders(ctx context.Context) ([]AuthProvider, error) {
	rows, err := q.db.Query(ctx, listEnabledAuthProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthProvider
	for rows.Next() {
		var i AuthProvider
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthProvider = `-- name: UpdateAuthProvider :one
UPDATE auth_providers
SET
    name = CASE WHEN $1::bool THEN $2::text ELSE name END,
    config = CASE WHEN $3::bool THEN $4::jsonb ELSE config END,
    enabled = CASE WHEN $5::bool THEN $6::bool ELSE enabled END,
    updated_at = NOW()
WHERE id = $7
RETURNING id, type, name, config, enabled, created_at, updated_at
`

type UpdateAuthProviderParams struct {
	NameSet    bool        `json:"name_set"`
	Name       pgtype.Text `json:"name"`
	ConfigSet  bool        `json:"config_set"`
	Config     []byte      `json:"config"`
	EnabledSet bool        `json:"enabled_set"`
	Enabled    pgtype.Bool `json:"enabled"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAuthProvider(ctx context.Context, arg UpdateAuthProviderParams) (AuthProvider, error) {
	row := q.db.QueryRow(ctx, updateAuthProvider,
		arg.NameSet,
		arg.Name,
		arg.ConfigSet,
		arg.Config,
		arg.EnabledSet,
		arg.Enabled,
		arg.ID,
	)
	var i AuthProvider
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
