// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connectors.sql

package db

import (
	"context"
)

const deleteConnectorRecord = `-- name: DeleteConnectorRecord :execrows
DELETE FROM connectors WHERE id = $1
`

func (q *Queries) DeleteConnectorRecord(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnectorRecord, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConnectorRecord = `-- name: GetConnectorRecord :one
SELECT id, name, runtime, version, checksum, uploaded_by, enabled, created_at, updated_at FROM connectors WHERE id = $1
`

func (q *Queries) GetConnectorRecord(ctx context.Context, id string) (Connector, error) {
	row := q.db.QueryRow(ctx, getConnectorRecord, id)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Runtime,
		&i.Version,
		&i.Checksum,
		&i.UploadedBy,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConnector = `-- name: UpsertConnector :one
INSERT INTO connectors (id, name, runtime, version, checksum, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    runtime = EXCLUDED.runtime,
    version = EXCLUDED.version,
    checksum = EXCLUDED.checksum,
    uploaded_by = EXCLUDED.uploaded_by,
    updated_at = now()
RETURNING id, name, runtime, version, checksum, uploaded_by, enabled, created_at, updated_at
`

type UpsertConnectorParams struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Runtime    string `json:"runtime"`
	Version    string `json:"version"`
	Checksum   string `json:"checksum"`
	UploadedBy string `json:"uploaded_by"`
}

func (q *Queries) UpsertConnector(ctx context.Context, arg UpsertConnectorParams) (Connector, error) {
	row := q.db.QueryRow(ctx, upsertConnector,
		arg.ID,
		arg.Name,
		arg.Runtime,
		arg.Version,
		arg.Checksum,
		arg.UploadedBy,
	)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Runtime,
		&i.Version,
		&i.Checksum,
		&i.UploadedBy,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
