// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: edges.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllPlaybookEdges = `-- name: DeleteAllPlaybookEdges :exec
DELETE FROM edges
WHERE destination_id IN (SELECT id FROM tasks WHERE tasks.playbook_id = $1)
   OR source_id IN (SELECT id FROM tasks WHERE tasks.playbook_id = $1)
`

func (q *Queries) DeleteAllPlaybookEdges(ctx context.Context, playbookID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllPlaybookEdges, playbookID)
	return err
}

const deleteEdges = `-- name: DeleteEdges :exec
DELETE FROM edges WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteEdges(ctx context.Context, ids []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEdges, ids)
	return err
}

const getEdgesByPlaybookId = `-- name: GetEdgesByPlaybookId :many
SELECT e.id, e.destination_id, e.source_id, e.playbook_id, e.source_handle, e.destination_handle, t1.name AS source_task_name, t2.name AS destination_task_name
FROM edges e
JOIN tasks t1 ON e.source_id = t1.id
JOIN tasks t2 ON e.destination_id = t2.id
WHERE t1.playbook_id = $1
`

type GetEdgesByPlaybookIdRow struct {
	ID                  pgtype.UUID `json:"id"`
	DestinationID       pgtype.UUID `json:"destination_id"`
	SourceID            pgtype.UUID `json:"source_id"`
	PlaybookID          pgtype.UUID `json:"playbook_id"`
	SourceHandle        pgtype.Text `json:"source_handle"`
	DestinationHandle   pgtype.Text `json:"destination_handle"`
	SourceTaskName      pgtype.Text `json:"source_task_name"`
	DestinationTaskName pgtype.Text `json:"destination_task_name"`
}

func (q *Queries) GetEdgesByPlaybookId(ctx context.Context, playbookID pgtype.UUID) ([]GetEdgesByPlaybookIdRow, error) {
	rows, err := q.db.Query(ctx, getEdgesByPlaybookId, playbookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEdgesByPlaybookIdRow
	for rows.Next() {
		var i GetEdgesByPlaybookIdRow
		if err := rows.Scan(
			&i.ID,
			&i.DestinationID,
			&i.SourceID,
			&i.PlaybookID,
			&i.SourceHandle,
			&i.DestinationHandle,
			&i.SourceTaskName,
			&i.DestinationTaskName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEdge = `-- name: UpsertEdge :one
INSERT INTO edges (destination_id, source_id, playbook_id, source_handle, destination_handle)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (destination_id, source_id) DO UPDATE
SET source_handle = EXCLUDED.source_handle,
    destination_handle = EXCLUDED.destination_handle
RETURNING id, destination_id, source_id, playbook_id, source_handle, destination_handle
`

type UpsertEdgeParams struct {
	DestinationID     pgtype.UUID `json:"destination_id"`
	SourceID          pgtype.UUID `json:"source_id"`
	PlaybookID        pgtype.UUID `json:"playbook_id"`
	SourceHandle      pgtype.Text `json:"source_handle"`
	DestinationHandle pgtype.Text `json:"destination_handle"`
}

func (q *Queries) UpsertEdge(ctx context.Context, arg UpsertEdgeParams) (Edge, error) {
	row := q.db.QueryRow(ctx, upsertEdge,
		arg.DestinationID,
		arg.SourceID,
		arg.PlaybookID,
		arg.SourceHandle,
		arg.DestinationHandle,
	)
	var i Edge
	err := row.Scan(
		&i.ID,
		&i.DestinationID,
		&i.SourceID,
		&i.PlaybookID,
		&i.SourceHandle,
		&i.DestinationHandle,
	)
	return i, err
}
