// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (title, severity, status, assignee_id, team_id, tags)
VALUES (
    $1,
    $2,
    COALESCE($3::incident_status, 'open'),
    $4,
    $5,
    COALESCE($6::text[], '{}')
)
RETURNING id, title, severity, status, assignee_id, team_id, tags, resolved_at, sla_deadline, sla_breached_at, sla_state, created_at, updated_at
`

type CreateIncidentParams struct {
	Title      string             `json:"title"`
	Severity   AlertSeverity      `json:"severity"`
	Status     NullIncidentStatus `json:"status"`
	AssigneeID pgtype.UUID        `json:"assignee_id"`
	TeamID     pgtype.UUID        `json:"team_id"`
	Tags       []string           `json:"tags"`
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, createIncident,
		arg.Title,
		arg.Severity,
		arg.Status,
		arg.AssigneeID,
		arg.TeamID,
		arg.Tags,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Severity,
		&i.Status,
		&i.AssigneeID,
		&i.TeamID,
		&i.Tags,
		&i.ResolvedAt,
		&i.SlaDeadline,
		&i.SlaBreachedAt,
		&i.SlaState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIncidentAlert = `-- name: DeleteIncidentAlert :execrows
DELETE FROM incident_alerts WHERE incident_id = $1 AND alert_id = $2
`

type DeleteIncidentAlertParams struct {
	IncidentID pgtype.UUID `json:"incident_id"`
	AlertID    pgtype.UUID `json:"alert_id"`
}

func (q *Queries) DeleteIncidentAlert(ctx context.Context, arg DeleteIncidentAlertParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIncidentAlert, arg.IncidentID, arg.AlertID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIncidentNote = `-- name: DeleteIncidentNote :execrows
DELETE FROM incident_notes WHERE id = $1
`

func (q *Queries) DeleteIncidentNote(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIncidentNote, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIncidentById = `-- name: GetIncidentById :one
SELECT id, title, severity, status, assignee_id, team_id, tags, resolved_at, sla_deadline, sla_breached_at, sla_state, created_at, updated_at FROM incidents WHERE id = $1
`

func (q *Queries) GetIncidentById(ctx context.Context, id pgtype.UUID) (Incident, error) {
	row := q.db.QueryRow(ctx, getIncidentById, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Severity,
		&i.Status,
		&i.AssigneeID,
		&i.TeamID,
		&i.Tags,
		&i.ResolvedAt,
		&i.SlaDeadline,
		&i.SlaBreachedAt,
		&i.SlaState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIncidentNoteById = `-- name: GetIncidentNoteById :one
SELECT id, incident_id, author_id, body, created_at, updated_at FROM incident_notes WHERE id = $1
`

func (q *Queries) GetIncidentNoteById(ctx context.Context, id pgtype.UUID) (IncidentNote, error) {
	row := q.db.QueryRow(ctx, getIncidentNoteById, id)
	var i IncidentNote
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertIncidentAlert = `-- name: InsertIncidentAlert :execrows
INSERT INTO incident_alerts (incident_id, alert_id, source)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertIncidentAlertParams struct {
	IncidentID pgtype.UUID `json:"incident_id"`
	AlertID    pgtype.UUID `json:"alert_id"`
	Source     LinkSource  `json:"source"`
}

func (q *Queries) InsertIncidentAlert(ctx context.Context, arg InsertIncidentAlertParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertIncidentAlert, arg.IncidentID, arg.AlertID, arg.Source)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertIncidentEvent = `-- name: InsertIncidentEvent :one
INSERT INTO incident_events (incident_id, type, actor_id, body)
VALUES ($1, $2, $3, $4)
RETURNING id, incident_id, type, actor_id, body, created_at
`

type InsertIncidentEventParams struct {
	IncidentID pgtype.UUID     `json:"incident_id"`
	Type       EventType       `json:"type"`
	ActorID    pgtype.UUID     `json:"actor_id"`
	Body       json.RawMessage `json:"body"`
}

func (q *Queries) InsertIncidentEvent(ctx context.Context, arg InsertIncidentEventParams) (IncidentEvent, error) {
	row := q.db.QueryRow(ctx, insertIncidentEvent,
		arg.IncidentID,
		arg.Type,
		arg.ActorID,
		arg.Body,
	)
	var i IncidentEvent
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Type,
		&i.ActorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const insertIncidentNote = `-- name: InsertIncidentNote :one
INSERT INTO incident_notes (incident_id, author_id, body)
VALUES ($1, $2, $3)
RETURNING id, incident_id, author_id, body, created_at, updated_at
`

type InsertIncidentNoteParams struct {
	IncidentID pgtype.UUID `json:"incident_id"`
	AuthorID   pgtype.UUID `json:"author_id"`
	Body       string      `json:"body"`
}

func (q *Queries) InsertIncidentNote(ctx context.Context, arg InsertIncidentNoteParams) (IncidentNote, error) {
	row := q.db.QueryRow(ctx, insertIncidentNote, arg.IncidentID, arg.AuthorID, arg.Body)
	var i IncidentNote
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIncidentAlerts = `-- name: ListIncidentAlerts :many
SELECT a.id, a.title, a.severity, a.source_kind, a.reporter, ia.source AS link_source
FROM incident_alerts ia
JOIN alerts a ON a.id = ia.alert_id
WHERE ia.incident_id = $1
ORDER BY a.created_at DESC, a.id DESC
`

type ListIncidentAlertsRow struct {
	ID         pgtype.UUID   `json:"id"`
	Title      string        `json:"title"`
	Severity   AlertSeverity `json:"severity"`
	SourceKind SourceKind    `json:"source_kind"`
	Reporter   pgtype.Text   `json:"reporter"`
	LinkSource LinkSource    `json:"link_source"`
}

func (q *Queries) ListIncidentAlerts(ctx context.Context, incidentID pgtype.UUID) ([]ListIncidentAlertsRow, error) {
	rows, err := q.db.Query(ctx, listIncidentAlerts, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncidentAlertsRow
	for rows.Next() {
		var i ListIncidentAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Severity,
			&i.SourceKind,
			&i.Reporter,
			&i.LinkSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentEvents = `-- name: ListIncidentEvents :many
SELECT e.id, e.incident_id, e.type, e.actor_id, e.body, e.created_at, u.username AS actor_username
FROM incident_events e
LEFT JOIN users u ON u.id = e.actor_id
WHERE e.incident_id = $1
ORDER BY e.created_at, e.id
`

type ListIncidentEventsRow struct {
	ID            pgtype.UUID      `json:"id"`
	IncidentID    pgtype.UUID      `json:"incident_id"`
	Type          EventType        `json:"type"`
	ActorID       pgtype.UUID      `json:"actor_id"`
	Body          json.RawMessage  `json:"body"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	ActorUsername pgtype.Text      `json:"actor_username"`
}

func (q *Queries) ListIncidentEvents(ctx context.Context, incidentID pgtype.UUID) ([]ListIncidentEventsRow, error) {
	rows, err := q.db.Query(ctx, listIncidentEvents, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncidentEventsRow
	for rows.Next() {
		var i ListIncidentEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Type,
			&i.ActorID,
			&i.Body,
			&i.CreatedAt,
			&i.ActorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentNotes = `-- name: ListIncidentNotes :many
SELECT n.id, n.incident_id, n.author_id, n.body, n.created_at, n.updated_at, u.username AS author_username
FROM incident_notes n
LEFT JOIN users u ON u.id = n.author_id
WHERE n.incident_id = $1
ORDER BY n.created_at, n.id
`

type ListIncidentNotesRow struct {
	ID             pgtype.UUID      `json:"id"`
	IncidentID     pgtype.UUID      `json:"incident_id"`
	AuthorID       pgtype.UUID      `json:"author_id"`
	Body           string           `json:"body"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	AuthorUsername pgtype.Text      `json:"author_username"`
}

func (q *Queries) ListIncidentNotes(ctx context.Context, incidentID pgtype.UUID) ([]ListIncidentNotesRow, error) {
	rows, err := q.db.Query(ctx, listIncidentNotes, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncidentNotesRow
	for rows.Next() {
		var i ListIncidentNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncident = `-- name: UpdateIncident :one
UPDATE incidents
SET
    severity = CASE
        WHEN $1::boolean THEN $2::alert_severity
        ELSE severity
    END,
    assignee_id = CASE
        WHEN $3::boolean THEN $4::uuid
        ELSE assignee_id
    END,
    team_id = CASE
        WHEN $5::boolean THEN $6::uuid
        ELSE team_id
    END,
    tags = CASE
        WHEN $7::boolean THEN COALESCE($8::text[], '{}')
        ELSE tags
    END,
    updated_at = NOW()
WHERE id = $9
RETURNING id, title, severity, status, assignee_id, team_id, tags, resolved_at, sla_deadline, sla_breached_at, sla_state, created_at, updated_at
`

type UpdateIncidentParams struct {
	SeveritySet   bool              `json:"severity_set"`
	Severity      NullAlertSeverity `json:"severity"`
	AssigneeIDSet bool              `json:"assignee_id_set"`
	AssigneeID    pgtype.UUID       `json:"assignee_id"`
	TeamIDSet     bool              `json:"team_id_set"`
	TeamID        pgtype.UUID       `json:"team_id"`
	TagsSet       bool              `json:"tags_set"`
	Tags          []string          `json:"tags"`
	ID            pgtype.UUID       `json:"id"`
}

func (q *Queries) UpdateIncident(ctx context.Context, arg UpdateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncident,
		arg.SeveritySet,
		arg.Severity,
		arg.AssigneeIDSet,
		arg.AssigneeID,
		arg.TeamIDSet,
		arg.TeamID,
		arg.TagsSet,
		arg.Tags,
		arg.ID,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Severity,
		&i.Status,
		&i.AssigneeID,
		&i.TeamID,
		&i.Tags,
		&i.ResolvedAt,
		&i.SlaDeadline,
		&i.SlaBreachedAt,
		&i.SlaState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIncidentNote = `-- name: UpdateIncidentNote :one
UPDATE incident_notes
SET body = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, incident_id, author_id, body, created_at, updated_at
`

type UpdateIncidentNoteParams struct {
	Body string      `json:"body"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateIncidentNote(ctx context.Context, arg UpdateIncidentNoteParams) (IncidentNote, error) {
	row := q.db.QueryRow(ctx, updateIncidentNote, arg.Body, arg.ID)
	var i IncidentNote
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIncidentStatus = `-- name: UpdateIncidentStatus :one
UPDATE incidents
SET
    status = $1,
    resolved_at = CASE
        WHEN $1::incident_status IN ('resolved', 'closed')
            THEN COALESCE(resolved_at, NOW())
        ELSE NULL
    END,
    updated_at = NOW()
WHERE id = $2
RETURNING id, title, severity, status, assignee_id, team_id, tags, resolved_at, sla_deadline, sla_breached_at, sla_state, created_at, updated_at
`

type UpdateIncidentStatusParams struct {
	Status IncidentStatus `json:"status"`
	ID     pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateIncidentStatus(ctx context.Context, arg UpdateIncidentStatusParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncidentStatus, arg.Status, arg.ID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Severity,
		&i.Status,
		&i.AssigneeID,
		&i.TeamID,
		&i.Tags,
		&i.ResolvedAt,
		&i.SlaDeadline,
		&i.SlaBreachedAt,
		&i.SlaState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
