// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PlaybookStatus string

const (
	PlaybookStatusInProgress PlaybookStatus = "in_progress"
	PlaybookStatusSuccess    PlaybookStatus = "success"
	PlaybookStatusFailed     PlaybookStatus = "failed"
)

func (e *PlaybookStatus) Scan(src any) error {
	switch s := src.(type) {
	case []byte:
		*e = PlaybookStatus(s)
	case string:
		*e = PlaybookStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PlaybookStatus: %T", src)
	}
	return nil
}

type NullPlaybookStatus struct {
	PlaybookStatus PlaybookStatus `json:"playbook_status"`
	Valid          bool           `json:"valid"` // Valid is true if PlaybookStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlaybookStatus) Scan(value any) error {
	if value == nil {
		ns.PlaybookStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlaybookStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlaybookStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlaybookStatus), nil
}

type TaskStatus string

const (
	TaskStatusPending    TaskStatus = "pending"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusSuccess    TaskStatus = "success"
	TaskStatusFailed     TaskStatus = "failed"
)

func (e *TaskStatus) Scan(src any) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value any) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type Edge struct {
	ID                pgtype.UUID `json:"id"`
	DestinationID     pgtype.UUID `json:"destination_id"`
	SourceID          pgtype.UUID `json:"source_id"`
	PlaybookID        pgtype.UUID `json:"playbook_id"`
	SourceHandle      pgtype.Text `json:"source_handle"`
	DestinationHandle pgtype.Text `json:"destination_handle"`
}

type Playbook struct {
	ID          pgtype.UUID      `json:"id"`
	Name        pgtype.Text      `json:"name"`
	Description pgtype.Text      `json:"description"`
	TriggerType pgtype.UUID      `json:"trigger_type"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type PlaybookHistory struct {
	ID          pgtype.UUID      `json:"id"`
	PlaybookID  pgtype.UUID      `json:"playbook_id"`
	Status      PlaybookStatus   `json:"status"`
	Error       pgtype.Text      `json:"error"`
	Result      []byte           `json:"result"`
	TriggeredAt pgtype.Timestamp `json:"triggered_at"`
	Edges       []byte           `json:"edges"`
}

type PlaybookTrigger struct {
	ID          pgtype.UUID `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
}

type Scheduler struct {
	ID         pgtype.UUID      `json:"id"`
	PlaybookID pgtype.UUID      `json:"playbook_id"`
	Cron       pgtype.Text      `json:"cron"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Task struct {
	ID            pgtype.UUID      `json:"id"`
	PlaybookID    pgtype.UUID      `json:"playbook_id"`
	Name          pgtype.Text      `json:"name"`
	Description   pgtype.Text      `json:"description"`
	Parameters    []byte           `json:"parameters"`
	Config        pgtype.Text      `json:"config"`
	X             pgtype.Float8    `json:"x"`
	Y             pgtype.Float8    `json:"y"`
	ConnectorName pgtype.Text      `json:"connector_name"`
	ConnectorID   pgtype.Text      `json:"connector_id"`
	Operation     pgtype.Text      `json:"operation"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type TaskHistory struct {
	ID                pgtype.UUID      `json:"id"`
	PlaybookHistoryID pgtype.UUID      `json:"playbook_history_id"`
	TaskID            pgtype.UUID      `json:"task_id"`
	Name              pgtype.Text      `json:"name"`
	Description       pgtype.Text      `json:"description"`
	Parameters        []byte           `json:"parameters"`
	Config            pgtype.Text      `json:"config"`
	X                 pgtype.Float8    `json:"x"`
	Y                 pgtype.Float8    `json:"y"`
	ConnectorName     pgtype.Text      `json:"connector_name"`
	ConnectorID       pgtype.Text      `json:"connector_id"`
	Operation         pgtype.Text      `json:"operation"`
	Status            TaskStatus       `json:"status"`
	DestinationIds    []pgtype.UUID    `json:"destination_ids"`
	Error             pgtype.Text      `json:"error"`
	Result            []byte           `json:"result"`
	TriggeredAt       pgtype.Timestamp `json:"triggered_at"`
}

type User struct {
	ID        pgtype.UUID `json:"id"`
	Username  string      `json:"username"`
	Email     string      `json:"email"`
	Password  string      `json:"password"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
}
