// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AlertSeverity string

const (
	AlertSeverityCritical AlertSeverity = "critical"
	AlertSeverityHigh     AlertSeverity = "high"
	AlertSeverityMedium   AlertSeverity = "medium"
	AlertSeverityLow      AlertSeverity = "low"
)

func (e *AlertSeverity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertSeverity(s)
	case string:
		*e = AlertSeverity(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertSeverity: %T", src)
	}
	return nil
}

type NullAlertSeverity struct {
	AlertSeverity AlertSeverity `json:"alert_severity"`
	Valid         bool          `json:"valid"` // Valid is true if AlertSeverity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertSeverity) Scan(value interface{}) error {
	if value == nil {
		ns.AlertSeverity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertSeverity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertSeverity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertSeverity), nil
}

type AlertStatus string

const (
	AlertStatusNew           AlertStatus = "new"
	AlertStatusInvestigating AlertStatus = "investigating"
	AlertStatusResolved      AlertStatus = "resolved"
	AlertStatusFalsepos      AlertStatus = "falsepos"
	AlertStatusClosed        AlertStatus = "closed"
)

func (e *AlertStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertStatus(s)
	case string:
		*e = AlertStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertStatus: %T", src)
	}
	return nil
}

type NullAlertStatus struct {
	AlertStatus AlertStatus `json:"alert_status"`
	Valid       bool        `json:"valid"` // Valid is true if AlertStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AlertStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertStatus), nil
}

type AuthProviderType string

const (
	AuthProviderTypeLocal AuthProviderType = "local"
	AuthProviderTypeOidc  AuthProviderType = "oidc"
	AuthProviderTypeLdap  AuthProviderType = "ldap"
)

func (e *AuthProviderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProviderType(s)
	case string:
		*e = AuthProviderType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProviderType: %T", src)
	}
	return nil
}

type NullAuthProviderType struct {
	AuthProviderType AuthProviderType `json:"auth_provider_type"`
	Valid            bool             `json:"valid"` // Valid is true if AuthProviderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProviderType) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProviderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProviderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProviderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProviderType), nil
}

type EventType string

const (
	EventTypeCreated       EventType = "created"
	EventTypeStatusChanged EventType = "status_changed"
	EventTypeEscalated     EventType = "escalated"
	EventTypeTriage        EventType = "triage"
	EventTypeSla           EventType = "sla"
	EventTypeCorrelation   EventType = "correlation"
	EventTypeAttackTag     EventType = "attack_tag"
	EventTypeLinked        EventType = "linked"
	EventTypeUnlinked      EventType = "unlinked"
)

func (e *EventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventType(s)
	case string:
		*e = EventType(s)
	default:
		return fmt.Errorf("unsupported scan type for EventType: %T", src)
	}
	return nil
}

type NullEventType struct {
	EventType EventType `json:"event_type"`
	Valid     bool      `json:"valid"` // Valid is true if EventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventType) Scan(value interface{}) error {
	if value == nil {
		ns.EventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventType), nil
}

type IncidentStatus string

const (
	IncidentStatusOpen          IncidentStatus = "open"
	IncidentStatusInvestigating IncidentStatus = "investigating"
	IncidentStatusContained     IncidentStatus = "contained"
	IncidentStatusResolved      IncidentStatus = "resolved"
	IncidentStatusClosed        IncidentStatus = "closed"
)

func (e *IncidentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IncidentStatus(s)
	case string:
		*e = IncidentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IncidentStatus: %T", src)
	}
	return nil
}

type NullIncidentStatus struct {
	IncidentStatus IncidentStatus `json:"incident_status"`
	Valid          bool           `json:"valid"` // Valid is true if IncidentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIncidentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IncidentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IncidentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIncidentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IncidentStatus), nil
}

type LinkSource string

const (
	LinkSourceManual      LinkSource = "manual"
	LinkSourceEscalate    LinkSource = "escalate"
	LinkSourceCorrelation LinkSource = "correlation"
)

func (e *LinkSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LinkSource(s)
	case string:
		*e = LinkSource(s)
	default:
		return fmt.Errorf("unsupported scan type for LinkSource: %T", src)
	}
	return nil
}

type NullLinkSource struct {
	LinkSource LinkSource `json:"link_source"`
	Valid      bool       `json:"valid"` // Valid is true if LinkSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLinkSource) Scan(value interface{}) error {
	if value == nil {
		ns.LinkSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LinkSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLinkSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LinkSource), nil
}

type PlaybookStatus string

const (
	PlaybookStatusInProgress PlaybookStatus = "in_progress"
	PlaybookStatusSuccess    PlaybookStatus = "success"
	PlaybookStatusFailed     PlaybookStatus = "failed"
)

func (e *PlaybookStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlaybookStatus(s)
	case string:
		*e = PlaybookStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PlaybookStatus: %T", src)
	}
	return nil
}

type NullPlaybookStatus struct {
	PlaybookStatus PlaybookStatus `json:"playbook_status"`
	Valid          bool           `json:"valid"` // Valid is true if PlaybookStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlaybookStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PlaybookStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlaybookStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlaybookStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlaybookStatus), nil
}

type SlaState string

const (
	SlaStateOk       SlaState = "ok"
	SlaStateWarning  SlaState = "warning"
	SlaStateBreached SlaState = "breached"
	SlaStateMet      SlaState = "met"
)

func (e *SlaState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SlaState(s)
	case string:
		*e = SlaState(s)
	default:
		return fmt.Errorf("unsupported scan type for SlaState: %T", src)
	}
	return nil
}

type NullSlaState struct {
	SlaState SlaState `json:"sla_state"`
	Valid    bool     `json:"valid"` // Valid is true if SlaState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSlaState) Scan(value interface{}) error {
	if value == nil {
		ns.SlaState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SlaState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSlaState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SlaState), nil
}

type SourceKind string

const (
	SourceKindEdr      SourceKind = "edr"
	SourceKindIdentity SourceKind = "identity"
	SourceKindEmail    SourceKind = "email"
	SourceKindFirewall SourceKind = "firewall"
	SourceKindDlp      SourceKind = "dlp"
)

func (e *SourceKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SourceKind(s)
	case string:
		*e = SourceKind(s)
	default:
		return fmt.Errorf("unsupported scan type for SourceKind: %T", src)
	}
	return nil
}

type NullSourceKind struct {
	SourceKind SourceKind `json:"source_kind"`
	Valid      bool       `json:"valid"` // Valid is true if SourceKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourceKind) Scan(value interface{}) error {
	if value == nil {
		ns.SourceKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SourceKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourceKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SourceKind), nil
}

type TaskStatus string

const (
	TaskStatusPending    TaskStatus = "pending"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusSuccess    TaskStatus = "success"
	TaskStatusFailed     TaskStatus = "failed"
	TaskStatusSkipped    TaskStatus = "skipped"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type TriggerType string

const (
	TriggerTypeManual     TriggerType = "manual"
	TriggerTypeWebhook    TriggerType = "webhook"
	TriggerTypeReferenced TriggerType = "referenced"
	TriggerTypeOnCreate   TriggerType = "on_create"
	TriggerTypeOnUpdate   TriggerType = "on_update"
	TriggerTypeOnDelete   TriggerType = "on_delete"
)

func (e *TriggerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TriggerType(s)
	case string:
		*e = TriggerType(s)
	default:
		return fmt.Errorf("unsupported scan type for TriggerType: %T", src)
	}
	return nil
}

type NullTriggerType struct {
	TriggerType TriggerType `json:"trigger_type"`
	Valid       bool        `json:"valid"` // Valid is true if TriggerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTriggerType) Scan(value interface{}) error {
	if value == nil {
		ns.TriggerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TriggerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTriggerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TriggerType), nil
}

type Alert struct {
	ID            pgtype.UUID      `json:"id"`
	Title         string           `json:"title"`
	Severity      AlertSeverity    `json:"severity"`
	Status        AlertStatus      `json:"status"`
	SourceKind    SourceKind       `json:"source_kind"`
	Reporter      pgtype.Text      `json:"reporter"`
	AssigneeID    pgtype.UUID      `json:"assignee_id"`
	TeamID        pgtype.UUID      `json:"team_id"`
	Payload       json.RawMessage  `json:"payload"`
	Tags          []string         `json:"tags"`
	Triage        []byte           `json:"triage"`
	ClosureNote   pgtype.Text      `json:"closure_note"`
	Fingerprint   string           `json:"fingerprint"`
	DedupCount    int32            `json:"dedup_count"`
	LastSeen      pgtype.Timestamp `json:"last_seen"`
	TriagedAt     pgtype.Timestamp `json:"triaged_at"`
	SlaDeadline   pgtype.Timestamp `json:"sla_deadline"`
	SlaBreachedAt pgtype.Timestamp `json:"sla_breached_at"`
	SlaState      SlaState         `json:"sla_state"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type AlertEvent struct {
	ID        pgtype.UUID      `json:"id"`
	AlertID   pgtype.UUID      `json:"alert_id"`
	Type      EventType        `json:"type"`
	ActorID   pgtype.UUID      `json:"actor_id"`
	Body      json.RawMessage  `json:"body"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type AlertNote struct {
	ID        pgtype.UUID      `json:"id"`
	AlertID   pgtype.UUID      `json:"alert_id"`
	AuthorID  pgtype.UUID      `json:"author_id"`
	Body      string           `json:"body"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type AuditLog struct {
	ID        pgtype.UUID      `json:"id"`
	ActorID   pgtype.UUID      `json:"actor_id"`
	Module    string           `json:"module"`
	Action    string           `json:"action"`
	EntityID  pgtype.Text      `json:"entity_id"`
	Detail    []byte           `json:"detail"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type AuthProvider struct {
	ID        pgtype.UUID      `json:"id"`
	Type      AuthProviderType `json:"type"`
	Name      string           `json:"name"`
	Config    json.RawMessage  `json:"config"`
	Enabled   bool             `json:"enabled"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Connector struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	Runtime    string             `json:"runtime"`
	Version    string             `json:"version"`
	Checksum   string             `json:"checksum"`
	UploadedBy string             `json:"uploaded_by"`
	Enabled    bool               `json:"enabled"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Edge struct {
	ID                pgtype.UUID `json:"id"`
	DestinationID     pgtype.UUID `json:"destination_id"`
	SourceID          pgtype.UUID `json:"source_id"`
	PlaybookID        pgtype.UUID `json:"playbook_id"`
	SourceHandle      pgtype.Text `json:"source_handle"`
	DestinationHandle pgtype.Text `json:"destination_handle"`
}

type Incident struct {
	ID            pgtype.UUID      `json:"id"`
	Title         string           `json:"title"`
	Severity      AlertSeverity    `json:"severity"`
	Status        IncidentStatus   `json:"status"`
	AssigneeID    pgtype.UUID      `json:"assignee_id"`
	TeamID        pgtype.UUID      `json:"team_id"`
	Tags          []string         `json:"tags"`
	ResolvedAt    pgtype.Timestamp `json:"resolved_at"`
	SlaDeadline   pgtype.Timestamp `json:"sla_deadline"`
	SlaBreachedAt pgtype.Timestamp `json:"sla_breached_at"`
	SlaState      SlaState         `json:"sla_state"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type IncidentAlert struct {
	IncidentID pgtype.UUID      `json:"incident_id"`
	AlertID    pgtype.UUID      `json:"alert_id"`
	Source     LinkSource       `json:"source"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type IncidentEvent struct {
	ID         pgtype.UUID      `json:"id"`
	IncidentID pgtype.UUID      `json:"incident_id"`
	Type       EventType        `json:"type"`
	ActorID    pgtype.UUID      `json:"actor_id"`
	Body       json.RawMessage  `json:"body"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type IncidentNote struct {
	ID         pgtype.UUID      `json:"id"`
	IncidentID pgtype.UUID      `json:"incident_id"`
	AuthorID   pgtype.UUID      `json:"author_id"`
	Body       string           `json:"body"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Playbook struct {
	ID                pgtype.UUID      `json:"id"`
	Name              pgtype.Text      `json:"name"`
	Description       pgtype.Text      `json:"description"`
	TriggerType       NullTriggerType  `json:"trigger_type"`
	TriggerParameters []byte           `json:"trigger_parameters"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type PlaybookHistory struct {
	ID          pgtype.UUID      `json:"id"`
	PlaybookID  pgtype.UUID      `json:"playbook_id"`
	Status      PlaybookStatus   `json:"status"`
	Error       pgtype.Text      `json:"error"`
	Result      []byte           `json:"result"`
	TriggeredAt pgtype.Timestamp `json:"triggered_at"`
	Edges       []byte           `json:"edges"`
}

type RefreshToken struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	TokenHash string           `json:"token_hash"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	RevokedAt pgtype.Timestamp `json:"revoked_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Role struct {
	ID          pgtype.UUID      `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	IsBuiltin   bool             `json:"is_builtin"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type RolePermission struct {
	RoleID pgtype.UUID `json:"role_id"`
	Module string      `json:"module"`
	Action string      `json:"action"`
}

type Scheduler struct {
	ID         pgtype.UUID      `json:"id"`
	PlaybookID pgtype.UUID      `json:"playbook_id"`
	Cron       pgtype.Text      `json:"cron"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Task struct {
	ID            pgtype.UUID      `json:"id"`
	PlaybookID    pgtype.UUID      `json:"playbook_id"`
	Name          pgtype.Text      `json:"name"`
	Description   pgtype.Text      `json:"description"`
	Parameters    []byte           `json:"parameters"`
	Config        pgtype.Text      `json:"config"`
	X             pgtype.Float8    `json:"x"`
	Y             pgtype.Float8    `json:"y"`
	ConnectorName pgtype.Text      `json:"connector_name"`
	ConnectorID   pgtype.Text      `json:"connector_id"`
	Operation     pgtype.Text      `json:"operation"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type TaskHistory struct {
	ID                pgtype.UUID      `json:"id"`
	PlaybookHistoryID pgtype.UUID      `json:"playbook_history_id"`
	TaskID            pgtype.UUID      `json:"task_id"`
	Name              pgtype.Text      `json:"name"`
	Description       pgtype.Text      `json:"description"`
	Parameters        []byte           `json:"parameters"`
	Config            pgtype.Text      `json:"config"`
	X                 pgtype.Float8    `json:"x"`
	Y                 pgtype.Float8    `json:"y"`
	ConnectorName     pgtype.Text      `json:"connector_name"`
	ConnectorID       pgtype.Text      `json:"connector_id"`
	Operation         pgtype.Text      `json:"operation"`
	Status            TaskStatus       `json:"status"`
	DestinationIds    []pgtype.UUID    `json:"destination_ids"`
	Error             pgtype.Text      `json:"error"`
	Result            []byte           `json:"result"`
	TriggeredAt       pgtype.Timestamp `json:"triggered_at"`
}

type Team struct {
	ID          pgtype.UUID      `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type TeamMember struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

type TeamRole struct {
	TeamID pgtype.UUID `json:"team_id"`
	RoleID pgtype.UUID `json:"role_id"`
}

type User struct {
	ID           pgtype.UUID      `json:"id"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	PasswordHash pgtype.Text      `json:"password_hash"`
	FirstName    pgtype.Text      `json:"first_name"`
	LastName     pgtype.Text      `json:"last_name"`
	AuthProvider AuthProviderType `json:"auth_provider"`
	ExternalID   pgtype.Text      `json:"external_id"`
	IsActive     bool             `json:"is_active"`
	LastLoginAt  pgtype.Timestamp `json:"last_login_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type UserRole struct {
	UserID pgtype.UUID `json:"user_id"`
	RoleID pgtype.UUID `json:"role_id"`
}
