// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthProviderType string

const (
	AuthProviderTypeLocal AuthProviderType = "local"
	AuthProviderTypeOidc  AuthProviderType = "oidc"
	AuthProviderTypeLdap  AuthProviderType = "ldap"
)

func (e *AuthProviderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProviderType(s)
	case string:
		*e = AuthProviderType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProviderType: %T", src)
	}
	return nil
}

type NullAuthProviderType struct {
	AuthProviderType AuthProviderType `json:"auth_provider_type"`
	Valid            bool             `json:"valid"` // Valid is true if AuthProviderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProviderType) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProviderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProviderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProviderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProviderType), nil
}

type PlaybookStatus string

const (
	PlaybookStatusInProgress PlaybookStatus = "in_progress"
	PlaybookStatusSuccess    PlaybookStatus = "success"
	PlaybookStatusFailed     PlaybookStatus = "failed"
)

func (e *PlaybookStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlaybookStatus(s)
	case string:
		*e = PlaybookStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PlaybookStatus: %T", src)
	}
	return nil
}

type NullPlaybookStatus struct {
	PlaybookStatus PlaybookStatus `json:"playbook_status"`
	Valid          bool           `json:"valid"` // Valid is true if PlaybookStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlaybookStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PlaybookStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlaybookStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlaybookStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlaybookStatus), nil
}

type TaskStatus string

const (
	TaskStatusPending    TaskStatus = "pending"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusSuccess    TaskStatus = "success"
	TaskStatusFailed     TaskStatus = "failed"
	TaskStatusSkipped    TaskStatus = "skipped"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type TriggerType string

const (
	TriggerTypeManual     TriggerType = "manual"
	TriggerTypeWebhook    TriggerType = "webhook"
	TriggerTypeReferenced TriggerType = "referenced"
	TriggerTypeOnCreate   TriggerType = "on_create"
	TriggerTypeOnUpdate   TriggerType = "on_update"
	TriggerTypeOnDelete   TriggerType = "on_delete"
)

func (e *TriggerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TriggerType(s)
	case string:
		*e = TriggerType(s)
	default:
		return fmt.Errorf("unsupported scan type for TriggerType: %T", src)
	}
	return nil
}

type NullTriggerType struct {
	TriggerType TriggerType `json:"trigger_type"`
	Valid       bool        `json:"valid"` // Valid is true if TriggerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTriggerType) Scan(value interface{}) error {
	if value == nil {
		ns.TriggerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TriggerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTriggerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TriggerType), nil
}

type AuditLog struct {
	ID        pgtype.UUID      `json:"id"`
	ActorID   pgtype.UUID      `json:"actor_id"`
	Module    string           `json:"module"`
	Action    string           `json:"action"`
	EntityID  pgtype.Text      `json:"entity_id"`
	Detail    []byte           `json:"detail"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type AuthProvider struct {
	ID        pgtype.UUID      `json:"id"`
	Type      AuthProviderType `json:"type"`
	Name      string           `json:"name"`
	Config    json.RawMessage  `json:"config"`
	Enabled   bool             `json:"enabled"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Connector struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	Runtime    string             `json:"runtime"`
	Version    string             `json:"version"`
	Checksum   string             `json:"checksum"`
	UploadedBy string             `json:"uploaded_by"`
	Enabled    bool               `json:"enabled"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Edge struct {
	ID                pgtype.UUID `json:"id"`
	DestinationID     pgtype.UUID `json:"destination_id"`
	SourceID          pgtype.UUID `json:"source_id"`
	PlaybookID        pgtype.UUID `json:"playbook_id"`
	SourceHandle      pgtype.Text `json:"source_handle"`
	DestinationHandle pgtype.Text `json:"destination_handle"`
}

type Playbook struct {
	ID                pgtype.UUID      `json:"id"`
	Name              pgtype.Text      `json:"name"`
	Description       pgtype.Text      `json:"description"`
	TriggerType       NullTriggerType  `json:"trigger_type"`
	TriggerParameters []byte           `json:"trigger_parameters"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type PlaybookHistory struct {
	ID          pgtype.UUID      `json:"id"`
	PlaybookID  pgtype.UUID      `json:"playbook_id"`
	Status      PlaybookStatus   `json:"status"`
	Error       pgtype.Text      `json:"error"`
	Result      []byte           `json:"result"`
	TriggeredAt pgtype.Timestamp `json:"triggered_at"`
	Edges       []byte           `json:"edges"`
}

type RefreshToken struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	TokenHash string           `json:"token_hash"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	RevokedAt pgtype.Timestamp `json:"revoked_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Role struct {
	ID          pgtype.UUID      `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	IsBuiltin   bool             `json:"is_builtin"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type RolePermission struct {
	RoleID pgtype.UUID `json:"role_id"`
	Module string      `json:"module"`
	Action string      `json:"action"`
}

type Scheduler struct {
	ID         pgtype.UUID      `json:"id"`
	PlaybookID pgtype.UUID      `json:"playbook_id"`
	Cron       pgtype.Text      `json:"cron"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Task struct {
	ID            pgtype.UUID      `json:"id"`
	PlaybookID    pgtype.UUID      `json:"playbook_id"`
	Name          pgtype.Text      `json:"name"`
	Description   pgtype.Text      `json:"description"`
	Parameters    []byte           `json:"parameters"`
	Config        pgtype.Text      `json:"config"`
	X             pgtype.Float8    `json:"x"`
	Y             pgtype.Float8    `json:"y"`
	ConnectorName pgtype.Text      `json:"connector_name"`
	ConnectorID   pgtype.Text      `json:"connector_id"`
	Operation     pgtype.Text      `json:"operation"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type TaskHistory struct {
	ID                pgtype.UUID      `json:"id"`
	PlaybookHistoryID pgtype.UUID      `json:"playbook_history_id"`
	TaskID            pgtype.UUID      `json:"task_id"`
	Name              pgtype.Text      `json:"name"`
	Description       pgtype.Text      `json:"description"`
	Parameters        []byte           `json:"parameters"`
	Config            pgtype.Text      `json:"config"`
	X                 pgtype.Float8    `json:"x"`
	Y                 pgtype.Float8    `json:"y"`
	ConnectorName     pgtype.Text      `json:"connector_name"`
	ConnectorID       pgtype.Text      `json:"connector_id"`
	Operation         pgtype.Text      `json:"operation"`
	Status            TaskStatus       `json:"status"`
	DestinationIds    []pgtype.UUID    `json:"destination_ids"`
	Error             pgtype.Text      `json:"error"`
	Result            []byte           `json:"result"`
	TriggeredAt       pgtype.Timestamp `json:"triggered_at"`
}

type Team struct {
	ID          pgtype.UUID      `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type TeamMember struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

type User struct {
	ID           pgtype.UUID      `json:"id"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	PasswordHash pgtype.Text      `json:"password_hash"`
	FirstName    pgtype.Text      `json:"first_name"`
	LastName     pgtype.Text      `json:"last_name"`
	AuthProvider AuthProviderType `json:"auth_provider"`
	ExternalID   pgtype.Text      `json:"external_id"`
	IsActive     bool             `json:"is_active"`
	LastLoginAt  pgtype.Timestamp `json:"last_login_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type UserRole struct {
	UserID pgtype.UUID `json:"user_id"`
	RoleID pgtype.UUID `json:"role_id"`
}
