// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playbooks.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlaybook = `-- name: CreatePlaybook :one
INSERT INTO playbooks (name, description, trigger_type, trigger_parameters)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, trigger_type, trigger_parameters, created_at, updated_at
`

type CreatePlaybookParams struct {
	Name              pgtype.Text     `json:"name"`
	Description       pgtype.Text     `json:"description"`
	TriggerType       NullTriggerType `json:"trigger_type"`
	TriggerParameters []byte          `json:"trigger_parameters"`
}

func (q *Queries) CreatePlaybook(ctx context.Context, arg CreatePlaybookParams) (Playbook, error) {
	row := q.db.QueryRow(ctx, createPlaybook,
		arg.Name,
		arg.Description,
		arg.TriggerType,
		arg.TriggerParameters,
	)
	var i Playbook
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TriggerType,
		&i.TriggerParameters,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlaybookHistory = `-- name: CreatePlaybookHistory :one
INSERT INTO playbook_history (playbook_id, triggered_at, edges)
VALUES ($1, NOW(), $2)
RETURNING id, playbook_id, status, error, result, triggered_at, edges
`

type CreatePlaybookHistoryParams struct {
	PlaybookID pgtype.UUID `json:"playbook_id"`
	Edges      []byte      `json:"edges"`
}

func (q *Queries) CreatePlaybookHistory(ctx context.Context, arg CreatePlaybookHistoryParams) (PlaybookHistory, error) {
	row := q.db.QueryRow(ctx, createPlaybookHistory, arg.PlaybookID, arg.Edges)
	var i PlaybookHistory
	err := row.Scan(
		&i.ID,
		&i.PlaybookID,
		&i.Status,
		&i.Error,
		&i.Result,
		&i.TriggeredAt,
		&i.Edges,
	)
	return i, err
}

const getPlaybookById = `-- name: GetPlaybookById :one
SELECT id, name, description, trigger_type, trigger_parameters, created_at, updated_at FROM playbooks WHERE id = $1
`

func (q *Queries) GetPlaybookById(ctx context.Context, id pgtype.UUID) (Playbook, error) {
	row := q.db.QueryRow(ctx, getPlaybookById, id)
	var i Playbook
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TriggerType,
		&i.TriggerParameters,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaybookGraphById = `-- name: GetPlaybookGraphById :one
SELECT
    playbooks.id, playbooks.name, playbooks.description, playbooks.trigger_type, playbooks.trigger_parameters, playbooks.created_at, playbooks.updated_at,
    (SELECT JSON_AGG(tasks.*)
        FROM tasks
        WHERE tasks.playbook_id = playbooks.id) AS tasks,
    (SELECT JSON_AGG(edges.*)
        FROM edges
        WHERE edges.playbook_id = playbooks.id) AS edges
FROM playbooks WHERE playbooks.id = $1
`

type GetPlaybookGraphByIdRow struct {
	ID                pgtype.UUID      `json:"id"`
	Name              pgtype.Text      `json:"name"`
	Description       pgtype.Text      `json:"description"`
	TriggerType       NullTriggerType  `json:"trigger_type"`
	TriggerParameters []byte           `json:"trigger_parameters"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	Tasks             []byte           `json:"tasks"`
	Edges             []byte           `json:"edges"`
}

func (q *Queries) GetPlaybookGraphById(ctx context.Context, id pgtype.UUID) (GetPlaybookGraphByIdRow, error) {
	row := q.db.QueryRow(ctx, getPlaybookGraphById, id)
	var i GetPlaybookGraphByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TriggerType,
		&i.TriggerParameters,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tasks,
		&i.Edges,
	)
	return i, err
}

const getPlaybookHistoryById = `-- name: GetPlaybookHistoryById :one
SELECT playbook_history.id, playbook_history.playbook_id, playbook_history.status, playbook_history.error, playbook_history.result, playbook_history.triggered_at, playbook_history.edges, to_jsonb(playbooks) AS playbook_data
FROM playbook_history
JOIN playbooks ON playbooks.id = playbook_history.playbook_id
WHERE playbook_history.id = $1
`

type GetPlaybookHistoryByIdRow struct {
	ID           pgtype.UUID      `json:"id"`
	PlaybookID   pgtype.UUID      `json:"playbook_id"`
	Status       PlaybookStatus   `json:"status"`
	Error        pgtype.Text      `json:"error"`
	Result       []byte           `json:"result"`
	TriggeredAt  pgtype.Timestamp `json:"triggered_at"`
	Edges        []byte           `json:"edges"`
	PlaybookData json.RawMessage  `json:"playbook_data"`
}

func (q *Queries) GetPlaybookHistoryById(ctx context.Context, id pgtype.UUID) (GetPlaybookHistoryByIdRow, error) {
	row := q.db.QueryRow(ctx, getPlaybookHistoryById, id)
	var i GetPlaybookHistoryByIdRow
	err := row.Scan(
		&i.ID,
		&i.PlaybookID,
		&i.Status,
		&i.Error,
		&i.Result,
		&i.TriggeredAt,
		&i.Edges,
		&i.PlaybookData,
	)
	return i, err
}

const updatePlaybook = `-- name: UpdatePlaybook :one
UPDATE playbooks
SET
    name = CASE
        WHEN $1::boolean THEN $2
        ELSE name
    END,
    description = CASE
        WHEN $3::boolean THEN $4
        ELSE description
    END,
    trigger_type = CASE
        WHEN $5::boolean THEN $6
        ELSE trigger_type
    END,
    trigger_parameters = CASE
        WHEN $7::boolean THEN $8
        ELSE trigger_parameters
    END,
    updated_at = NOW()
WHERE id = $9
RETURNING id, name, description, trigger_type, trigger_parameters, created_at, updated_at
`

type UpdatePlaybookParams struct {
	NameSet              bool            `json:"name_set"`
	Name                 pgtype.Text     `json:"name"`
	DescriptionSet       bool            `json:"description_set"`
	Description          pgtype.Text     `json:"description"`
	TriggerTypeSet       bool            `json:"trigger_type_set"`
	TriggerType          NullTriggerType `json:"trigger_type"`
	TriggerParametersSet bool            `json:"trigger_parameters_set"`
	TriggerParameters    []byte          `json:"trigger_parameters"`
	ID                   pgtype.UUID     `json:"id"`
}

func (q *Queries) UpdatePlaybook(ctx context.Context, arg UpdatePlaybookParams) (Playbook, error) {
	row := q.db.QueryRow(ctx, updatePlaybook,
		arg.NameSet,
		arg.Name,
		arg.DescriptionSet,
		arg.Description,
		arg.TriggerTypeSet,
		arg.TriggerType,
		arg.TriggerParametersSet,
		arg.TriggerParameters,
		arg.ID,
	)
	var i Playbook
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TriggerType,
		&i.TriggerParameters,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlaybookHistory = `-- name: UpdatePlaybookHistory :one
UPDATE playbook_history
SET
    status = CASE
        WHEN $1::boolean THEN $2::playbook_status
        ELSE status
    END,
    error = CASE
        WHEN $3::boolean THEN $4
        ELSE error
    END,
    result = $5
WHERE id = $6
RETURNING id, playbook_id, status, error, result, triggered_at, edges
`

type UpdatePlaybookHistoryParams struct {
	StatusSet bool               `json:"status_set"`
	Status    NullPlaybookStatus `json:"status"`
	ErrorSet  bool               `json:"error_set"`
	Error     pgtype.Text        `json:"error"`
	Result    []byte             `json:"result"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdatePlaybookHistory(ctx context.Context, arg UpdatePlaybookHistoryParams) (PlaybookHistory, error) {
	row := q.db.QueryRow(ctx, updatePlaybookHistory,
		arg.StatusSet,
		arg.Status,
		arg.ErrorSet,
		arg.Error,
		arg.Result,
		arg.ID,
	)
	var i PlaybookHistory
	err := row.Scan(
		&i.ID,
		&i.PlaybookID,
		&i.Status,
		&i.Error,
		&i.Result,
		&i.TriggeredAt,
		&i.Edges,
	)
	return i, err
}

const updatePlaybookHistoryStatus = `-- name: UpdatePlaybookHistoryStatus :one
UPDATE playbook_history
SET status = $2
WHERE id = $1
RETURNING id, playbook_id, status, error, result, triggered_at, edges
`

type UpdatePlaybookHistoryStatusParams struct {
	ID     pgtype.UUID    `json:"id"`
	Status PlaybookStatus `json:"status"`
}

func (q *Queries) UpdatePlaybookHistoryStatus(ctx context.Context, arg UpdatePlaybookHistoryStatusParams) (PlaybookHistory, error) {
	row := q.db.QueryRow(ctx, updatePlaybookHistoryStatus, arg.ID, arg.Status)
	var i PlaybookHistory
	err := row.Scan(
		&i.ID,
		&i.PlaybookID,
		&i.Status,
		&i.Error,
		&i.Result,
		&i.TriggeredAt,
		&i.Edges,
	)
	return i, err
}
