// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreatePlaybook(ctx context.Context, arg CreatePlaybookParams) (Playbook, error)
	CreatePlaybookHistory(ctx context.Context, arg CreatePlaybookHistoryParams) (PlaybookHistory, error)
	CreateTaskHistory(ctx context.Context, arg CreateTaskHistoryParams) (TaskHistory, error)
	DeleteAllPlaybookEdges(ctx context.Context, playbookID pgtype.UUID) error
	DeleteConnectorRecord(ctx context.Context, id string) (int64, error)
	DeleteEdges(ctx context.Context, ids []pgtype.UUID) error
	DeleteTasks(ctx context.Context, ids []pgtype.UUID) error
	GetConnectorRecord(ctx context.Context, id string) (Connector, error)
	GetEdgesByPlaybookId(ctx context.Context, playbookID pgtype.UUID) ([]GetEdgesByPlaybookIdRow, error)
	GetPlaybookById(ctx context.Context, id pgtype.UUID) (Playbook, error)
	GetPlaybookGraphById(ctx context.Context, id pgtype.UUID) (GetPlaybookGraphByIdRow, error)
	GetPlaybookHistoryById(ctx context.Context, id pgtype.UUID) (GetPlaybookHistoryByIdRow, error)
	GetPlaybookTriggers(ctx context.Context) ([]PlaybookTrigger, error)
	GetTaskHistoryByPlaybookHistoryId(ctx context.Context, playbookHistoryID pgtype.UUID) ([]TaskHistory, error)
	GetTasksByPlaybookId(ctx context.Context, playbookID pgtype.UUID) ([]Task, error)
	UpdatePlaybook(ctx context.Context, arg UpdatePlaybookParams) (Playbook, error)
	UpdatePlaybookHistory(ctx context.Context, arg UpdatePlaybookHistoryParams) (PlaybookHistory, error)
	UpdatePlaybookHistoryStatus(ctx context.Context, arg UpdatePlaybookHistoryStatusParams) (PlaybookHistory, error)
	UpdateTaskHistory(ctx context.Context, arg UpdateTaskHistoryParams) (TaskHistory, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (TaskHistory, error)
	UpsertConnector(ctx context.Context, arg UpsertConnectorParams) (Connector, error)
	UpsertEdge(ctx context.Context, arg UpsertEdgeParams) (Edge, error)
	UpsertTask(ctx context.Context, arg UpsertTaskParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
