// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTaskHistory = `-- name: CreateTaskHistory :one
INSERT INTO task_history (
    playbook_history_id, task_id, triggered_at, name, description, parameters,
    config, x, y, connector_name, connector_id, operation, destination_ids
)
VALUES ($1, $2, NOW(), $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, playbook_history_id, task_id, name, description, parameters, config, x, y, connector_name, connector_id, operation, status, destination_ids, error, result, triggered_at
`

type CreateTaskHistoryParams struct {
	PlaybookHistoryID pgtype.UUID   `json:"playbook_history_id"`
	TaskID            pgtype.UUID   `json:"task_id"`
	Name              pgtype.Text   `json:"name"`
	Description       pgtype.Text   `json:"description"`
	Parameters        []byte        `json:"parameters"`
	Config            pgtype.Text   `json:"config"`
	X                 pgtype.Float8 `json:"x"`
	Y                 pgtype.Float8 `json:"y"`
	ConnectorName     pgtype.Text   `json:"connector_name"`
	ConnectorID       pgtype.Text   `json:"connector_id"`
	Operation         pgtype.Text   `json:"operation"`
	DestinationIds    []pgtype.UUID `json:"destination_ids"`
}

func (q *Queries) CreateTaskHistory(ctx context.Context, arg CreateTaskHistoryParams) (TaskHistory, error) {
	row := q.db.QueryRow(ctx, createTaskHistory,
		arg.PlaybookHistoryID,
		arg.TaskID,
		arg.Name,
		arg.Description,
		arg.Parameters,
		arg.Config,
		arg.X,
		arg.Y,
		arg.ConnectorName,
		arg.ConnectorID,
		arg.Operation,
		arg.DestinationIds,
	)
	var i TaskHistory
	err := row.Scan(
		&i.ID,
		&i.PlaybookHistoryID,
		&i.TaskID,
		&i.Name,
		&i.Description,
		&i.Parameters,
		&i.Config,
		&i.X,
		&i.Y,
		&i.ConnectorName,
		&i.ConnectorID,
		&i.Operation,
		&i.Status,
		&i.DestinationIds,
		&i.Error,
		&i.Result,
		&i.TriggeredAt,
	)
	return i, err
}

const deleteTasks = `-- name: DeleteTasks :exec
DELETE FROM tasks WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteTasks(ctx context.Context, ids []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTasks, ids)
	return err
}

const getTaskHistoryByPlaybookHistoryId = `-- name: GetTaskHistoryByPlaybookHistoryId :many
SELECT id, playbook_history_id, task_id, name, description, parameters, config, x, y, connector_name, connector_id, operation, status, destination_ids, error, result, triggered_at FROM task_history WHERE playbook_history_id = $1
`

func (q *Queries) GetTaskHistoryByPlaybookHistoryId(ctx context.Context, playbookHistoryID pgtype.UUID) ([]TaskHistory, error) {
	rows, err := q.db.Query(ctx, getTaskHistoryByPlaybookHistoryId, playbookHistoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskHistory
	for rows.Next() {
		var i TaskHistory
		if err := rows.Scan(
			&i.ID,
			&i.PlaybookHistoryID,
			&i.TaskID,
			&i.Name,
			&i.Description,
			&i.Parameters,
			&i.Config,
			&i.X,
			&i.Y,
			&i.ConnectorName,
			&i.ConnectorID,
			&i.Operation,
			&i.Status,
			&i.DestinationIds,
			&i.Error,
			&i.Result,
			&i.TriggeredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByPlaybookId = `-- name: GetTasksByPlaybookId :many
SELECT id, playbook_id, name, description, parameters, config, x, y, connector_name, connector_id, operation, created_at, updated_at FROM tasks WHERE playbook_id = $1
`

func (q *Queries) GetTasksByPlaybookId(ctx context.Context, playbookID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksByPlaybookId, playbookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.PlaybookID,
			&i.Name,
			&i.Description,
			&i.Parameters,
			&i.Config,
			&i.X,
			&i.Y,
			&i.ConnectorName,
			&i.ConnectorID,
			&i.Operation,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskHistory = `-- name: UpdateTaskHistory :one
UPDATE task_history
SET
    name = $1,
    description = $2,
    parameters = $3,
    result = $4,
    x = $5,
    y = $6,
    operation = $7,
    status = CASE
        WHEN $8::boolean THEN $9::task_status
        ELSE status
    END,
    error = CASE
        WHEN $10::boolean THEN $11
        ELSE error
    END,
    connector_name = CASE
        WHEN $12::boolean THEN $13
        ELSE connector_name
    END,
    connector_id = CASE
        WHEN $14::boolean THEN $15
        ELSE connector_id
    END,
    config = CASE
        WHEN $16::boolean THEN $17
        ELSE config
    END
WHERE playbook_history_id = $18 AND task_id = $19
RETURNING id, playbook_history_id, task_id, name, description, parameters, config, x, y, connector_name, connector_id, operation, status, destination_ids, error, result, triggered_at
`

type UpdateTaskHistoryParams struct {
	Name              pgtype.Text    `json:"name"`
	Description       pgtype.Text    `json:"description"`
	Parameters        []byte         `json:"parameters"`
	Result            []byte         `json:"result"`
	X                 pgtype.Float8  `json:"x"`
	Y                 pgtype.Float8  `json:"y"`
	Operation         pgtype.Text    `json:"operation"`
	StatusSet         bool           `json:"status_set"`
	Status            NullTaskStatus `json:"status"`
	ErrorSet          bool           `json:"error_set"`
	Error             pgtype.Text    `json:"error"`
	ConnectorNameSet  bool           `json:"connector_name_set"`
	ConnectorName     pgtype.Text    `json:"connector_name"`
	ConnectorIDSet    bool           `json:"connector_id_set"`
	ConnectorID       pgtype.Text    `json:"connector_id"`
	ConfigSet         bool           `json:"config_set"`
	Config            pgtype.Text    `json:"config"`
	PlaybookHistoryID pgtype.UUID    `json:"playbook_history_id"`
	TaskID            pgtype.UUID    `json:"task_id"`
}

func (q *Queries) UpdateTaskHistory(ctx context.Context, arg UpdateTaskHistoryParams) (TaskHistory, error) {
	row := q.db.QueryRow(ctx, updateTaskHistory,
		arg.Name,
		arg.Description,
		arg.Parameters,
		arg.Result,
		arg.X,
		arg.Y,
		arg.Operation,
		arg.StatusSet,
		arg.Status,
		arg.ErrorSet,
		arg.Error,
		arg.ConnectorNameSet,
		arg.ConnectorName,
		arg.ConnectorIDSet,
		arg.ConnectorID,
		arg.ConfigSet,
		arg.Config,
		arg.PlaybookHistoryID,
		arg.TaskID,
	)
	var i TaskHistory
	err := row.Scan(
		&i.ID,
		&i.PlaybookHistoryID,
		&i.TaskID,
		&i.Name,
		&i.Description,
		&i.Parameters,
		&i.Config,
		&i.X,
		&i.Y,
		&i.ConnectorName,
		&i.ConnectorID,
		&i.Operation,
		&i.Status,
		&i.DestinationIds,
		&i.Error,
		&i.Result,
		&i.TriggeredAt,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE task_history
SET status = $3
WHERE playbook_history_id = $1 AND task_id = $2
RETURNING id, playbook_history_id, task_id, name, description, parameters, config, x, y, connector_name, connector_id, operation, status, destination_ids, error, result, triggered_at
`

type UpdateTaskStatusParams struct {
	PlaybookHistoryID pgtype.UUID `json:"playbook_history_id"`
	TaskID            pgtype.UUID `json:"task_id"`
	Status            TaskStatus  `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (TaskHistory, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus, arg.PlaybookHistoryID, arg.TaskID, arg.Status)
	var i TaskHistory
	err := row.Scan(
		&i.ID,
		&i.PlaybookHistoryID,
		&i.TaskID,
		&i.Name,
		&i.Description,
		&i.Parameters,
		&i.Config,
		&i.X,
		&i.Y,
		&i.ConnectorName,
		&i.ConnectorID,
		&i.Operation,
		&i.Status,
		&i.DestinationIds,
		&i.Error,
		&i.Result,
		&i.TriggeredAt,
	)
	return i, err
}

const upsertTask = `-- name: UpsertTask :one
INSERT INTO tasks (playbook_id, name, description, parameters, config, connector_name, connector_id, operation, x, y)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (playbook_id, name) DO UPDATE
SET description = EXCLUDED.description,
    parameters = EXCLUDED.parameters,
    config = EXCLUDED.config,
    connector_name = EXCLUDED.connector_name,
    connector_id = EXCLUDED.connector_id,
    operation = EXCLUDED.operation,
    x = EXCLUDED.x,
    y = EXCLUDED.y,
    updated_at = NOW()
RETURNING id, playbook_id, name, description, parameters, config, x, y, connector_name, connector_id, operation, created_at, updated_at
`

type UpsertTaskParams struct {
	PlaybookID    pgtype.UUID   `json:"playbook_id"`
	Name          pgtype.Text   `json:"name"`
	Description   pgtype.Text   `json:"description"`
	Parameters    []byte        `json:"parameters"`
	Config        pgtype.Text   `json:"config"`
	ConnectorName pgtype.Text   `json:"connector_name"`
	ConnectorID   pgtype.Text   `json:"connector_id"`
	Operation     pgtype.Text   `json:"operation"`
	X             pgtype.Float8 `json:"x"`
	Y             pgtype.Float8 `json:"y"`
}

func (q *Queries) UpsertTask(ctx context.Context, arg UpsertTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, upsertTask,
		arg.PlaybookID,
		arg.Name,
		arg.Description,
		arg.Parameters,
		arg.Config,
		arg.ConnectorName,
		arg.ConnectorID,
		arg.Operation,
		arg.X,
		arg.Y,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.PlaybookID,
		&i.Name,
		&i.Description,
		&i.Parameters,
		&i.Config,
		&i.X,
		&i.Y,
		&i.ConnectorName,
		&i.ConnectorID,
		&i.Operation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
