// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, description) VALUES ($1, $2) RETURNING id, name, description, created_at, updated_at
`

type CreateTeamParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Name, arg.Description)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :execrows
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTeam, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTeamMembers = `-- name: DeleteTeamMembers :exec
DELETE FROM team_members WHERE team_id = $1
`

func (q *Queries) DeleteTeamMembers(ctx context.Context, teamID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeamMembers, teamID)
	return err
}

const getTeamById = `-- name: GetTeamById :one
SELECT id, name, description, created_at, updated_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeamById(ctx context.Context, id pgtype.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamById, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTeamMember = `-- name: InsertTeamMember :exec
INSERT INTO team_members (team_id, user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type InsertTeamMemberParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) InsertTeamMember(ctx context.Context, arg InsertTeamMemberParams) error {
	_, err := q.db.Exec(ctx, insertTeamMember, arg.TeamID, arg.UserID)
	return err
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET
    name = CASE
        WHEN $1::boolean THEN $2
        ELSE name
    END,
    description = CASE
        WHEN $3::boolean THEN $4
        ELSE description
    END,
    updated_at = NOW()
WHERE id = $5
RETURNING id, name, description, created_at, updated_at
`

type UpdateTeamParams struct {
	NameSet        bool        `json:"name_set"`
	Name           pgtype.Text `json:"name"`
	DescriptionSet bool        `json:"description_set"`
	Description    pgtype.Text `json:"description"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.NameSet,
		arg.Name,
		arg.DescriptionSet,
		arg.Description,
		arg.ID,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
