// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersWithRole = `-- name: CountUsersWithRole :one
SELECT COUNT(*) FROM users u
JOIN user_roles ur ON ur.user_id = u.id
JOIN roles r ON r.id = ur.role_id
WHERE r.name = $1
`

func (q *Queries) CountUsersWithRole(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersWithRole, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, email, password_hash, first_name, last_name,
    auth_provider, external_id, is_active
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, username, email, password_hash, first_name, last_name, auth_provider, external_id, is_active, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	PasswordHash pgtype.Text      `json:"password_hash"`
	FirstName    pgtype.Text      `json:"first_name"`
	LastName     pgtype.Text      `json:"last_name"`
	AuthProvider AuthProviderType `json:"auth_provider"`
	ExternalID   pgtype.Text      `json:"external_id"`
	IsActive     bool             `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.AuthProvider,
		arg.ExternalID,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.AuthProvider,
		&i.ExternalID,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, first_name, last_name, auth_provider, external_id, is_active, last_login_at, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.AuthProvider,
		&i.ExternalID,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByExternalId = `-- name: GetUserByExternalId :one
SELECT id, username, email, password_hash, first_name, last_name, auth_provider, external_id, is_active, last_login_at, created_at, updated_at FROM users WHERE auth_provider = $1 AND external_id = $2
`

type GetUserByExternalIdParams struct {
	AuthProvider AuthProviderType `json:"auth_provider"`
	ExternalID   pgtype.Text      `json:"external_id"`
}

func (q *Queries) GetUserByExternalId(ctx context.Context, arg GetUserByExternalIdParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByExternalId, arg.AuthProvider, arg.ExternalID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.AuthProvider,
		&i.ExternalID,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, email, password_hash, first_name, last_name, auth_provider, external_id, is_active, last_login_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.AuthProvider,
		&i.ExternalID,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, first_name, last_name, auth_provider, external_id, is_active, last_login_at, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.AuthProvider,
		&i.ExternalID,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = NOW() WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const touchUserLastLogin = `-- name: TouchUserLastLogin :exec
UPDATE users SET last_login_at = NOW() WHERE id = $1
`

func (q *Queries) TouchUserLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchUserLastLogin, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    email = CASE
        WHEN $1::boolean THEN $2
        ELSE email
    END,
    first_name = CASE
        WHEN $3::boolean THEN $4
        ELSE first_name
    END,
    last_name = CASE
        WHEN $5::boolean THEN $6
        ELSE last_name
    END,
    is_active = CASE
        WHEN $7::boolean THEN $8
        ELSE is_active
    END,
    updated_at = NOW()
WHERE id = $9
RETURNING id, username, email, password_hash, first_name, last_name, auth_provider, external_id, is_active, last_login_at, created_at, updated_at
`

type UpdateUserParams struct {
	EmailSet     bool        `json:"email_set"`
	Email        pgtype.Text `json:"email"`
	FirstNameSet bool        `json:"first_name_set"`
	FirstName    pgtype.Text `json:"first_name"`
	LastNameSet  bool        `json:"last_name_set"`
	LastName     pgtype.Text `json:"last_name"`
	IsActiveSet  bool        `json:"is_active_set"`
	IsActive     pgtype.Bool `json:"is_active"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.EmailSet,
		arg.Email,
		arg.FirstNameSet,
		arg.FirstName,
		arg.LastNameSet,
		arg.LastName,
		arg.IsActiveSet,
		arg.IsActive,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.AuthProvider,
		&i.ExternalID,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
