// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/edges (interfaces: EdgeService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/service_mock.go -package=mocks . EdgeService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/yuudev14/ytsoar/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockEdgeService is a mock of EdgeService interface.
type MockEdgeService struct {
	ctrl     *gomock.Controller
	recorder *MockEdgeServiceMockRecorder
	isgomock struct{}
}

// MockEdgeServiceMockRecorder is the mock recorder for MockEdgeService.
type MockEdgeServiceMockRecorder struct {
	mock *MockEdgeService
}

// NewMockEdgeService creates a new mock instance.
func NewMockEdgeService(ctrl *gomock.Controller) *MockEdgeService {
	mock := &MockEdgeService{ctrl: ctrl}
	mock.recorder = &MockEdgeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEdgeService) EXPECT() *MockEdgeServiceMockRecorder {
	return m.recorder
}

// DeleteAllPlaybookEdges mocks base method.
func (m *MockEdgeService) DeleteAllPlaybookEdges(ctx context.Context, playbookId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllPlaybookEdges", ctx, playbookId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllPlaybookEdges indicates an expected call of DeleteAllPlaybookEdges.
func (mr *MockEdgeServiceMockRecorder) DeleteAllPlaybookEdges(ctx, playbookId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllPlaybookEdges", reflect.TypeOf((*MockEdgeService)(nil).DeleteAllPlaybookEdges), ctx, playbookId)
}

// DeleteEdges mocks base method.
func (m *MockEdgeService) DeleteEdges(ctx context.Context, edgeIds []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEdges", ctx, edgeIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEdges indicates an expected call of DeleteEdges.
func (mr *MockEdgeServiceMockRecorder) DeleteEdges(ctx, edgeIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEdges", reflect.TypeOf((*MockEdgeService)(nil).DeleteEdges), ctx, edgeIds)
}

// GetEdgesByPlaybookId mocks base method.
func (m *MockEdgeService) GetEdgesByPlaybookId(ctx context.Context, playbookId string) ([]domain.ResponseEdges, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEdgesByPlaybookId", ctx, playbookId)
	ret0, _ := ret[0].([]domain.ResponseEdges)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEdgesByPlaybookId indicates an expected call of GetEdgesByPlaybookId.
func (mr *MockEdgeServiceMockRecorder) GetEdgesByPlaybookId(ctx, playbookId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEdgesByPlaybookId", reflect.TypeOf((*MockEdgeService)(nil).GetEdgesByPlaybookId), ctx, playbookId)
}

// InsertEdges mocks base method.
func (m *MockEdgeService) InsertEdges(ctx context.Context, edges []domain.Edges) ([]domain.Edges, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEdges", ctx, edges)
	ret0, _ := ret[0].([]domain.Edges)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertEdges indicates an expected call of InsertEdges.
func (mr *MockEdgeServiceMockRecorder) InsertEdges(ctx, edges any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEdges", reflect.TypeOf((*MockEdgeService)(nil).InsertEdges), ctx, edges)
}
