# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: connector_runtime.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'connector_runtime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63onnector_runtime.proto\"\xdb\x01\n\x17\x45xecuteOperationRequest\x12\x14\n\x0c\x63onnector_id\x18\x01 \x01(\t\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x18\n\x0b\x63onfig_name\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x17\n\x0fparameters_json\x18\x04 \x01(\t\x12\x12\n\nsteps_json\x18\x05 \x01(\t\x12\x1b\n\x13playbook_history_id\x18\x06 \x01(\t\x12\x0f\n\x07task_id\x18\x07 \x01(\t\x12\x12\n\ntimeout_ms\x18\x08 \x01(\rB\x0e\n\x0c_config_name\">\n\x18\x45xecuteOperationResponse\x12\x13\n\x0bresult_json\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x14\n\x12HealthCheckRequest\"!\n\x13HealthCheckResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\x99\x01\n\x10\x43onnectorRuntime\x12I\n\x10\x45xecuteOperation\x12\x18.ExecuteOperationRequest\x1a\x19.ExecuteOperationResponse\"\x00\x12:\n\x0bHealthCheck\x12\x13.HealthCheckRequest\x1a\x14.HealthCheckResponse\"\x00\x42\x33Z1github.com/yuudev14/ytsoar/gen/connectorruntimepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connector_runtime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/yuudev14/ytsoar/gen/connectorruntimepb'
  _globals['_EXECUTEOPERATIONREQUEST']._serialized_start=28
  _globals['_EXECUTEOPERATIONREQUEST']._serialized_end=247
  _globals['_EXECUTEOPERATIONRESPONSE']._serialized_start=249
  _globals['_EXECUTEOPERATIONRESPONSE']._serialized_end=311
  _globals['_HEALTHCHECKREQUEST']._serialized_start=313
  _globals['_HEALTHCHECKREQUEST']._serialized_end=333
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=335
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=368
  _globals['_CONNECTORRUNTIME']._serialized_start=371
  _globals['_CONNECTORRUNTIME']._serialized_end=524
# @@protoc_insertion_point(module_scope)
