# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: workflow.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'workflow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eworkflow.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x82\x01\n\x15WorkflowStatusPayload\x12\x1b\n\x13workflow_history_id\x18\x01 \x01(\t\x12\x13\n\x06status\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05\x65rror\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x0e\n\x06result\x18\x04 \x01(\tB\t\n\x07_statusB\x08\n\x06_error\"\xe2\x01\n\x0fWorkflowHistory\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0bworkflow_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x12\n\x05\x65rror\x18\x04 \x01(\tH\x00\x88\x01\x01\x12&\n\x06result\x18\x05 \x01(\x0b\x32\x16.google.protobuf.Value\x12\x30\n\x0ctriggered_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12&\n\x05\x65\x64ges\x18\x07 \x01(\x0b\x32\x17.google.protobuf.StructB\x08\n\x06_error2H\n\x08Workflow\x12<\n\x0eHandleWorkflow\x12\x16.WorkflowStatusPayload\x1a\x10.WorkflowHistory\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'workflow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORKFLOWSTATUSPAYLOAD']._serialized_start=82
  _globals['_WORKFLOWSTATUSPAYLOAD']._serialized_end=212
  _globals['_WORKFLOWHISTORY']._serialized_start=215
  _globals['_WORKFLOWHISTORY']._serialized_end=441
  _globals['_WORKFLOW']._serialized_start=443
  _globals['_WORKFLOW']._serialized_end=515
# @@protoc_insertion_point(module_scope)
