FROM golang:1.24-alpine

RUN apk add --no-cache git curl

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

RUN go install github.com/air-verse/air@latest

COPY . .

EXPOSE 8080

ENV GIN_MODE=debug

CMD ["air", "server", "--port", "8080", "--debug"]
