// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/playbooks (interfaces: PlaybookRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/repository_mock.go -package=mocks . PlaybookRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	sqlx "github.com/jmoiron/sqlx"
	playbooks "github.com/yuudev14/ytsoar/internal/application/playbooks"
	domain "github.com/yuudev14/ytsoar/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPlaybookRepository is a mock of PlaybookRepository interface.
type MockPlaybookRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPlaybookRepositoryMockRecorder
	isgomock struct{}
}

// MockPlaybookRepositoryMockRecorder is the mock recorder for MockPlaybookRepository.
type MockPlaybookRepositoryMockRecorder struct {
	mock *MockPlaybookRepository
}

// NewMockPlaybookRepository creates a new mock instance.
func NewMockPlaybookRepository(ctrl *gomock.Controller) *MockPlaybookRepository {
	mock := &MockPlaybookRepository{ctrl: ctrl}
	mock.recorder = &MockPlaybookRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlaybookRepository) EXPECT() *MockPlaybookRepositoryMockRecorder {
	return m.recorder
}

// CreatePlaybook mocks base method.
func (m *MockPlaybookRepository) CreatePlaybook(playbook playbooks.PlaybookPayload) (*domain.Playbooks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlaybook", playbook)
	ret0, _ := ret[0].(*domain.Playbooks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePlaybook indicates an expected call of CreatePlaybook.
func (mr *MockPlaybookRepositoryMockRecorder) CreatePlaybook(playbook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlaybook", reflect.TypeOf((*MockPlaybookRepository)(nil).CreatePlaybook), playbook)
}

// CreatePlaybookHistory mocks base method.
func (m *MockPlaybookRepository) CreatePlaybookHistory(tx *sqlx.Tx, id string, edges []domain.ResponseEdges) (*domain.PlaybookHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlaybookHistory", tx, id, edges)
	ret0, _ := ret[0].(*domain.PlaybookHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePlaybookHistory indicates an expected call of CreatePlaybookHistory.
func (mr *MockPlaybookRepositoryMockRecorder) CreatePlaybookHistory(tx, id, edges any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlaybookHistory", reflect.TypeOf((*MockPlaybookRepository)(nil).CreatePlaybookHistory), tx, id, edges)
}

// GetPlaybookById mocks base method.
func (m *MockPlaybookRepository) GetPlaybookById(id string) (*domain.Playbooks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookById", id)
	ret0, _ := ret[0].(*domain.Playbooks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookById indicates an expected call of GetPlaybookById.
func (mr *MockPlaybookRepositoryMockRecorder) GetPlaybookById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookById", reflect.TypeOf((*MockPlaybookRepository)(nil).GetPlaybookById), id)
}

// GetPlaybookGraphById mocks base method.
func (m *MockPlaybookRepository) GetPlaybookGraphById(id string) (*domain.PlaybookGraph, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookGraphById", id)
	ret0, _ := ret[0].(*domain.PlaybookGraph)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookGraphById indicates an expected call of GetPlaybookGraphById.
func (mr *MockPlaybookRepositoryMockRecorder) GetPlaybookGraphById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookGraphById", reflect.TypeOf((*MockPlaybookRepository)(nil).GetPlaybookGraphById), id)
}

// GetPlaybookHistory mocks base method.
func (m *MockPlaybookRepository) GetPlaybookHistory(offset, limit int, filter playbooks.PlaybookHistoryFilter) ([]domain.PlaybookHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookHistory", offset, limit, filter)
	ret0, _ := ret[0].([]domain.PlaybookHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookHistory indicates an expected call of GetPlaybookHistory.
func (mr *MockPlaybookRepositoryMockRecorder) GetPlaybookHistory(offset, limit, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookHistory", reflect.TypeOf((*MockPlaybookRepository)(nil).GetPlaybookHistory), offset, limit, filter)
}

// GetPlaybookHistoryById mocks base method.
func (m *MockPlaybookRepository) GetPlaybookHistoryById(playbookHistoryId uuid.UUID) (*domain.PlaybookHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookHistoryById", playbookHistoryId)
	ret0, _ := ret[0].(*domain.PlaybookHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookHistoryById indicates an expected call of GetPlaybookHistoryById.
func (mr *MockPlaybookRepositoryMockRecorder) GetPlaybookHistoryById(playbookHistoryId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookHistoryById", reflect.TypeOf((*MockPlaybookRepository)(nil).GetPlaybookHistoryById), playbookHistoryId)
}

// GetPlaybookHistoryCount mocks base method.
func (m *MockPlaybookRepository) GetPlaybookHistoryCount(filter playbooks.PlaybookHistoryFilter) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookHistoryCount", filter)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookHistoryCount indicates an expected call of GetPlaybookHistoryCount.
func (mr *MockPlaybookRepositoryMockRecorder) GetPlaybookHistoryCount(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookHistoryCount", reflect.TypeOf((*MockPlaybookRepository)(nil).GetPlaybookHistoryCount), filter)
}

// GetPlaybookTriggers mocks base method.
func (m *MockPlaybookRepository) GetPlaybookTriggers() ([]domain.PlaybookTriggers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookTriggers")
	ret0, _ := ret[0].([]domain.PlaybookTriggers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookTriggers indicates an expected call of GetPlaybookTriggers.
func (mr *MockPlaybookRepositoryMockRecorder) GetPlaybookTriggers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookTriggers", reflect.TypeOf((*MockPlaybookRepository)(nil).GetPlaybookTriggers))
}

// GetPlaybooks mocks base method.
func (m *MockPlaybookRepository) GetPlaybooks(offset, limit int, filter playbooks.PlaybookFilter) ([]domain.Playbooks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybooks", offset, limit, filter)
	ret0, _ := ret[0].([]domain.Playbooks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybooks indicates an expected call of GetPlaybooks.
func (mr *MockPlaybookRepositoryMockRecorder) GetPlaybooks(offset, limit, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybooks", reflect.TypeOf((*MockPlaybookRepository)(nil).GetPlaybooks), offset, limit, filter)
}

// GetPlaybooksCount mocks base method.
func (m *MockPlaybookRepository) GetPlaybooksCount(filter playbooks.PlaybookFilter) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybooksCount", filter)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybooksCount indicates an expected call of GetPlaybooksCount.
func (mr *MockPlaybookRepositoryMockRecorder) GetPlaybooksCount(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybooksCount", reflect.TypeOf((*MockPlaybookRepository)(nil).GetPlaybooksCount), filter)
}

// UpdatePlaybook mocks base method.
func (m *MockPlaybookRepository) UpdatePlaybook(id string, playbook playbooks.UpdatePlaybookData) (*domain.Playbooks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaybook", id, playbook)
	ret0, _ := ret[0].(*domain.Playbooks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlaybook indicates an expected call of UpdatePlaybook.
func (mr *MockPlaybookRepositoryMockRecorder) UpdatePlaybook(id, playbook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaybook", reflect.TypeOf((*MockPlaybookRepository)(nil).UpdatePlaybook), id, playbook)
}

// UpdatePlaybookHistory mocks base method.
func (m *MockPlaybookRepository) UpdatePlaybookHistory(playbookHistoryId string, playbookHistory playbooks.UpdatePlaybookHistoryData) (*domain.PlaybookHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaybookHistory", playbookHistoryId, playbookHistory)
	ret0, _ := ret[0].(*domain.PlaybookHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlaybookHistory indicates an expected call of UpdatePlaybookHistory.
func (mr *MockPlaybookRepositoryMockRecorder) UpdatePlaybookHistory(playbookHistoryId, playbookHistory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaybookHistory", reflect.TypeOf((*MockPlaybookRepository)(nil).UpdatePlaybookHistory), playbookHistoryId, playbookHistory)
}

// UpdatePlaybookHistoryStatus mocks base method.
func (m *MockPlaybookRepository) UpdatePlaybookHistoryStatus(playbookHistoryId, status string) (*domain.PlaybookHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaybookHistoryStatus", playbookHistoryId, status)
	ret0, _ := ret[0].(*domain.PlaybookHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlaybookHistoryStatus indicates an expected call of UpdatePlaybookHistoryStatus.
func (mr *MockPlaybookRepositoryMockRecorder) UpdatePlaybookHistoryStatus(playbookHistoryId, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaybookHistoryStatus", reflect.TypeOf((*MockPlaybookRepository)(nil).UpdatePlaybookHistoryStatus), playbookHistoryId, status)
}

// UpdatePlaybookTx mocks base method.
func (m *MockPlaybookRepository) UpdatePlaybookTx(tx *sqlx.Tx, id string, playbook playbooks.UpdatePlaybookData) (*domain.Playbooks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaybookTx", tx, id, playbook)
	ret0, _ := ret[0].(*domain.Playbooks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlaybookTx indicates an expected call of UpdatePlaybookTx.
func (mr *MockPlaybookRepositoryMockRecorder) UpdatePlaybookTx(tx, id, playbook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaybookTx", reflect.TypeOf((*MockPlaybookRepository)(nil).UpdatePlaybookTx), tx, id, playbook)
}
