// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/playbooks (interfaces: PlaybookService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/service_mock.go -package=mocks . PlaybookService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	sqlx "github.com/jmoiron/sqlx"
	playbooks "github.com/yuudev14/ytsoar/internal/application/playbooks"
	domain "github.com/yuudev14/ytsoar/internal/domain"
	types "github.com/yuudev14/ytsoar/internal/types"
	gomock "go.uber.org/mock/gomock"
)

// MockPlaybookService is a mock of PlaybookService interface.
type MockPlaybookService struct {
	ctrl     *gomock.Controller
	recorder *MockPlaybookServiceMockRecorder
	isgomock struct{}
}

// MockPlaybookServiceMockRecorder is the mock recorder for MockPlaybookService.
type MockPlaybookServiceMockRecorder struct {
	mock *MockPlaybookService
}

// NewMockPlaybookService creates a new mock instance.
func NewMockPlaybookService(ctrl *gomock.Controller) *MockPlaybookService {
	mock := &MockPlaybookService{ctrl: ctrl}
	mock.recorder = &MockPlaybookServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlaybookService) EXPECT() *MockPlaybookServiceMockRecorder {
	return m.recorder
}

// CreatePlaybook mocks base method.
func (m *MockPlaybookService) CreatePlaybook(workflow playbooks.PlaybookPayload) (*domain.Playbooks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlaybook", workflow)
	ret0, _ := ret[0].(*domain.Playbooks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePlaybook indicates an expected call of CreatePlaybook.
func (mr *MockPlaybookServiceMockRecorder) CreatePlaybook(workflow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlaybook", reflect.TypeOf((*MockPlaybookService)(nil).CreatePlaybook), workflow)
}

// CreatePlaybookHistory mocks base method.
func (m *MockPlaybookService) CreatePlaybookHistory(tx *sqlx.Tx, id string, edges []domain.ResponseEdges) (*domain.PlaybookHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlaybookHistory", tx, id, edges)
	ret0, _ := ret[0].(*domain.PlaybookHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePlaybookHistory indicates an expected call of CreatePlaybookHistory.
func (mr *MockPlaybookServiceMockRecorder) CreatePlaybookHistory(tx, id, edges any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlaybookHistory", reflect.TypeOf((*MockPlaybookService)(nil).CreatePlaybookHistory), tx, id, edges)
}

// GetPlaybookById mocks base method.
func (m *MockPlaybookService) GetPlaybookById(id string) (*domain.Playbooks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookById", id)
	ret0, _ := ret[0].(*domain.Playbooks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookById indicates an expected call of GetPlaybookById.
func (mr *MockPlaybookServiceMockRecorder) GetPlaybookById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookById", reflect.TypeOf((*MockPlaybookService)(nil).GetPlaybookById), id)
}

// GetPlaybookGraphById mocks base method.
func (m *MockPlaybookService) GetPlaybookGraphById(id string) (*domain.PlaybookGraph, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookGraphById", id)
	ret0, _ := ret[0].(*domain.PlaybookGraph)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookGraphById indicates an expected call of GetPlaybookGraphById.
func (mr *MockPlaybookServiceMockRecorder) GetPlaybookGraphById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookGraphById", reflect.TypeOf((*MockPlaybookService)(nil).GetPlaybookGraphById), id)
}

// GetPlaybookHistory mocks base method.
func (m *MockPlaybookService) GetPlaybookHistory(offset, limit int, filter playbooks.PlaybookHistoryFilter) ([]domain.PlaybookHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookHistory", offset, limit, filter)
	ret0, _ := ret[0].([]domain.PlaybookHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookHistory indicates an expected call of GetPlaybookHistory.
func (mr *MockPlaybookServiceMockRecorder) GetPlaybookHistory(offset, limit, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookHistory", reflect.TypeOf((*MockPlaybookService)(nil).GetPlaybookHistory), offset, limit, filter)
}

// GetPlaybookHistoryById mocks base method.
func (m *MockPlaybookService) GetPlaybookHistoryById(workflowHistoryId uuid.UUID) (*domain.PlaybookHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookHistoryById", workflowHistoryId)
	ret0, _ := ret[0].(*domain.PlaybookHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookHistoryById indicates an expected call of GetPlaybookHistoryById.
func (mr *MockPlaybookServiceMockRecorder) GetPlaybookHistoryById(workflowHistoryId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookHistoryById", reflect.TypeOf((*MockPlaybookService)(nil).GetPlaybookHistoryById), workflowHistoryId)
}

// GetPlaybookHistoryCount mocks base method.
func (m *MockPlaybookService) GetPlaybookHistoryCount(filter playbooks.PlaybookHistoryFilter) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookHistoryCount", filter)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookHistoryCount indicates an expected call of GetPlaybookHistoryCount.
func (mr *MockPlaybookServiceMockRecorder) GetPlaybookHistoryCount(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookHistoryCount", reflect.TypeOf((*MockPlaybookService)(nil).GetPlaybookHistoryCount), filter)
}

// GetPlaybookTriggers mocks base method.
func (m *MockPlaybookService) GetPlaybookTriggers() ([]domain.PlaybookTriggers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookTriggers")
	ret0, _ := ret[0].([]domain.PlaybookTriggers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookTriggers indicates an expected call of GetPlaybookTriggers.
func (mr *MockPlaybookServiceMockRecorder) GetPlaybookTriggers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookTriggers", reflect.TypeOf((*MockPlaybookService)(nil).GetPlaybookTriggers))
}

// GetPlaybooks mocks base method.
func (m *MockPlaybookService) GetPlaybooks(offset, limit int, filter playbooks.PlaybookFilter) ([]domain.Playbooks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybooks", offset, limit, filter)
	ret0, _ := ret[0].([]domain.Playbooks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybooks indicates an expected call of GetPlaybooks.
func (mr *MockPlaybookServiceMockRecorder) GetPlaybooks(offset, limit, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybooks", reflect.TypeOf((*MockPlaybookService)(nil).GetPlaybooks), offset, limit, filter)
}

// GetPlaybooksCount mocks base method.
func (m *MockPlaybookService) GetPlaybooksCount(filter playbooks.PlaybookFilter) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybooksCount", filter)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybooksCount indicates an expected call of GetPlaybooksCount.
func (mr *MockPlaybookServiceMockRecorder) GetPlaybooksCount(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybooksCount", reflect.TypeOf((*MockPlaybookService)(nil).GetPlaybooksCount), filter)
}

// GetPlaybooksData mocks base method.
func (m *MockPlaybookService) GetPlaybooksData(offset, limit int, filter playbooks.PlaybookFilter) (types.Entries[domain.Playbooks], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybooksData", offset, limit, filter)
	ret0, _ := ret[0].(types.Entries[domain.Playbooks])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybooksData indicates an expected call of GetPlaybooksData.
func (mr *MockPlaybookServiceMockRecorder) GetPlaybooksData(offset, limit, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybooksData", reflect.TypeOf((*MockPlaybookService)(nil).GetPlaybooksData), offset, limit, filter)
}

// GetPlaybooksHistoryData mocks base method.
func (m *MockPlaybookService) GetPlaybooksHistoryData(offset, limit int, filter playbooks.PlaybookHistoryFilter) (types.Entries[domain.PlaybookHistoryResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybooksHistoryData", offset, limit, filter)
	ret0, _ := ret[0].(types.Entries[domain.PlaybookHistoryResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybooksHistoryData indicates an expected call of GetPlaybooksHistoryData.
func (mr *MockPlaybookServiceMockRecorder) GetPlaybooksHistoryData(offset, limit, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybooksHistoryData", reflect.TypeOf((*MockPlaybookService)(nil).GetPlaybooksHistoryData), offset, limit, filter)
}

// UpdatePlaybook mocks base method.
func (m *MockPlaybookService) UpdatePlaybook(id string, workflow playbooks.UpdatePlaybookData) (*domain.Playbooks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaybook", id, workflow)
	ret0, _ := ret[0].(*domain.Playbooks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlaybook indicates an expected call of UpdatePlaybook.
func (mr *MockPlaybookServiceMockRecorder) UpdatePlaybook(id, workflow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaybook", reflect.TypeOf((*MockPlaybookService)(nil).UpdatePlaybook), id, workflow)
}

// UpdatePlaybookHistory mocks base method.
func (m *MockPlaybookService) UpdatePlaybookHistory(workflowHistoryId string, workflowHistory playbooks.UpdatePlaybookHistoryData) (*domain.PlaybookHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaybookHistory", workflowHistoryId, workflowHistory)
	ret0, _ := ret[0].(*domain.PlaybookHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlaybookHistory indicates an expected call of UpdatePlaybookHistory.
func (mr *MockPlaybookServiceMockRecorder) UpdatePlaybookHistory(workflowHistoryId, workflowHistory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaybookHistory", reflect.TypeOf((*MockPlaybookService)(nil).UpdatePlaybookHistory), workflowHistoryId, workflowHistory)
}

// UpdatePlaybookHistoryStatus mocks base method.
func (m *MockPlaybookService) UpdatePlaybookHistoryStatus(workflowHistoryId, status string) (*domain.PlaybookHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaybookHistoryStatus", workflowHistoryId, status)
	ret0, _ := ret[0].(*domain.PlaybookHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlaybookHistoryStatus indicates an expected call of UpdatePlaybookHistoryStatus.
func (mr *MockPlaybookServiceMockRecorder) UpdatePlaybookHistoryStatus(workflowHistoryId, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaybookHistoryStatus", reflect.TypeOf((*MockPlaybookService)(nil).UpdatePlaybookHistoryStatus), workflowHistoryId, status)
}

// UpdatePlaybookTx mocks base method.
func (m *MockPlaybookService) UpdatePlaybookTx(tx *sqlx.Tx, id string, workflow playbooks.UpdatePlaybookData) (*domain.Playbooks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaybookTx", tx, id, workflow)
	ret0, _ := ret[0].(*domain.Playbooks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlaybookTx indicates an expected call of UpdatePlaybookTx.
func (mr *MockPlaybookServiceMockRecorder) UpdatePlaybookTx(tx, id, workflow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaybookTx", reflect.TypeOf((*MockPlaybookService)(nil).UpdatePlaybookTx), tx, id, workflow)
}
