version: "3.9"
name: ytsoar
networks:
  ytsoar:
services:
  ytsoar_rabbitmq:
    image: rabbitmq:3-management
    container_name: ytsoar_rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - ytsoar
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  ytsoar_postgres:
    image: postgres:15
    container_name: ytsoar_postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ytsoar
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - ytsoar
    volumes:
      - postgres_data:/var/lib/postgresql/data
  ytsoar_worker:
    build:
      context: ../app/connectors-service
      dockerfile: Dockerfile.worker
    image: ytsoar/worker:latest
    container_name: ytsoar_worker
    volumes:
      - ../app/connectors-service:/app
    environment:
      - CELERY_BROKER=pyamqp://guest:guest@ytsoar_rabbitmq:5672
      - CELERY_BACKEND=db+postgresql://postgres:password@ytsoar_postgres:5432/ytsoar?sslmode=disable
      - MQ_URL=amqp://guest:guest@ytsoar_rabbitmq:5672
      - grpc_workflow_host=ytsoar_api:50051
    networks:
      - ytsoar
    depends_on:
      ytsoar_postgres:
        condition: service_healthy
      ytsoar_rabbitmq:
        condition: service_healthy
  ytsoar_connectors:
    build:
      context: ../app/connectors-service
      dockerfile: Dockerfile.dev
    image: ytsoar/connectors:latest
    container_name: ytsoar_connectors
    ports:
      - "8000:8000"
    volumes:
      - ../app/connectors-service:/app
    environment:
      - CELERY_BROKER=pyamqp://guest:guest@ytsoar_rabbitmq:5672
      - CELERY_BACKEND=db+postgresql://postgres:password@ytsoar_postgres:5432/ytsoar?sslmode=disable
      - MQ_URL=amqp://guest:guest@ytsoar_rabbitmq:5672
      - use_celery=true
      - grpc_workflow_host=ytsoar_api:50051
    networks:
      - ytsoar
    depends_on:
      ytsoar_postgres:
        condition: service_healthy
      ytsoar_rabbitmq:
        condition: service_healthy
  ytsoar_playbook_service:
    build:
      context: ../app/playbook_service
      dockerfile: Dockerfile.dev
    image: ytsoar/playbook-service:latest
    container_name: ytsoar_api
    ports:
      - "8080:8080"
    volumes:
      - ../app/playbook_service:/app
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=ytsoar_postgres
      - DB_PORT=5432
      - DB_NAME=ytsoar
      - MQ_USER=guest
      - MQ_PASSWORD=guest
      - MQ_HOST=ytsoar_rabbitmq
      - MQ_PORT=5672
      - AIR_POLL=true
      - AIR_WATCH_TMOUT=500ms
    networks:
      - ytsoar
    depends_on:
      ytsoar_postgres:
        condition: service_healthy
      ytsoar_rabbitmq:
        condition: service_healthy
  ytsoar_nginx:
    build: ../app/nginx
    container_name: ytsoar_nginx
    ports:
      - "9999:9999"
    volumes:
      - ../app/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    depends_on:
      - ytsoar_connectors
      - ytsoar_playbook_service
    networks:
      - ytsoar
volumes:
  postgres_data:
  rabbitmq_data:
