// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/incidents (interfaces: AlertTimeline)
//
// Generated by this command:
//
//	mockgen -destination=mocks/alert_timeline_mock.go -package=mocks . AlertTimeline
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/yuudev14/ytsoar/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAlertTimeline is a mock of AlertTimeline interface.
type MockAlertTimeline struct {
	ctrl     *gomock.Controller
	recorder *MockAlertTimelineMockRecorder
	isgomock struct{}
}

// MockAlertTimelineMockRecorder is the mock recorder for MockAlertTimeline.
type MockAlertTimelineMockRecorder struct {
	mock *MockAlertTimeline
}

// NewMockAlertTimeline creates a new mock instance.
func NewMockAlertTimeline(ctrl *gomock.Controller) *MockAlertTimeline {
	mock := &MockAlertTimeline{ctrl: ctrl}
	mock.recorder = &MockAlertTimelineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlertTimeline) EXPECT() *MockAlertTimelineMockRecorder {
	return m.recorder
}

// AppendAlertEvent mocks base method.
func (m *MockAlertTimeline) AppendAlertEvent(ctx context.Context, alertID uuid.UUID, eventType domain.EventType, actorID *uuid.UUID, body []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendAlertEvent", ctx, alertID, eventType, actorID, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendAlertEvent indicates an expected call of AppendAlertEvent.
func (mr *MockAlertTimelineMockRecorder) AppendAlertEvent(ctx, alertID, eventType, actorID, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendAlertEvent", reflect.TypeOf((*MockAlertTimeline)(nil).AppendAlertEvent), ctx, alertID, eventType, actorID, body)
}
