// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/incidents (interfaces: IncidentRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/repository_mock.go -package=mocks . IncidentRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	incidents "github.com/yuudev14/ytsoar/internal/application/incidents"
	domain "github.com/yuudev14/ytsoar/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIncidentRepository is a mock of IncidentRepository interface.
type MockIncidentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIncidentRepositoryMockRecorder
	isgomock struct{}
}

// MockIncidentRepositoryMockRecorder is the mock recorder for MockIncidentRepository.
type MockIncidentRepositoryMockRecorder struct {
	mock *MockIncidentRepository
}

// NewMockIncidentRepository creates a new mock instance.
func NewMockIncidentRepository(ctrl *gomock.Controller) *MockIncidentRepository {
	mock := &MockIncidentRepository{ctrl: ctrl}
	mock.recorder = &MockIncidentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIncidentRepository) EXPECT() *MockIncidentRepositoryMockRecorder {
	return m.recorder
}

// AddNote mocks base method.
func (m *MockIncidentRepository) AddNote(ctx context.Context, incidentID uuid.UUID, authorID *uuid.UUID, body string) (domain.IncidentNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNote", ctx, incidentID, authorID, body)
	ret0, _ := ret[0].(domain.IncidentNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddNote indicates an expected call of AddNote.
func (mr *MockIncidentRepositoryMockRecorder) AddNote(ctx, incidentID, authorID, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNote", reflect.TypeOf((*MockIncidentRepository)(nil).AddNote), ctx, incidentID, authorID, body)
}

// AppendEvent mocks base method.
func (m *MockIncidentRepository) AppendEvent(ctx context.Context, params incidents.AppendEventParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendEvent", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendEvent indicates an expected call of AppendEvent.
func (mr *MockIncidentRepositoryMockRecorder) AppendEvent(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendEvent", reflect.TypeOf((*MockIncidentRepository)(nil).AppendEvent), ctx, params)
}

// Count mocks base method.
func (m *MockIncidentRepository) Count(ctx context.Context, filter incidents.IncidentFilter) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filter)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockIncidentRepositoryMockRecorder) Count(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockIncidentRepository)(nil).Count), ctx, filter)
}

// Create mocks base method.
func (m *MockIncidentRepository) Create(ctx context.Context, params incidents.CreateParams) (domain.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(domain.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIncidentRepositoryMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIncidentRepository)(nil).Create), ctx, params)
}

// DeleteNote mocks base method.
func (m *MockIncidentRepository) DeleteNote(ctx context.Context, noteID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNote", ctx, noteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNote indicates an expected call of DeleteNote.
func (mr *MockIncidentRepositoryMockRecorder) DeleteNote(ctx, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MockIncidentRepository)(nil).DeleteNote), ctx, noteID)
}

// GetByID mocks base method.
func (m *MockIncidentRepository) GetByID(ctx context.Context, id uuid.UUID) (domain.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIncidentRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIncidentRepository)(nil).GetByID), ctx, id)
}

// GetDetail mocks base method.
func (m *MockIncidentRepository) GetDetail(ctx context.Context, id uuid.UUID) (incidents.IncidentDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetail", ctx, id)
	ret0, _ := ret[0].(incidents.IncidentDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetail indicates an expected call of GetDetail.
func (mr *MockIncidentRepositoryMockRecorder) GetDetail(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetail", reflect.TypeOf((*MockIncidentRepository)(nil).GetDetail), ctx, id)
}

// GetNote mocks base method.
func (m *MockIncidentRepository) GetNote(ctx context.Context, noteID uuid.UUID) (domain.IncidentNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNote", ctx, noteID)
	ret0, _ := ret[0].(domain.IncidentNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNote indicates an expected call of GetNote.
func (mr *MockIncidentRepositoryMockRecorder) GetNote(ctx, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNote", reflect.TypeOf((*MockIncidentRepository)(nil).GetNote), ctx, noteID)
}

// LinkAlert mocks base method.
func (m *MockIncidentRepository) LinkAlert(ctx context.Context, incidentID, alertID uuid.UUID, source domain.LinkSource) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkAlert", ctx, incidentID, alertID, source)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkAlert indicates an expected call of LinkAlert.
func (mr *MockIncidentRepositoryMockRecorder) LinkAlert(ctx, incidentID, alertID, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkAlert", reflect.TypeOf((*MockIncidentRepository)(nil).LinkAlert), ctx, incidentID, alertID, source)
}

// List mocks base method.
func (m *MockIncidentRepository) List(ctx context.Context, filter incidents.IncidentFilter) ([]incidents.IncidentListItem, *string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]incidents.IncidentListItem)
	ret1, _ := ret[1].(*string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockIncidentRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIncidentRepository)(nil).List), ctx, filter)
}

// ListNotes mocks base method.
func (m *MockIncidentRepository) ListNotes(ctx context.Context, incidentID uuid.UUID) ([]domain.IncidentNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotes", ctx, incidentID)
	ret0, _ := ret[0].([]domain.IncidentNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotes indicates an expected call of ListNotes.
func (mr *MockIncidentRepositoryMockRecorder) ListNotes(ctx, incidentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotes", reflect.TypeOf((*MockIncidentRepository)(nil).ListNotes), ctx, incidentID)
}

// Summary mocks base method.
func (m *MockIncidentRepository) Summary(ctx context.Context) (incidents.IncidentsSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summary", ctx)
	ret0, _ := ret[0].(incidents.IncidentsSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Summary indicates an expected call of Summary.
func (mr *MockIncidentRepositoryMockRecorder) Summary(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summary", reflect.TypeOf((*MockIncidentRepository)(nil).Summary), ctx)
}

// UnlinkAlert mocks base method.
func (m *MockIncidentRepository) UnlinkAlert(ctx context.Context, incidentID, alertID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkAlert", ctx, incidentID, alertID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkAlert indicates an expected call of UnlinkAlert.
func (mr *MockIncidentRepositoryMockRecorder) UnlinkAlert(ctx, incidentID, alertID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkAlert", reflect.TypeOf((*MockIncidentRepository)(nil).UnlinkAlert), ctx, incidentID, alertID)
}

// Update mocks base method.
func (m *MockIncidentRepository) Update(ctx context.Context, id uuid.UUID, params incidents.UpdateParams) (domain.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, params)
	ret0, _ := ret[0].(domain.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIncidentRepositoryMockRecorder) Update(ctx, id, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIncidentRepository)(nil).Update), ctx, id, params)
}

// UpdateNote mocks base method.
func (m *MockIncidentRepository) UpdateNote(ctx context.Context, noteID uuid.UUID, body string) (domain.IncidentNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNote", ctx, noteID, body)
	ret0, _ := ret[0].(domain.IncidentNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNote indicates an expected call of UpdateNote.
func (mr *MockIncidentRepositoryMockRecorder) UpdateNote(ctx, noteID, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNote", reflect.TypeOf((*MockIncidentRepository)(nil).UpdateNote), ctx, noteID, body)
}

// UpdateStatus mocks base method.
func (m *MockIncidentRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status domain.IncidentStatus) (domain.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(domain.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockIncidentRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockIncidentRepository)(nil).UpdateStatus), ctx, id, status)
}
