// Code generated by MockGen. DO NOT EDIT.
// Source: /home/yuudev14/Desktop/projects/workflow/app/workflow_service/internal/infra/mq/rabbitmq.go
//
// Generated by this command:
//
//	mockgen -source=/home/yuudev14/Desktop/projects/workflow/app/workflow_service/internal/infra/mq/rabbitmq.go -destination=/home/yuudev14/Desktop/projects/workflow/app/workflow_service/internal/infra/mq/mock/rabbitmq_mock.go
//

// Package mock_mq is a generated GoMock package.
package mock_mq

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTaskPubSub is a mock of TaskPubSub interface.
type MockTaskPubSub struct {
	ctrl     *gomock.Controller
	recorder *MockTaskPubSubMockRecorder
	isgomock struct{}
}

// MockTaskPubSubMockRecorder is the mock recorder for MockTaskPubSub.
type MockTaskPubSubMockRecorder struct {
	mock *MockTaskPubSub
}

// NewMockTaskPubSub creates a new mock instance.
func NewMockTaskPubSub(ctrl *gomock.Controller) *MockTaskPubSub {
	mock := &MockTaskPubSub{ctrl: ctrl}
	mock.recorder = &MockTaskPubSubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskPubSub) EXPECT() *MockTaskPubSubMockRecorder {
	return m.recorder
}

// SendMessage mocks base method.
func (m *MockTaskPubSub) SendMessage(message any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockTaskPubSubMockRecorder) SendMessage(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockTaskPubSub)(nil).SendMessage), message)
}
