// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/alerts (interfaces: IncidentLinker)
//
// Generated by this command:
//
//	mockgen -destination=mocks/incident_linker_mock.go -package=mocks . IncidentLinker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	alerts "github.com/yuudev14/ytsoar/internal/application/alerts"
	domain "github.com/yuudev14/ytsoar/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIncidentLinker is a mock of IncidentLinker interface.
type MockIncidentLinker struct {
	ctrl     *gomock.Controller
	recorder *MockIncidentLinkerMockRecorder
	isgomock struct{}
}

// MockIncidentLinkerMockRecorder is the mock recorder for MockIncidentLinker.
type MockIncidentLinkerMockRecorder struct {
	mock *MockIncidentLinker
}

// NewMockIncidentLinker creates a new mock instance.
func NewMockIncidentLinker(ctrl *gomock.Controller) *MockIncidentLinker {
	mock := &MockIncidentLinker{ctrl: ctrl}
	mock.recorder = &MockIncidentLinkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIncidentLinker) EXPECT() *MockIncidentLinkerMockRecorder {
	return m.recorder
}

// CreateForEscalation mocks base method.
func (m *MockIncidentLinker) CreateForEscalation(ctx context.Context, params alerts.EscalationParams) (domain.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateForEscalation", ctx, params)
	ret0, _ := ret[0].(domain.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateForEscalation indicates an expected call of CreateForEscalation.
func (mr *MockIncidentLinkerMockRecorder) CreateForEscalation(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateForEscalation", reflect.TypeOf((*MockIncidentLinker)(nil).CreateForEscalation), ctx, params)
}
