// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/alerts (interfaces: AlertRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/repository_mock.go -package=mocks . AlertRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	alerts "github.com/yuudev14/ytsoar/internal/application/alerts"
	domain "github.com/yuudev14/ytsoar/internal/domain"
	types "github.com/yuudev14/ytsoar/internal/types"
	gomock "go.uber.org/mock/gomock"
)

// MockAlertRepository is a mock of AlertRepository interface.
type MockAlertRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAlertRepositoryMockRecorder
	isgomock struct{}
}

// MockAlertRepositoryMockRecorder is the mock recorder for MockAlertRepository.
type MockAlertRepositoryMockRecorder struct {
	mock *MockAlertRepository
}

// NewMockAlertRepository creates a new mock instance.
func NewMockAlertRepository(ctrl *gomock.Controller) *MockAlertRepository {
	mock := &MockAlertRepository{ctrl: ctrl}
	mock.recorder = &MockAlertRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlertRepository) EXPECT() *MockAlertRepositoryMockRecorder {
	return m.recorder
}

// AddNote mocks base method.
func (m *MockAlertRepository) AddNote(ctx context.Context, alertID uuid.UUID, authorID *uuid.UUID, body string) (domain.AlertNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNote", ctx, alertID, authorID, body)
	ret0, _ := ret[0].(domain.AlertNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddNote indicates an expected call of AddNote.
func (mr *MockAlertRepositoryMockRecorder) AddNote(ctx, alertID, authorID, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNote", reflect.TypeOf((*MockAlertRepository)(nil).AddNote), ctx, alertID, authorID, body)
}

// AppendEvent mocks base method.
func (m *MockAlertRepository) AppendEvent(ctx context.Context, params alerts.AppendEventParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendEvent", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendEvent indicates an expected call of AppendEvent.
func (mr *MockAlertRepositoryMockRecorder) AppendEvent(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendEvent", reflect.TypeOf((*MockAlertRepository)(nil).AppendEvent), ctx, params)
}

// Count mocks base method.
func (m *MockAlertRepository) Count(ctx context.Context, filter alerts.AlertFilter) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filter)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockAlertRepositoryMockRecorder) Count(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockAlertRepository)(nil).Count), ctx, filter)
}

// DeleteNote mocks base method.
func (m *MockAlertRepository) DeleteNote(ctx context.Context, noteID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNote", ctx, noteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNote indicates an expected call of DeleteNote.
func (mr *MockAlertRepositoryMockRecorder) DeleteNote(ctx, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MockAlertRepository)(nil).DeleteNote), ctx, noteID)
}

// GetByID mocks base method.
func (m *MockAlertRepository) GetByID(ctx context.Context, id uuid.UUID) (domain.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAlertRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAlertRepository)(nil).GetByID), ctx, id)
}

// GetDetail mocks base method.
func (m *MockAlertRepository) GetDetail(ctx context.Context, id uuid.UUID) (alerts.AlertDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetail", ctx, id)
	ret0, _ := ret[0].(alerts.AlertDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetail indicates an expected call of GetDetail.
func (mr *MockAlertRepositoryMockRecorder) GetDetail(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetail", reflect.TypeOf((*MockAlertRepository)(nil).GetDetail), ctx, id)
}

// GetNote mocks base method.
func (m *MockAlertRepository) GetNote(ctx context.Context, noteID uuid.UUID) (domain.AlertNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNote", ctx, noteID)
	ret0, _ := ret[0].(domain.AlertNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNote indicates an expected call of GetNote.
func (mr *MockAlertRepositoryMockRecorder) GetNote(ctx, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNote", reflect.TypeOf((*MockAlertRepository)(nil).GetNote), ctx, noteID)
}

// List mocks base method.
func (m *MockAlertRepository) List(ctx context.Context, filter alerts.AlertFilter) ([]alerts.AlertListItem, *string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]alerts.AlertListItem)
	ret1, _ := ret[1].(*string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockAlertRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAlertRepository)(nil).List), ctx, filter)
}

// ListNotes mocks base method.
func (m *MockAlertRepository) ListNotes(ctx context.Context, alertID uuid.UUID) ([]domain.AlertNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotes", ctx, alertID)
	ret0, _ := ret[0].([]domain.AlertNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotes indicates an expected call of ListNotes.
func (mr *MockAlertRepositoryMockRecorder) ListNotes(ctx, alertID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotes", reflect.TypeOf((*MockAlertRepository)(nil).ListNotes), ctx, alertID)
}

// Summary mocks base method.
func (m *MockAlertRepository) Summary(ctx context.Context, rng types.ResolvedRange) (alerts.AlertsSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summary", ctx, rng)
	ret0, _ := ret[0].(alerts.AlertsSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Summary indicates an expected call of Summary.
func (mr *MockAlertRepositoryMockRecorder) Summary(ctx, rng any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summary", reflect.TypeOf((*MockAlertRepository)(nil).Summary), ctx, rng)
}

// Update mocks base method.
func (m *MockAlertRepository) Update(ctx context.Context, id uuid.UUID, params alerts.UpdateParams) (domain.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, params)
	ret0, _ := ret[0].(domain.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAlertRepositoryMockRecorder) Update(ctx, id, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAlertRepository)(nil).Update), ctx, id, params)
}

// UpdateNote mocks base method.
func (m *MockAlertRepository) UpdateNote(ctx context.Context, noteID uuid.UUID, body string) (domain.AlertNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNote", ctx, noteID, body)
	ret0, _ := ret[0].(domain.AlertNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNote indicates an expected call of UpdateNote.
func (mr *MockAlertRepositoryMockRecorder) UpdateNote(ctx, noteID, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNote", reflect.TypeOf((*MockAlertRepository)(nil).UpdateNote), ctx, noteID, body)
}

// UpdateStatus mocks base method.
func (m *MockAlertRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status domain.AlertStatus, closureNote *string) (domain.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status, closureNote)
	ret0, _ := ret[0].(domain.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockAlertRepositoryMockRecorder) UpdateStatus(ctx, id, status, closureNote any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockAlertRepository)(nil).UpdateStatus), ctx, id, status, closureNote)
}

// Upsert mocks base method.
func (m *MockAlertRepository) Upsert(ctx context.Context, params alerts.UpsertParams) (domain.Alert, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, params)
	ret0, _ := ret[0].(domain.Alert)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Upsert indicates an expected call of Upsert.
func (mr *MockAlertRepositoryMockRecorder) Upsert(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockAlertRepository)(nil).Upsert), ctx, params)
}
