import { Alert, AlertsSummary } from "./alerts.schema";

export const ALERTS: Alert[] = [
  {
    id: "a-1",
    title: "Suspicious PowerShell execution on WIN-DESKTOP-04",
    source: "EDR",
    sourceKind: "edr",
    severity: "critical",
    status: "investigating",
    assignee: "n.reyes",
    age: "2m",
    reporter: "CrowdStrike EDR",
    linkedRun: { playbook: "Malware Sandbox Detonation", outcome: "success" },
    fields: [
      { k: "Host", v: "WIN-DESKTOP-04" },
      { k: "User", v: "j.tan" },
      { k: "ATT&CK technique", v: "T1059.001" },
      { k: "First seen", v: "14:26:38" },
      { k: "Last seen", v: "14:26:41" },
      { k: "Source", v: "crowdstrike-edr" },
    ],
    payload: {
      host: "WIN-DESKTOP-04",
      process: "powershell.exe",
      parent_process: "outlook.exe",
      technique: "T1059.001",
      encoded_cmd: true,
      command_line: "-enc JAB...",
    },
    timeline: [
      { title: "Alert received from CrowdStrike EDR", detail: "14:26:38", tone: "rose" },
      {
        title: "Malware Sandbox Detonation triggered automatically",
        detail: '14:26:41 · matched rule "edr-critical-auto-run"',
        tone: "signal",
      },
      {
        title: "Detonation complete — score 91/100, host quarantined",
        detail: "14:28:52 · 2m 11s runtime",
        tone: "moss",
      },
    ],
    relatedAlerts: [
      { title: "Registry persistence attempt", age: "6h ago" },
      { title: "Unsigned binary execution", age: "1d ago" },
    ],
    tags: ["finance-subnet", "t1059.001"],
  },
  {
    id: "a-2",
    title: "Multiple failed MFA attempts — jdoe@corp.com",
    source: "Identity provider",
    sourceKind: "identity",
    severity: "high",
    status: "investigating",
    assignee: null,
    age: "6m",
    reporter: "Okta",
    linkedRun: { playbook: "Suspicious Login Response", outcome: "running" },
    payload: { user: "jdoe@corp.com", attempts: 7, geo: "impossible-travel" },
    tags: ["identity"],
  },
  {
    id: "a-3",
    title: "Outbound connection to known C2 IP",
    source: "IDS/firewall",
    sourceKind: "firewall",
    severity: "critical",
    status: "closed",
    assignee: "n.reyes",
    age: "41m",
    reporter: "Palo Alto",
    linkedRun: { playbook: "IOC Enrichment & Block", outcome: "failed" },
    payload: { dst_ip: "203.0.113.44", proto: "tcp", bytes: 148230 },
    tags: ["c2-beacon", "finance-subnet"],
  },
  {
    id: "a-4",
    title: "Phishing email reported by user",
    source: "Email gateway",
    sourceKind: "email",
    severity: "medium",
    status: "resolved",
    assignee: "takakiiiyuuu",
    age: "18m",
    reporter: "Proofpoint",
    linkedRun: { playbook: "Phishing Email Triage", outcome: "success" },
    payload: { sender: "payroll@corp-secure.top", verdict: "malicious" },
    tags: ["phishing"],
  },
  {
    id: "a-5",
    title: "Unusual data exfiltration volume — 4.2 GB",
    source: "DLP",
    sourceKind: "dlp",
    severity: "low",
    status: "new",
    assignee: null,
    age: "1h",
    reporter: "Forcepoint",
    linkedRun: null,
    payload: { volume_gb: 4.2, destination: "personal-drive.example" },
    tags: ["dlp"],
  },
];

export const ALERTS_SUMMARY: AlertsSummary = {
  total: 47,
  bySeverity: [
    { severity: "critical", count: 5 },
    { severity: "high", count: 14 },
    { severity: "medium", count: 22 },
    { severity: "low", count: 6 },
  ],
  bySource: [
    { label: "EDR", count: 17 },
    { label: "Identity provider", count: 12 },
    { label: "Email gateway", count: 9 },
    { label: "Firewall / IDS", count: 6 },
    { label: "DLP", count: 3 },
  ],
  topPlaybooks: [
    { label: "Slack Notify", successRate: 96 },
    { label: "Phishing Triage", successRate: 91 },
    { label: "IOC Enrichment", successRate: 88 },
    { label: "Login Response", successRate: 67 },
  ],
  volume: [78, 74, 68, 72, 60, 64, 50, 55, 40, 46, 30, 36, 22, 26, 14].map(
    (v) => 100 - v
  ),
};
