// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/contracts (interfaces: TaskPublisher)
//
// Generated by this command:
//
//	mockgen -destination=mocks/task_publisher_mock.go -package=mocks . TaskPublisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTaskPublisher is a mock of TaskPublisher interface.
type MockTaskPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockTaskPublisherMockRecorder
	isgomock struct{}
}

// MockTaskPublisherMockRecorder is the mock recorder for MockTaskPublisher.
type MockTaskPublisherMockRecorder struct {
	mock *MockTaskPublisher
}

// NewMockTaskPublisher creates a new mock instance.
func NewMockTaskPublisher(ctrl *gomock.Controller) *MockTaskPublisher {
	mock := &MockTaskPublisher{ctrl: ctrl}
	mock.recorder = &MockTaskPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskPublisher) EXPECT() *MockTaskPublisherMockRecorder {
	return m.recorder
}

// SendMessage mocks base method.
func (m *MockTaskPublisher) SendMessage(message any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockTaskPublisherMockRecorder) SendMessage(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockTaskPublisher)(nil).SendMessage), message)
}
