// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/edges (interfaces: EdgeRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/repository_mock.go -package=mocks . EdgeRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	sqlx "github.com/jmoiron/sqlx"
	domain "github.com/yuudev14/ytsoar/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockEdgeRepository is a mock of EdgeRepository interface.
type MockEdgeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEdgeRepositoryMockRecorder
	isgomock struct{}
}

// MockEdgeRepositoryMockRecorder is the mock recorder for MockEdgeRepository.
type MockEdgeRepositoryMockRecorder struct {
	mock *MockEdgeRepository
}

// NewMockEdgeRepository creates a new mock instance.
func NewMockEdgeRepository(ctrl *gomock.Controller) *MockEdgeRepository {
	mock := &MockEdgeRepository{ctrl: ctrl}
	mock.recorder = &MockEdgeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEdgeRepository) EXPECT() *MockEdgeRepositoryMockRecorder {
	return m.recorder
}

// DeleteAllPlaybookEdges mocks base method.
func (m *MockEdgeRepository) DeleteAllPlaybookEdges(tx *sqlx.Tx, playbookId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllPlaybookEdges", tx, playbookId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllPlaybookEdges indicates an expected call of DeleteAllPlaybookEdges.
func (mr *MockEdgeRepositoryMockRecorder) DeleteAllPlaybookEdges(tx, playbookId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllPlaybookEdges", reflect.TypeOf((*MockEdgeRepository)(nil).DeleteAllPlaybookEdges), tx, playbookId)
}

// DeleteEdges mocks base method.
func (m *MockEdgeRepository) DeleteEdges(tx *sqlx.Tx, edgeIds []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEdges", tx, edgeIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEdges indicates an expected call of DeleteEdges.
func (mr *MockEdgeRepositoryMockRecorder) DeleteEdges(tx, edgeIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEdges", reflect.TypeOf((*MockEdgeRepository)(nil).DeleteEdges), tx, edgeIds)
}

// GetEdgesByPlaybookId mocks base method.
func (m *MockEdgeRepository) GetEdgesByPlaybookId(playbookId string) ([]domain.ResponseEdges, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEdgesByPlaybookId", playbookId)
	ret0, _ := ret[0].([]domain.ResponseEdges)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEdgesByPlaybookId indicates an expected call of GetEdgesByPlaybookId.
func (mr *MockEdgeRepositoryMockRecorder) GetEdgesByPlaybookId(playbookId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEdgesByPlaybookId", reflect.TypeOf((*MockEdgeRepository)(nil).GetEdgesByPlaybookId), playbookId)
}

// InsertEdges mocks base method.
func (m *MockEdgeRepository) InsertEdges(tx *sqlx.Tx, edges []domain.Edges) ([]domain.Edges, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEdges", tx, edges)
	ret0, _ := ret[0].([]domain.Edges)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertEdges indicates an expected call of InsertEdges.
func (mr *MockEdgeRepositoryMockRecorder) InsertEdges(tx, edges any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEdges", reflect.TypeOf((*MockEdgeRepository)(nil).InsertEdges), tx, edges)
}
