// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/orchestrator/workflows/workflow_application_service.go
//
// Generated by this command:
//
//	mockgen -source=./internal/orchestrator/workflows/workflow_application_service.go -destination=./internal/orchestrator/workflows/mocks/workflow_application_service_mock.go
//

// Package mock_workflow_application is a generated GoMock package.
package mock_workflow_application

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	sqlx "github.com/jmoiron/sqlx"
	edges "github.com/yuudev14-workflow/workflow-service/internal/edges"
	workflow_application "github.com/yuudev14-workflow/workflow-service/internal/orchestrator/workflows"
	tasks "github.com/yuudev14-workflow/workflow-service/internal/tasks"
	workflows "github.com/yuudev14-workflow/workflow-service/internal/workflows"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkflowApplicationService is a mock of WorkflowApplicationService interface.
type MockWorkflowApplicationService struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowApplicationServiceMockRecorder
	isgomock struct{}
}

// MockWorkflowApplicationServiceMockRecorder is the mock recorder for MockWorkflowApplicationService.
type MockWorkflowApplicationServiceMockRecorder struct {
	mock *MockWorkflowApplicationService
}

// NewMockWorkflowApplicationService creates a new mock instance.
func NewMockWorkflowApplicationService(ctrl *gomock.Controller) *MockWorkflowApplicationService {
	mock := &MockWorkflowApplicationService{ctrl: ctrl}
	mock.recorder = &MockWorkflowApplicationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowApplicationService) EXPECT() *MockWorkflowApplicationServiceMockRecorder {
	return m.recorder
}

// DeleteEdges mocks base method.
func (m *MockWorkflowApplicationService) DeleteEdges(tx *sqlx.Tx, workflowUUID uuid.UUID, arg2 map[string][]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEdges", tx, workflowUUID, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEdges indicates an expected call of DeleteEdges.
func (mr *MockWorkflowApplicationServiceMockRecorder) DeleteEdges(tx, workflowUUID, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEdges", reflect.TypeOf((*MockWorkflowApplicationService)(nil).DeleteEdges), tx, workflowUUID, arg2)
}

// DeleteTasks mocks base method.
func (m *MockWorkflowApplicationService) DeleteTasks(tx *sqlx.Tx, workflowUUID uuid.UUID, nodes []tasks.TaskPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTasks", tx, workflowUUID, nodes)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTasks indicates an expected call of DeleteTasks.
func (mr *MockWorkflowApplicationServiceMockRecorder) DeleteTasks(tx, workflowUUID, nodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTasks", reflect.TypeOf((*MockWorkflowApplicationService)(nil).DeleteTasks), tx, workflowUUID, nodes)
}

// InsertEdges mocks base method.
func (m *MockWorkflowApplicationService) InsertEdges(tx *sqlx.Tx, workflowUUID uuid.UUID, arg2 map[string][]string, arg3 []tasks.Tasks, handles *map[string]map[string]edges.EdgeHandle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEdges", tx, workflowUUID, arg2, arg3, handles)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertEdges indicates an expected call of InsertEdges.
func (mr *MockWorkflowApplicationServiceMockRecorder) InsertEdges(tx, workflowUUID, arg2, arg3, handles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEdges", reflect.TypeOf((*MockWorkflowApplicationService)(nil).InsertEdges), tx, workflowUUID, arg2, arg3, handles)
}

// PrepareWorkflowMessage mocks base method.
func (m *MockWorkflowApplicationService) PrepareWorkflowMessage(arg0 []tasks.Tasks, arg1 []edges.ResponseEdges) (map[string]tasks.Tasks, map[string][]string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareWorkflowMessage", arg0, arg1)
	ret0, _ := ret[0].(map[string]tasks.Tasks)
	ret1, _ := ret[1].(map[string][]string)
	return ret0, ret1
}

// PrepareWorkflowMessage indicates an expected call of PrepareWorkflowMessage.
func (mr *MockWorkflowApplicationServiceMockRecorder) PrepareWorkflowMessage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareWorkflowMessage", reflect.TypeOf((*MockWorkflowApplicationService)(nil).PrepareWorkflowMessage), arg0, arg1)
}

// TriggerWorkflow mocks base method.
func (m *MockWorkflowApplicationService) TriggerWorkflow(workflowId string) (*workflow_application.TaskMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerWorkflow", workflowId)
	ret0, _ := ret[0].(*workflow_application.TaskMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerWorkflow indicates an expected call of TriggerWorkflow.
func (mr *MockWorkflowApplicationServiceMockRecorder) TriggerWorkflow(workflowId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerWorkflow", reflect.TypeOf((*MockWorkflowApplicationService)(nil).TriggerWorkflow), workflowId)
}

// UpdateWorkflowTasks mocks base method.
func (m *MockWorkflowApplicationService) UpdateWorkflowTasks(workflowId string, body tasks.UpdateWorkflowtasks) (*workflows.WorkflowsGraph, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkflowTasks", workflowId, body)
	ret0, _ := ret[0].(*workflows.WorkflowsGraph)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWorkflowTasks indicates an expected call of UpdateWorkflowTasks.
func (mr *MockWorkflowApplicationServiceMockRecorder) UpdateWorkflowTasks(workflowId, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkflowTasks", reflect.TypeOf((*MockWorkflowApplicationService)(nil).UpdateWorkflowTasks), workflowId, body)
}

// UpsertTasks mocks base method.
func (m *MockWorkflowApplicationService) UpsertTasks(tx *sqlx.Tx, workflowUUID uuid.UUID, nodes []tasks.TaskPayload) ([]tasks.Tasks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTasks", tx, workflowUUID, nodes)
	ret0, _ := ret[0].([]tasks.Tasks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertTasks indicates an expected call of UpsertTasks.
func (mr *MockWorkflowApplicationServiceMockRecorder) UpsertTasks(tx, workflowUUID, nodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTasks", reflect.TypeOf((*MockWorkflowApplicationService)(nil).UpsertTasks), tx, workflowUUID, nodes)
}
