// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/workflow_service/internal/tasks/repository.go
//
// Generated by this command:
//
//	mockgen -source=./app/workflow_service/internal/tasks/repository.go -destination=./app/workflow_service/internal/tasks/mocks/repository_mock.go
//

// Package mock_tasks is a generated GoMock package.
package mock_tasks

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	sqlx "github.com/jmoiron/sqlx"
	tasks "github.com/yuudev14-workflow/workflow-service/internal/tasks"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskRepository is a mock of TaskRepository interface.
type MockTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepositoryMockRecorder
	isgomock struct{}
}

// MockTaskRepositoryMockRecorder is the mock recorder for MockTaskRepository.
type MockTaskRepositoryMockRecorder struct {
	mock *MockTaskRepository
}

// NewMockTaskRepository creates a new mock instance.
func NewMockTaskRepository(ctrl *gomock.Controller) *MockTaskRepository {
	mock := &MockTaskRepository{ctrl: ctrl}
	mock.recorder = &MockTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepository) EXPECT() *MockTaskRepositoryMockRecorder {
	return m.recorder
}

// CreateTaskHistory mocks base method.
func (m *MockTaskRepository) CreateTaskHistory(tx *sqlx.Tx, workflowHistoryId string, arg2 []tasks.Tasks, graph map[uuid.UUID][]uuid.UUID) ([]tasks.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTaskHistory", tx, workflowHistoryId, arg2, graph)
	ret0, _ := ret[0].([]tasks.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTaskHistory indicates an expected call of CreateTaskHistory.
func (mr *MockTaskRepositoryMockRecorder) CreateTaskHistory(tx, workflowHistoryId, arg2, graph any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTaskHistory", reflect.TypeOf((*MockTaskRepository)(nil).CreateTaskHistory), tx, workflowHistoryId, arg2, graph)
}

// DeleteTasks mocks base method.
func (m *MockTaskRepository) DeleteTasks(tx *sqlx.Tx, taskIds []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTasks", tx, taskIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTasks indicates an expected call of DeleteTasks.
func (mr *MockTaskRepositoryMockRecorder) DeleteTasks(tx, taskIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTasks", reflect.TypeOf((*MockTaskRepository)(nil).DeleteTasks), tx, taskIds)
}

// GetTaskHistoryByWorkflowHistoryId mocks base method.
func (m *MockTaskRepository) GetTaskHistoryByWorkflowHistoryId(id string, filter tasks.TaskHistoryFilter) ([]tasks.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskHistoryByWorkflowHistoryId", id, filter)
	ret0, _ := ret[0].([]tasks.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskHistoryByWorkflowHistoryId indicates an expected call of GetTaskHistoryByWorkflowHistoryId.
func (mr *MockTaskRepositoryMockRecorder) GetTaskHistoryByWorkflowHistoryId(id, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskHistoryByWorkflowHistoryId", reflect.TypeOf((*MockTaskRepository)(nil).GetTaskHistoryByWorkflowHistoryId), id, filter)
}

// GetTaskHistoryCount mocks base method.
func (m *MockTaskRepository) GetTaskHistoryCount(filter tasks.TaskHistoryFilter) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskHistoryCount", filter)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskHistoryCount indicates an expected call of GetTaskHistoryCount.
func (mr *MockTaskRepositoryMockRecorder) GetTaskHistoryCount(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskHistoryCount", reflect.TypeOf((*MockTaskRepository)(nil).GetTaskHistoryCount), filter)
}

// GetTasksByWorkflowId mocks base method.
func (m *MockTaskRepository) GetTasksByWorkflowId(workflowId string) []tasks.Tasks {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByWorkflowId", workflowId)
	ret0, _ := ret[0].([]tasks.Tasks)
	return ret0
}

// GetTasksByWorkflowId indicates an expected call of GetTasksByWorkflowId.
func (mr *MockTaskRepositoryMockRecorder) GetTasksByWorkflowId(workflowId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByWorkflowId", reflect.TypeOf((*MockTaskRepository)(nil).GetTasksByWorkflowId), workflowId)
}

// UpdateTaskHistory mocks base method.
func (m *MockTaskRepository) UpdateTaskHistory(workflowHistoryId, taskId string, taskHistory tasks.UpdateTaskHistoryData) (*tasks.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskHistory", workflowHistoryId, taskId, taskHistory)
	ret0, _ := ret[0].(*tasks.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskHistory indicates an expected call of UpdateTaskHistory.
func (mr *MockTaskRepositoryMockRecorder) UpdateTaskHistory(workflowHistoryId, taskId, taskHistory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskHistory", reflect.TypeOf((*MockTaskRepository)(nil).UpdateTaskHistory), workflowHistoryId, taskId, taskHistory)
}

// UpdateTaskStatus mocks base method.
func (m *MockTaskRepository) UpdateTaskStatus(workflowHistoryId, taskId, status string) (*tasks.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatus", workflowHistoryId, taskId, status)
	ret0, _ := ret[0].(*tasks.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskStatus indicates an expected call of UpdateTaskStatus.
func (mr *MockTaskRepositoryMockRecorder) UpdateTaskStatus(workflowHistoryId, taskId, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatus", reflect.TypeOf((*MockTaskRepository)(nil).UpdateTaskStatus), workflowHistoryId, taskId, status)
}

// UpsertTasks mocks base method.
func (m *MockTaskRepository) UpsertTasks(tx *sqlx.Tx, workflowId uuid.UUID, arg2 []tasks.Tasks) ([]tasks.Tasks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTasks", tx, workflowId, arg2)
	ret0, _ := ret[0].([]tasks.Tasks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertTasks indicates an expected call of UpsertTasks.
func (mr *MockTaskRepositoryMockRecorder) UpsertTasks(tx, workflowId, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTasks", reflect.TypeOf((*MockTaskRepository)(nil).UpsertTasks), tx, workflowId, arg2)
}
