// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/workflow_service/internal/tasks/service.go
//
// Generated by this command:
//
//	mockgen -source=./app/workflow_service/internal/tasks/service.go -destination=./app/workflow_service/internal/tasks/mocks/service_mock.go
//

// Package mock_tasks is a generated GoMock package.
package mock_tasks

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	sqlx "github.com/jmoiron/sqlx"
	tasks "github.com/yuudev14-workflow/workflow-service/internal/tasks"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskService is a mock of TaskService interface.
type MockTaskService struct {
	ctrl     *gomock.Controller
	recorder *MockTaskServiceMockRecorder
	isgomock struct{}
}

// MockTaskServiceMockRecorder is the mock recorder for MockTaskService.
type MockTaskServiceMockRecorder struct {
	mock *MockTaskService
}

// NewMockTaskService creates a new mock instance.
func NewMockTaskService(ctrl *gomock.Controller) *MockTaskService {
	mock := &MockTaskService{ctrl: ctrl}
	mock.recorder = &MockTaskServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskService) EXPECT() *MockTaskServiceMockRecorder {
	return m.recorder
}

// CreateTaskHistory mocks base method.
func (m *MockTaskService) CreateTaskHistory(tx *sqlx.Tx, workflowHistoryId string, arg2 []tasks.Tasks, graph map[uuid.UUID][]uuid.UUID) ([]tasks.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTaskHistory", tx, workflowHistoryId, arg2, graph)
	ret0, _ := ret[0].([]tasks.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTaskHistory indicates an expected call of CreateTaskHistory.
func (mr *MockTaskServiceMockRecorder) CreateTaskHistory(tx, workflowHistoryId, arg2, graph any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTaskHistory", reflect.TypeOf((*MockTaskService)(nil).CreateTaskHistory), tx, workflowHistoryId, arg2, graph)
}

// DeleteTasks mocks base method.
func (m *MockTaskService) DeleteTasks(tx *sqlx.Tx, taskIds []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTasks", tx, taskIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTasks indicates an expected call of DeleteTasks.
func (mr *MockTaskServiceMockRecorder) DeleteTasks(tx, taskIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTasks", reflect.TypeOf((*MockTaskService)(nil).DeleteTasks), tx, taskIds)
}

// GetTaskHistoryByWorkflowHistoryId mocks base method.
func (m *MockTaskService) GetTaskHistoryByWorkflowHistoryId(id string, filter tasks.TaskHistoryFilter) ([]tasks.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskHistoryByWorkflowHistoryId", id, filter)
	ret0, _ := ret[0].([]tasks.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskHistoryByWorkflowHistoryId indicates an expected call of GetTaskHistoryByWorkflowHistoryId.
func (mr *MockTaskServiceMockRecorder) GetTaskHistoryByWorkflowHistoryId(id, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskHistoryByWorkflowHistoryId", reflect.TypeOf((*MockTaskService)(nil).GetTaskHistoryByWorkflowHistoryId), id, filter)
}

// GetTaskHistoryCount mocks base method.
func (m *MockTaskService) GetTaskHistoryCount(filter tasks.TaskHistoryFilter) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskHistoryCount", filter)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskHistoryCount indicates an expected call of GetTaskHistoryCount.
func (mr *MockTaskServiceMockRecorder) GetTaskHistoryCount(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskHistoryCount", reflect.TypeOf((*MockTaskService)(nil).GetTaskHistoryCount), filter)
}

// GetTasksByWorkflowId mocks base method.
func (m *MockTaskService) GetTasksByWorkflowId(workflowId string) ([]tasks.Tasks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByWorkflowId", workflowId)
	ret0, _ := ret[0].([]tasks.Tasks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByWorkflowId indicates an expected call of GetTasksByWorkflowId.
func (mr *MockTaskServiceMockRecorder) GetTasksByWorkflowId(workflowId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByWorkflowId", reflect.TypeOf((*MockTaskService)(nil).GetTasksByWorkflowId), workflowId)
}

// UpdateTaskHistory mocks base method.
func (m *MockTaskService) UpdateTaskHistory(workflowHistoryId, taskId string, taskHistory tasks.UpdateTaskHistoryData) (*tasks.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskHistory", workflowHistoryId, taskId, taskHistory)
	ret0, _ := ret[0].(*tasks.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskHistory indicates an expected call of UpdateTaskHistory.
func (mr *MockTaskServiceMockRecorder) UpdateTaskHistory(workflowHistoryId, taskId, taskHistory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskHistory", reflect.TypeOf((*MockTaskService)(nil).UpdateTaskHistory), workflowHistoryId, taskId, taskHistory)
}

// UpdateTaskStatus mocks base method.
func (m *MockTaskService) UpdateTaskStatus(workflowHistoryId, taskId, status string) (*tasks.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatus", workflowHistoryId, taskId, status)
	ret0, _ := ret[0].(*tasks.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskStatus indicates an expected call of UpdateTaskStatus.
func (mr *MockTaskServiceMockRecorder) UpdateTaskStatus(workflowHistoryId, taskId, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatus", reflect.TypeOf((*MockTaskService)(nil).UpdateTaskStatus), workflowHistoryId, taskId, status)
}

// UpsertTasks mocks base method.
func (m *MockTaskService) UpsertTasks(tx *sqlx.Tx, workflowId uuid.UUID, arg2 []tasks.Tasks) ([]tasks.Tasks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTasks", tx, workflowId, arg2)
	ret0, _ := ret[0].([]tasks.Tasks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertTasks indicates an expected call of UpsertTasks.
func (mr *MockTaskServiceMockRecorder) UpsertTasks(tx, workflowId, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTasks", reflect.TypeOf((*MockTaskService)(nil).UpsertTasks), tx, workflowId, arg2)
}
