// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: workflow.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Workflow_HandleWorkflow_FullMethodName = "/Workflow/HandleWorkflow"
	Workflow_HandleTask_FullMethodName     = "/Workflow/HandleTask"
)

// WorkflowClient is the client API for Workflow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkflowClient interface {
	HandleWorkflow(ctx context.Context, in *WorkflowStatusPayload, opts ...grpc.CallOption) (*WorkflowHistory, error)
	HandleTask(ctx context.Context, in *TaskStatusPayload, opts ...grpc.CallOption) (*TaskHistory, error)
}

type workflowClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowClient(cc grpc.ClientConnInterface) WorkflowClient {
	return &workflowClient{cc}
}

func (c *workflowClient) HandleWorkflow(ctx context.Context, in *WorkflowStatusPayload, opts ...grpc.CallOption) (*WorkflowHistory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowHistory)
	err := c.cc.Invoke(ctx, Workflow_HandleWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowClient) HandleTask(ctx context.Context, in *TaskStatusPayload, opts ...grpc.CallOption) (*TaskHistory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskHistory)
	err := c.cc.Invoke(ctx, Workflow_HandleTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowServer is the server API for Workflow service.
// All implementations must embed UnimplementedWorkflowServer
// for forward compatibility.
type WorkflowServer interface {
	HandleWorkflow(context.Context, *WorkflowStatusPayload) (*WorkflowHistory, error)
	HandleTask(context.Context, *TaskStatusPayload) (*TaskHistory, error)
	mustEmbedUnimplementedWorkflowServer()
}

// UnimplementedWorkflowServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkflowServer struct{}

func (UnimplementedWorkflowServer) HandleWorkflow(context.Context, *WorkflowStatusPayload) (*WorkflowHistory, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleWorkflow not implemented")
}
func (UnimplementedWorkflowServer) HandleTask(context.Context, *TaskStatusPayload) (*TaskHistory, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleTask not implemented")
}
func (UnimplementedWorkflowServer) mustEmbedUnimplementedWorkflowServer() {}
func (UnimplementedWorkflowServer) testEmbeddedByValue()                  {}

// UnsafeWorkflowServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowServer will
// result in compilation errors.
type UnsafeWorkflowServer interface {
	mustEmbedUnimplementedWorkflowServer()
}

func RegisterWorkflowServer(s grpc.ServiceRegistrar, srv WorkflowServer) {
	// If the following call panics, it indicates UnimplementedWorkflowServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Workflow_ServiceDesc, srv)
}

func _Workflow_HandleWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowStatusPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServer).HandleWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workflow_HandleWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServer).HandleWorkflow(ctx, req.(*WorkflowStatusPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflow_HandleTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskStatusPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServer).HandleTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workflow_HandleTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServer).HandleTask(ctx, req.(*TaskStatusPayload))
	}
	return interceptor(ctx, in, info, handler)
}

// Workflow_ServiceDesc is the grpc.ServiceDesc for Workflow service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Workflow_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Workflow",
	HandlerType: (*WorkflowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleWorkflow",
			Handler:    _Workflow_HandleWorkflow_Handler,
		},
		{
			MethodName: "HandleTask",
			Handler:    _Workflow_HandleTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workflow.proto",
}
