// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: workflow.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowStatusPayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WorkflowHistoryId string                 `protobuf:"bytes,1,opt,name=workflow_history_id,json=workflowHistoryId,proto3" json:"workflow_history_id,omitempty"`
	Status            *string                `protobuf:"bytes,2,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Error             *string                `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Result            *string                `protobuf:"bytes,4,opt,name=result,proto3,oneof" json:"result,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WorkflowStatusPayload) Reset() {
	*x = WorkflowStatusPayload{}
	mi := &file_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStatusPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStatusPayload) ProtoMessage() {}

func (x *WorkflowStatusPayload) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStatusPayload.ProtoReflect.Descriptor instead.
func (*WorkflowStatusPayload) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowStatusPayload) GetWorkflowHistoryId() string {
	if x != nil {
		return x.WorkflowHistoryId
	}
	return ""
}

func (x *WorkflowStatusPayload) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *WorkflowStatusPayload) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *WorkflowStatusPayload) GetResult() string {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ""
}

type WorkflowHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Error         *string                `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Result        *structpb.Value        `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	TriggeredAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=triggered_at,json=triggeredAt,proto3" json:"triggered_at,omitempty"`
	Edges         *structpb.Struct       `protobuf:"bytes,7,opt,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowHistory) Reset() {
	*x = WorkflowHistory{}
	mi := &file_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowHistory) ProtoMessage() {}

func (x *WorkflowHistory) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowHistory.ProtoReflect.Descriptor instead.
func (*WorkflowHistory) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowHistory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowHistory) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowHistory) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowHistory) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *WorkflowHistory) GetResult() *structpb.Value {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *WorkflowHistory) GetTriggeredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TriggeredAt
	}
	return nil
}

func (x *WorkflowHistory) GetEdges() *structpb.Struct {
	if x != nil {
		return x.Edges
	}
	return nil
}

var File_workflow_proto protoreflect.FileDescriptor

const file_workflow_proto_rawDesc = "" +
	"\n" +
	"\x0eworkflow.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xbc\x01\n" +
	"\x15WorkflowStatusPayload\x12.\n" +
	"\x13workflow_history_id\x18\x01 \x01(\tR\x11workflowHistoryId\x12\x1b\n" +
	"\x06status\x18\x02 \x01(\tH\x00R\x06status\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x01R\x05error\x88\x01\x01\x12\x1b\n" +
	"\x06result\x18\x04 \x01(\tH\x02R\x06result\x88\x01\x01B\t\n" +
	"\a_statusB\b\n" +
	"\x06_errorB\t\n" +
	"\a_result\"\x9d\x02\n" +
	"\x0fWorkflowHistory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x19\n" +
	"\x05error\x18\x04 \x01(\tH\x00R\x05error\x88\x01\x01\x12.\n" +
	"\x06result\x18\x05 \x01(\v2\x16.google.protobuf.ValueR\x06result\x12=\n" +
	"\ftriggered_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vtriggeredAt\x12-\n" +
	"\x05edges\x18\a \x01(\v2\x17.google.protobuf.StructR\x05edgesB\b\n" +
	"\x06_error2H\n" +
	"\bWorkflow\x12<\n" +
	"\x0eHandleWorkflow\x12\x16.WorkflowStatusPayload\x1a\x10.WorkflowHistory\"\x00b\x06proto3"

var (
	file_workflow_proto_rawDescOnce sync.Once
	file_workflow_proto_rawDescData []byte
)

func file_workflow_proto_rawDescGZIP() []byte {
	file_workflow_proto_rawDescOnce.Do(func() {
		file_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)))
	})
	return file_workflow_proto_rawDescData
}

var file_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_workflow_proto_goTypes = []any{
	(*WorkflowStatusPayload)(nil), // 0: WorkflowStatusPayload
	(*WorkflowHistory)(nil),       // 1: WorkflowHistory
	(*structpb.Value)(nil),        // 2: google.protobuf.Value
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 4: google.protobuf.Struct
}
var file_workflow_proto_depIdxs = []int32{
	2, // 0: WorkflowHistory.result:type_name -> google.protobuf.Value
	3, // 1: WorkflowHistory.triggered_at:type_name -> google.protobuf.Timestamp
	4, // 2: WorkflowHistory.edges:type_name -> google.protobuf.Struct
	0, // 3: Workflow.HandleWorkflow:input_type -> WorkflowStatusPayload
	1, // 4: Workflow.HandleWorkflow:output_type -> WorkflowHistory
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_workflow_proto_init() }
func file_workflow_proto_init() {
	if File_workflow_proto != nil {
		return
	}
	file_workflow_proto_msgTypes[0].OneofWrappers = []any{}
	file_workflow_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workflow_proto_goTypes,
		DependencyIndexes: file_workflow_proto_depIdxs,
		MessageInfos:      file_workflow_proto_msgTypes,
	}.Build()
	File_workflow_proto = out.File
	file_workflow_proto_goTypes = nil
	file_workflow_proto_depIdxs = nil
}
