// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/workflow_service/internal/edges/repository.go
//
// Generated by this command:
//
//	mockgen -source=./app/workflow_service/internal/edges/repository.go -destination=./app/workflow_service/internal/edges/mocks/repository_mock.go
//

// Package mock_edges is a generated GoMock package.
package mock_edges

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	sqlx "github.com/jmoiron/sqlx"
	edges "github.com/yuudev14-workflow/workflow-service/internal/edges"
	gomock "go.uber.org/mock/gomock"
)

// MockEdgeRepository is a mock of EdgeRepository interface.
type MockEdgeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEdgeRepositoryMockRecorder
	isgomock struct{}
}

// MockEdgeRepositoryMockRecorder is the mock recorder for MockEdgeRepository.
type MockEdgeRepositoryMockRecorder struct {
	mock *MockEdgeRepository
}

// NewMockEdgeRepository creates a new mock instance.
func NewMockEdgeRepository(ctrl *gomock.Controller) *MockEdgeRepository {
	mock := &MockEdgeRepository{ctrl: ctrl}
	mock.recorder = &MockEdgeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEdgeRepository) EXPECT() *MockEdgeRepositoryMockRecorder {
	return m.recorder
}

// DeleteAllWorkflowEdges mocks base method.
func (m *MockEdgeRepository) DeleteAllWorkflowEdges(tx *sqlx.Tx, workflowId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllWorkflowEdges", tx, workflowId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllWorkflowEdges indicates an expected call of DeleteAllWorkflowEdges.
func (mr *MockEdgeRepositoryMockRecorder) DeleteAllWorkflowEdges(tx, workflowId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllWorkflowEdges", reflect.TypeOf((*MockEdgeRepository)(nil).DeleteAllWorkflowEdges), tx, workflowId)
}

// DeleteEdges mocks base method.
func (m *MockEdgeRepository) DeleteEdges(tx *sqlx.Tx, edgeIds []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEdges", tx, edgeIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEdges indicates an expected call of DeleteEdges.
func (mr *MockEdgeRepositoryMockRecorder) DeleteEdges(tx, edgeIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEdges", reflect.TypeOf((*MockEdgeRepository)(nil).DeleteEdges), tx, edgeIds)
}

// GetEdgesByWorkflowId mocks base method.
func (m *MockEdgeRepository) GetEdgesByWorkflowId(workflowId string) ([]edges.ResponseEdges, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEdgesByWorkflowId", workflowId)
	ret0, _ := ret[0].([]edges.ResponseEdges)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEdgesByWorkflowId indicates an expected call of GetEdgesByWorkflowId.
func (mr *MockEdgeRepositoryMockRecorder) GetEdgesByWorkflowId(workflowId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEdgesByWorkflowId", reflect.TypeOf((*MockEdgeRepository)(nil).GetEdgesByWorkflowId), workflowId)
}

// InsertEdges mocks base method.
func (m *MockEdgeRepository) InsertEdges(tx *sqlx.Tx, arg1 []edges.Edges) ([]edges.Edges, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEdges", tx, arg1)
	ret0, _ := ret[0].([]edges.Edges)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertEdges indicates an expected call of InsertEdges.
func (mr *MockEdgeRepositoryMockRecorder) InsertEdges(tx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEdges", reflect.TypeOf((*MockEdgeRepository)(nil).InsertEdges), tx, arg1)
}
