// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/workflow_service/internal/edges/service.go
//
// Generated by this command:
//
//	mockgen -source=./app/workflow_service/internal/edges/service.go -destination=./app/workflow_service/internal/edges/mocks/service_mock.go
//

// Package mock_edges is a generated GoMock package.
package mock_edges

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	sqlx "github.com/jmoiron/sqlx"
	edges "github.com/yuudev14-workflow/workflow-service/internal/edges"
	gomock "go.uber.org/mock/gomock"
)

// MockEdgeService is a mock of EdgeService interface.
type MockEdgeService struct {
	ctrl     *gomock.Controller
	recorder *MockEdgeServiceMockRecorder
	isgomock struct{}
}

// MockEdgeServiceMockRecorder is the mock recorder for MockEdgeService.
type MockEdgeServiceMockRecorder struct {
	mock *MockEdgeService
}

// NewMockEdgeService creates a new mock instance.
func NewMockEdgeService(ctrl *gomock.Controller) *MockEdgeService {
	mock := &MockEdgeService{ctrl: ctrl}
	mock.recorder = &MockEdgeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEdgeService) EXPECT() *MockEdgeServiceMockRecorder {
	return m.recorder
}

// DeleteAllWorkflowEdges mocks base method.
func (m *MockEdgeService) DeleteAllWorkflowEdges(tx *sqlx.Tx, workflowId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllWorkflowEdges", tx, workflowId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllWorkflowEdges indicates an expected call of DeleteAllWorkflowEdges.
func (mr *MockEdgeServiceMockRecorder) DeleteAllWorkflowEdges(tx, workflowId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllWorkflowEdges", reflect.TypeOf((*MockEdgeService)(nil).DeleteAllWorkflowEdges), tx, workflowId)
}

// DeleteEdges mocks base method.
func (m *MockEdgeService) DeleteEdges(tx *sqlx.Tx, edgeIds []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEdges", tx, edgeIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEdges indicates an expected call of DeleteEdges.
func (mr *MockEdgeServiceMockRecorder) DeleteEdges(tx, edgeIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEdges", reflect.TypeOf((*MockEdgeService)(nil).DeleteEdges), tx, edgeIds)
}

// GetEdgesByWorkflowId mocks base method.
func (m *MockEdgeService) GetEdgesByWorkflowId(workflowId string) ([]edges.ResponseEdges, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEdgesByWorkflowId", workflowId)
	ret0, _ := ret[0].([]edges.ResponseEdges)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEdgesByWorkflowId indicates an expected call of GetEdgesByWorkflowId.
func (mr *MockEdgeServiceMockRecorder) GetEdgesByWorkflowId(workflowId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEdgesByWorkflowId", reflect.TypeOf((*MockEdgeService)(nil).GetEdgesByWorkflowId), workflowId)
}

// InsertEdges mocks base method.
func (m *MockEdgeService) InsertEdges(tx *sqlx.Tx, arg1 []edges.Edges) ([]edges.Edges, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEdges", tx, arg1)
	ret0, _ := ret[0].([]edges.Edges)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertEdges indicates an expected call of InsertEdges.
func (mr *MockEdgeServiceMockRecorder) InsertEdges(tx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEdges", reflect.TypeOf((*MockEdgeService)(nil).InsertEdges), tx, arg1)
}
