// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/contracts (interfaces: ModuleEventPublisher)
//
// Generated by this command:
//
//	mockgen -destination=mocks/module_event_publisher_mock.go -package=mocks . ModuleEventPublisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockModuleEventPublisher is a mock of ModuleEventPublisher interface.
type MockModuleEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockModuleEventPublisherMockRecorder
	isgomock struct{}
}

// MockModuleEventPublisherMockRecorder is the mock recorder for MockModuleEventPublisher.
type MockModuleEventPublisherMockRecorder struct {
	mock *MockModuleEventPublisher
}

// NewMockModuleEventPublisher creates a new mock instance.
func NewMockModuleEventPublisher(ctrl *gomock.Controller) *MockModuleEventPublisher {
	mock := &MockModuleEventPublisher{ctrl: ctrl}
	mock.recorder = &MockModuleEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModuleEventPublisher) EXPECT() *MockModuleEventPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockModuleEventPublisher) Publish(module, event string, entity any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", module, event, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockModuleEventPublisherMockRecorder) Publish(module, event, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockModuleEventPublisher)(nil).Publish), module, event, entity)
}
