// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/contracts (interfaces: StatusBroadcaster)
//
// Generated by this command:
//
//	mockgen -destination=mocks/status_broadcaster_mock.go -package=mocks . StatusBroadcaster
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStatusBroadcaster is a mock of StatusBroadcaster interface.
type MockStatusBroadcaster struct {
	ctrl     *gomock.Controller
	recorder *MockStatusBroadcasterMockRecorder
	isgomock struct{}
}

// MockStatusBroadcasterMockRecorder is the mock recorder for MockStatusBroadcaster.
type MockStatusBroadcasterMockRecorder struct {
	mock *MockStatusBroadcaster
}

// NewMockStatusBroadcaster creates a new mock instance.
func NewMockStatusBroadcaster(ctrl *gomock.Controller) *MockStatusBroadcaster {
	mock := &MockStatusBroadcaster{ctrl: ctrl}
	mock.recorder = &MockStatusBroadcasterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusBroadcaster) EXPECT() *MockStatusBroadcasterMockRecorder {
	return m.recorder
}

// Broadcast mocks base method.
func (m *MockStatusBroadcaster) Broadcast(data any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Broadcast", data)
}

// Broadcast indicates an expected call of Broadcast.
func (mr *MockStatusBroadcasterMockRecorder) Broadcast(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*MockStatusBroadcaster)(nil).Broadcast), data)
}
