// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/contracts (interfaces: UserDirectory)
//
// Generated by this command:
//
//	mockgen -destination=mocks/user_directory_mock.go -package=mocks . UserDirectory
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserDirectory is a mock of UserDirectory interface.
type MockUserDirectory struct {
	ctrl     *gomock.Controller
	recorder *MockUserDirectoryMockRecorder
	isgomock struct{}
}

// MockUserDirectoryMockRecorder is the mock recorder for MockUserDirectory.
type MockUserDirectoryMockRecorder struct {
	mock *MockUserDirectory
}

// NewMockUserDirectory creates a new mock instance.
func NewMockUserDirectory(ctrl *gomock.Controller) *MockUserDirectory {
	mock := &MockUserDirectory{ctrl: ctrl}
	mock.recorder = &MockUserDirectoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDirectory) EXPECT() *MockUserDirectoryMockRecorder {
	return m.recorder
}

// UsernamesByIDs mocks base method.
func (m *MockUserDirectory) UsernamesByIDs(ctx context.Context, ids []uuid.UUID) (map[uuid.UUID]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UsernamesByIDs", ctx, ids)
	ret0, _ := ret[0].(map[uuid.UUID]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UsernamesByIDs indicates an expected call of UsernamesByIDs.
func (mr *MockUserDirectoryMockRecorder) UsernamesByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UsernamesByIDs", reflect.TypeOf((*MockUserDirectory)(nil).UsernamesByIDs), ctx, ids)
}
