FROM python:3.12-alpine3.20

RUN apk add --no-cache \
    postgresql-dev \
    gcc \
    musl-dev \
    libffi-dev \
    curl \
    ca-certificates

RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:$PATH"


WORKDIR /app


COPY pyproject.toml uv.lock ./


RUN uv venv /opt/venv \
 && source /opt/venv/bin/activate \
 && uv sync --active

COPY . .

EXPOSE 8000

CMD ["/opt/venv/bin/python3", "main.py"]
