FROM python:3.13-alpine3.20

# Install build and PostgreSQL dependencies
RUN apk update && apk add --no-cache \
    postgresql-dev \
    gcc \
    musl-dev \
    libffi-dev

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

# COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--reload", "--port=8000", "--host=0.0.0.0"]