// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/playbooks (interfaces: PlaybookApplicationService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/orchestrator_mock.go -package=mocks . PlaybookApplicationService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	playbooks "github.com/yuudev14/ytsoar/internal/application/playbooks"
	tasks "github.com/yuudev14/ytsoar/internal/application/tasks"
	domain "github.com/yuudev14/ytsoar/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPlaybookApplicationService is a mock of PlaybookApplicationService interface.
type MockPlaybookApplicationService struct {
	ctrl     *gomock.Controller
	recorder *MockPlaybookApplicationServiceMockRecorder
	isgomock struct{}
}

// MockPlaybookApplicationServiceMockRecorder is the mock recorder for MockPlaybookApplicationService.
type MockPlaybookApplicationServiceMockRecorder struct {
	mock *MockPlaybookApplicationService
}

// NewMockPlaybookApplicationService creates a new mock instance.
func NewMockPlaybookApplicationService(ctrl *gomock.Controller) *MockPlaybookApplicationService {
	mock := &MockPlaybookApplicationService{ctrl: ctrl}
	mock.recorder = &MockPlaybookApplicationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlaybookApplicationService) EXPECT() *MockPlaybookApplicationServiceMockRecorder {
	return m.recorder
}

// DeleteEdges mocks base method.
func (m *MockPlaybookApplicationService) DeleteEdges(ctx context.Context, playbookUUID uuid.UUID, edges map[string][]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEdges", ctx, playbookUUID, edges)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEdges indicates an expected call of DeleteEdges.
func (mr *MockPlaybookApplicationServiceMockRecorder) DeleteEdges(ctx, playbookUUID, edges any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEdges", reflect.TypeOf((*MockPlaybookApplicationService)(nil).DeleteEdges), ctx, playbookUUID, edges)
}

// DeleteTasks mocks base method.
func (m *MockPlaybookApplicationService) DeleteTasks(ctx context.Context, playbookUUID uuid.UUID, nodes []tasks.TaskPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTasks", ctx, playbookUUID, nodes)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTasks indicates an expected call of DeleteTasks.
func (mr *MockPlaybookApplicationServiceMockRecorder) DeleteTasks(ctx, playbookUUID, nodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTasks", reflect.TypeOf((*MockPlaybookApplicationService)(nil).DeleteTasks), ctx, playbookUUID, nodes)
}

// InsertEdges mocks base method.
func (m *MockPlaybookApplicationService) InsertEdges(ctx context.Context, playbookUUID uuid.UUID, edges map[string][]string, arg3 []domain.Tasks, handles map[string]map[string]domain.EdgeHandle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEdges", ctx, playbookUUID, edges, arg3, handles)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertEdges indicates an expected call of InsertEdges.
func (mr *MockPlaybookApplicationServiceMockRecorder) InsertEdges(ctx, playbookUUID, edges, arg3, handles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEdges", reflect.TypeOf((*MockPlaybookApplicationService)(nil).InsertEdges), ctx, playbookUUID, edges, arg3, handles)
}

// PreparePlaybookMessage mocks base method.
func (m *MockPlaybookApplicationService) PreparePlaybookMessage(arg0 []domain.Tasks, edges []domain.ResponseEdges) (map[string]domain.Tasks, map[string][]string, []domain.EdgeRef) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreparePlaybookMessage", arg0, edges)
	ret0, _ := ret[0].(map[string]domain.Tasks)
	ret1, _ := ret[1].(map[string][]string)
	ret2, _ := ret[2].([]domain.EdgeRef)
	return ret0, ret1, ret2
}

// PreparePlaybookMessage indicates an expected call of PreparePlaybookMessage.
func (mr *MockPlaybookApplicationServiceMockRecorder) PreparePlaybookMessage(arg0, edges any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreparePlaybookMessage", reflect.TypeOf((*MockPlaybookApplicationService)(nil).PreparePlaybookMessage), arg0, edges)
}

// TriggerPlaybook mocks base method.
func (m *MockPlaybookApplicationService) TriggerPlaybook(ctx context.Context, playbookId string) (*domain.TaskMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerPlaybook", ctx, playbookId)
	ret0, _ := ret[0].(*domain.TaskMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerPlaybook indicates an expected call of TriggerPlaybook.
func (mr *MockPlaybookApplicationServiceMockRecorder) TriggerPlaybook(ctx, playbookId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerPlaybook", reflect.TypeOf((*MockPlaybookApplicationService)(nil).TriggerPlaybook), ctx, playbookId)
}

// UpdatePlaybookTasks mocks base method.
func (m *MockPlaybookApplicationService) UpdatePlaybookTasks(ctx context.Context, playbookId string, body playbooks.UpdatePlaybookTasksPayload) (*domain.PlaybookGraph, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaybookTasks", ctx, playbookId, body)
	ret0, _ := ret[0].(*domain.PlaybookGraph)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlaybookTasks indicates an expected call of UpdatePlaybookTasks.
func (mr *MockPlaybookApplicationServiceMockRecorder) UpdatePlaybookTasks(ctx, playbookId, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaybookTasks", reflect.TypeOf((*MockPlaybookApplicationService)(nil).UpdatePlaybookTasks), ctx, playbookId, body)
}

// UpsertTasks mocks base method.
func (m *MockPlaybookApplicationService) UpsertTasks(ctx context.Context, playbookUUID uuid.UUID, nodes []tasks.TaskPayload) ([]domain.Tasks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTasks", ctx, playbookUUID, nodes)
	ret0, _ := ret[0].([]domain.Tasks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertTasks indicates an expected call of UpsertTasks.
func (mr *MockPlaybookApplicationServiceMockRecorder) UpsertTasks(ctx, playbookUUID, nodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTasks", reflect.TypeOf((*MockPlaybookApplicationService)(nil).UpsertTasks), ctx, playbookUUID, nodes)
}
