// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yuudev14/ytsoar/internal/application/playbooks (interfaces: PlaybookRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/repository_mock.go -package=mocks . PlaybookRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	playbooks "github.com/yuudev14/ytsoar/internal/application/playbooks"
	domain "github.com/yuudev14/ytsoar/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPlaybookRepository is a mock of PlaybookRepository interface.
type MockPlaybookRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPlaybookRepositoryMockRecorder
	isgomock struct{}
}

// MockPlaybookRepositoryMockRecorder is the mock recorder for MockPlaybookRepository.
type MockPlaybookRepositoryMockRecorder struct {
	mock *MockPlaybookRepository
}

// NewMockPlaybookRepository creates a new mock instance.
func NewMockPlaybookRepository(ctrl *gomock.Controller) *MockPlaybookRepository {
	mock := &MockPlaybookRepository{ctrl: ctrl}
	mock.recorder = &MockPlaybookRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlaybookRepository) EXPECT() *MockPlaybookRepositoryMockRecorder {
	return m.recorder
}

// CreatePlaybook mocks base method.
func (m *MockPlaybookRepository) CreatePlaybook(ctx context.Context, playbook playbooks.PlaybookPayload) (*domain.Playbooks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlaybook", ctx, playbook)
	ret0, _ := ret[0].(*domain.Playbooks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePlaybook indicates an expected call of CreatePlaybook.
func (mr *MockPlaybookRepositoryMockRecorder) CreatePlaybook(ctx, playbook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlaybook", reflect.TypeOf((*MockPlaybookRepository)(nil).CreatePlaybook), ctx, playbook)
}

// CreatePlaybookHistory mocks base method.
func (m *MockPlaybookRepository) CreatePlaybookHistory(ctx context.Context, id string, edges []domain.ResponseEdges) (*domain.PlaybookHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlaybookHistory", ctx, id, edges)
	ret0, _ := ret[0].(*domain.PlaybookHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePlaybookHistory indicates an expected call of CreatePlaybookHistory.
func (mr *MockPlaybookRepositoryMockRecorder) CreatePlaybookHistory(ctx, id, edges any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlaybookHistory", reflect.TypeOf((*MockPlaybookRepository)(nil).CreatePlaybookHistory), ctx, id, edges)
}

// GetPlaybookById mocks base method.
func (m *MockPlaybookRepository) GetPlaybookById(ctx context.Context, id string) (*domain.Playbooks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookById", ctx, id)
	ret0, _ := ret[0].(*domain.Playbooks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookById indicates an expected call of GetPlaybookById.
func (mr *MockPlaybookRepositoryMockRecorder) GetPlaybookById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookById", reflect.TypeOf((*MockPlaybookRepository)(nil).GetPlaybookById), ctx, id)
}

// GetPlaybookGraphById mocks base method.
func (m *MockPlaybookRepository) GetPlaybookGraphById(ctx context.Context, id string) (*domain.PlaybookGraph, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookGraphById", ctx, id)
	ret0, _ := ret[0].(*domain.PlaybookGraph)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookGraphById indicates an expected call of GetPlaybookGraphById.
func (mr *MockPlaybookRepositoryMockRecorder) GetPlaybookGraphById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookGraphById", reflect.TypeOf((*MockPlaybookRepository)(nil).GetPlaybookGraphById), ctx, id)
}

// GetPlaybookHistory mocks base method.
func (m *MockPlaybookRepository) GetPlaybookHistory(ctx context.Context, offset, limit int, filter playbooks.PlaybookHistoryFilter) ([]domain.PlaybookHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookHistory", ctx, offset, limit, filter)
	ret0, _ := ret[0].([]domain.PlaybookHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookHistory indicates an expected call of GetPlaybookHistory.
func (mr *MockPlaybookRepositoryMockRecorder) GetPlaybookHistory(ctx, offset, limit, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookHistory", reflect.TypeOf((*MockPlaybookRepository)(nil).GetPlaybookHistory), ctx, offset, limit, filter)
}

// GetPlaybookHistoryById mocks base method.
func (m *MockPlaybookRepository) GetPlaybookHistoryById(ctx context.Context, playbookHistoryId uuid.UUID) (*domain.PlaybookHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookHistoryById", ctx, playbookHistoryId)
	ret0, _ := ret[0].(*domain.PlaybookHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookHistoryById indicates an expected call of GetPlaybookHistoryById.
func (mr *MockPlaybookRepositoryMockRecorder) GetPlaybookHistoryById(ctx, playbookHistoryId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookHistoryById", reflect.TypeOf((*MockPlaybookRepository)(nil).GetPlaybookHistoryById), ctx, playbookHistoryId)
}

// GetPlaybookHistoryCount mocks base method.
func (m *MockPlaybookRepository) GetPlaybookHistoryCount(ctx context.Context, filter playbooks.PlaybookHistoryFilter) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookHistoryCount", ctx, filter)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookHistoryCount indicates an expected call of GetPlaybookHistoryCount.
func (mr *MockPlaybookRepositoryMockRecorder) GetPlaybookHistoryCount(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookHistoryCount", reflect.TypeOf((*MockPlaybookRepository)(nil).GetPlaybookHistoryCount), ctx, filter)
}

// GetPlaybooks mocks base method.
func (m *MockPlaybookRepository) GetPlaybooks(ctx context.Context, offset, limit int, filter playbooks.PlaybookFilter) ([]domain.Playbooks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybooks", ctx, offset, limit, filter)
	ret0, _ := ret[0].([]domain.Playbooks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybooks indicates an expected call of GetPlaybooks.
func (mr *MockPlaybookRepositoryMockRecorder) GetPlaybooks(ctx, offset, limit, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybooks", reflect.TypeOf((*MockPlaybookRepository)(nil).GetPlaybooks), ctx, offset, limit, filter)
}

// GetPlaybooksCount mocks base method.
func (m *MockPlaybookRepository) GetPlaybooksCount(ctx context.Context, filter playbooks.PlaybookFilter) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybooksCount", ctx, filter)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybooksCount indicates an expected call of GetPlaybooksCount.
func (mr *MockPlaybookRepositoryMockRecorder) GetPlaybooksCount(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybooksCount", reflect.TypeOf((*MockPlaybookRepository)(nil).GetPlaybooksCount), ctx, filter)
}

// UpdatePlaybook mocks base method.
func (m *MockPlaybookRepository) UpdatePlaybook(ctx context.Context, id string, playbook playbooks.UpdatePlaybookData) (*domain.Playbooks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaybook", ctx, id, playbook)
	ret0, _ := ret[0].(*domain.Playbooks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlaybook indicates an expected call of UpdatePlaybook.
func (mr *MockPlaybookRepositoryMockRecorder) UpdatePlaybook(ctx, id, playbook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaybook", reflect.TypeOf((*MockPlaybookRepository)(nil).UpdatePlaybook), ctx, id, playbook)
}

// UpdatePlaybookHistory mocks base method.
func (m *MockPlaybookRepository) UpdatePlaybookHistory(ctx context.Context, playbookHistoryId string, playbookHistory playbooks.UpdatePlaybookHistoryData) (*domain.PlaybookHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaybookHistory", ctx, playbookHistoryId, playbookHistory)
	ret0, _ := ret[0].(*domain.PlaybookHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlaybookHistory indicates an expected call of UpdatePlaybookHistory.
func (mr *MockPlaybookRepositoryMockRecorder) UpdatePlaybookHistory(ctx, playbookHistoryId, playbookHistory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaybookHistory", reflect.TypeOf((*MockPlaybookRepository)(nil).UpdatePlaybookHistory), ctx, playbookHistoryId, playbookHistory)
}

// UpdatePlaybookHistoryStatus mocks base method.
func (m *MockPlaybookRepository) UpdatePlaybookHistoryStatus(ctx context.Context, playbookHistoryId, status string) (*domain.PlaybookHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaybookHistoryStatus", ctx, playbookHistoryId, status)
	ret0, _ := ret[0].(*domain.PlaybookHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlaybookHistoryStatus indicates an expected call of UpdatePlaybookHistoryStatus.
func (mr *MockPlaybookRepositoryMockRecorder) UpdatePlaybookHistoryStatus(ctx, playbookHistoryId, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaybookHistoryStatus", reflect.TypeOf((*MockPlaybookRepository)(nil).UpdatePlaybookHistoryStatus), ctx, playbookHistoryId, status)
}
